name: Deploy Angular to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/BonzoByte.Frontend/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'apps/BonzoByte.Frontend/package-lock.json'

      - name: Install deps
        working-directory: apps/BonzoByte.Frontend
        run: npm ci

      # ⬇️ Build u fiksni folder da nema dilema
      - name: Build Angular (project pages)
        working-directory: apps/BonzoByte.Frontend
        run: npx ng build --configuration production --base-href "/BonzoByte/" --deploy-url "/BonzoByte/" --output-path dist/site

      # SPA fallback
      - name: Add 404 fallback
        working-directory: apps/BonzoByte.Frontend
        run: cp dist/site/index.html dist/site/404.html

      # Debug listing (vidi se u logu)
      - name: List output
        working-directory: apps/BonzoByte.Frontend
        run: ls -la dist/site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/BonzoByte.Frontend/dist/site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4