using BonzoByte.Core.Configs;
using BonzoByte.Core.Models;
using Microsoft.Data.SqlClient;
using System.Data;

namespace BonzoByte.Core.DAL.Repositories
{
    public class PlayerRepository : IPlayerRepository
    {
        private readonly IDbConnection _connection;
        private readonly TrueskillSettings _trueSkillSettings;

        public PlayerRepository(IDbConnection connection, TrueskillSettings trueSkillSettings)
        {
            _connection = connection;
            _trueSkillSettings = trueSkillSettings;

        }

        public async Task<IEnumerable<Player>> GetAllPlayersAsync()
        {
            var Players = new List<Player>();

            using var command   = _connection.CreateCommand();
            command.CommandText = "GetAllPlayers";
            command.CommandType = CommandType.StoredProcedure;

            if (_connection.State != ConnectionState.Open) _connection.Open();

            using var reader = await Task.Run(() => command.ExecuteReader());
            while (await Task.Run(() => reader.Read()))
            {
                try
                {
                    var Player = new Player
                    {
                        PlayerTPId = reader["PlayerTPId"] as int?,
                        PlayerName = reader["PlayerName"] as string,
                        CountryTPId = reader["CountryTPId"] != DBNull.Value ? Convert.ToInt32(reader["CountryTPId"]) : (int?)null,
                        PlayerBirthDate = reader["PlayerBirthDate"] as DateTime?,
                        PlayerHeight = reader["PlayerHeight"] != DBNull.Value ? Convert.ToInt32(reader["PlayerHeight"]) : (int?)null,
                        PlayerWeight = reader["PlayerWeight"] != DBNull.Value ? Convert.ToInt32(reader["PlayerWeight"]) : (int?)null,
                        PlayerTurnedPro = reader["PlayerTurnedPro"] as int?,
                        PlaysId = reader["PlaysId"] != DBNull.Value ? Convert.ToInt32(reader["PlaysId"]) : (int?)null,
                        TournamentTypeId = reader["TournamentTypeId"] != DBNull.Value ? Convert.ToInt32(reader["TournamentTypeId"]) : (int?)null,
                        TrueSkillMeanM = reader["TrueSkillMeanM"] as double?,
                        TrueSkillStandardDeviationM = reader["TrueSkillStandardDeviationM"] as double?,
                        TrueSkillMeanSM = reader["TrueSkillMeanSM"] as double?,
                        TrueSkillStandardDeviationSM = reader["TrueSkillStandardDeviationSM"] as double?,
                        TrueSkillMeanGSM = reader["TrueSkillMeanGSM"] as double?,
                        TrueSkillStandardDeviationGSM = reader["TrueSkillStandardDeviationGSM"] as double?,
                        TrueSkillMeanMS1 = reader["TrueSkillMeanMS1"] as double?,
                        TrueSkillStandardDeviationMS1 = reader["TrueSkillStandardDeviationMS1"] as double?,
                        TrueSkillMeanSMS1 = reader["TrueSkillMeanSMS1"] as double?,
                        TrueSkillStandardDeviationSMS1 = reader["TrueSkillStandardDeviationSMS1"] as double?,
                        TrueSkillMeanGSMS1 = reader["TrueSkillMeanGSMS1"] as double?,
                        TrueSkillStandardDeviationGSMS1 = reader["TrueSkillStandardDeviationGSMS1"] as double?,
                        TrueSkillMeanMS2 = reader["TrueSkillMeanMS2"] as double?,
                        TrueSkillStandardDeviationMS2 = reader["TrueSkillStandardDeviationMS2"] as double?,
                        TrueSkillMeanSMS2 = reader["TrueSkillMeanSMS2"] as double?,
                        TrueSkillStandardDeviationSMS2 = reader["TrueSkillStandardDeviationSMS2"] as double?,
                        TrueSkillMeanGSMS2 = reader["TrueSkillMeanGSMS2"] as double?,
                        TrueSkillStandardDeviationGSMS2 = reader["TrueSkillStandardDeviationGSMS2"] as double?,
                        TrueSkillMeanMS3 = reader["TrueSkillMeanMS3"] as double?,
                        TrueSkillStandardDeviationMS3 = reader["TrueSkillStandardDeviationMS3"] as double?,
                        TrueSkillMeanSMS3 = reader["TrueSkillMeanSMS3"] as double?,
                        TrueSkillStandardDeviationSMS3 = reader["TrueSkillStandardDeviationSMS3"] as double?,
                        TrueSkillMeanGSMS3 = reader["TrueSkillMeanGSMS3"] as double?,
                        TrueSkillStandardDeviationGSMS3 = reader["TrueSkillStandardDeviationGSMS3"] as double?,
                        TrueSkillMeanMS4 = reader["TrueSkillMeanMS4"] as double?,
                        TrueSkillStandardDeviationMS4 = reader["TrueSkillStandardDeviationMS4"] as double?,
                        TrueSkillMeanSMS4 = reader["TrueSkillMeanSMS4"] as double?,
                        TrueSkillStandardDeviationSMS4 = reader["TrueSkillStandardDeviationSMS4"] as double?,
                        TrueSkillMeanGSMS4 = reader["TrueSkillMeanGSMS4"] as double?,
                        TrueSkillStandardDeviationGSMS4 = reader["TrueSkillStandardDeviationGSMS4"] as double?,
                        WinsTotal = reader["WinsTotal"] as int?,
                        LossesTotal = reader["LossesTotal"] as int?,
                        WinsLastYear = reader["WinsLastYear"] as int?,
                        LossesLastYear = reader["LossesLastYear"] as int?,
                        WinsLastMonth = reader["WinsLastMonth"] as int?,
                        LossesLastMonth = reader["LossesLastMonth"] as int?,
                        WinsLastWeek = reader["WinsLastWeek"] as int?,
                        LossesLastWeek = reader["LossesLastWeek"] as int?,
                        WinsTotalS1 = reader["WinsTotalS1"] as int?,
                        LossesTotalS1 = reader["LossesTotalS1"] as int?,
                        WinsLastYearS1 = reader["WinsLastYearS1"] as int?,
                        LossesLastYearS1 = reader["LossesLastYearS1"] as int?,
                        WinsLastMonthS1 = reader["WinsLastMonthS1"] as int?,
                        LossesLastMonthS1 = reader["LossesLastMonthS1"] as int?,
                        WinsLastWeekS1 = reader["WinsLastWeekS1"] as int?,
                        LossesLastWeekS1 = reader["LossesLastWeekS1"] as int?,
                        WinsTotalS2 = reader["WinsTotalS2"] as int?,
                        LossesTotalS2 = reader["LossesTotalS2"] as int?,
                        WinsLastYearS2 = reader["WinsLastYearS2"] as int?,
                        LossesLastYearS2 = reader["LossesLastYearS2"] as int?,
                        WinsLastMonthS2 = reader["WinsLastMonthS2"] as int?,
                        LossesLastMonthS2 = reader["LossesLastMonthS2"] as int?,
                        WinsLastWeekS2 = reader["WinsLastWeekS2"] as int?,
                        LossesLastWeekS2 = reader["LossesLastWeekS2"] as int?,
                        WinsTotalS3 = reader["WinsTotalS3"] as int?,
                        LossesTotalS3 = reader["LossesTotalS3"] as int?,
                        WinsLastYearS3 = reader["WinsLastYearS3"] as int?,
                        LossesLastYearS3 = reader["LossesLastYearS3"] as int?,
                        WinsLastMonthS3 = reader["WinsLastMonthS3"] as int?,
                        LossesLastMonthS3 = reader["LossesLastMonthS3"] as int?,
                        WinsLastWeekS3 = reader["WinsLastWeekS3"] as int?,
                        LossesLastWeekS3 = reader["LossesLastWeekS3"] as int?,
                        WinsTotalS4 = reader["WinsTotalS4"] as int?,
                        LossesTotalS4 = reader["LossesTotalS4"] as int?,
                        WinsLastYearS4 = reader["WinsLastYearS4"] as int?,
                        LossesLastYearS4 = reader["LossesLastYearS4"] as int?,
                        WinsLastMonthS4 = reader["WinsLastMonthS4"] as int?,
                        LossesLastMonthS4 = reader["LossesLastMonthS4"] as int?,
                        WinsLastWeekS4 = reader["WinsLastWeekS4"] as int?,
                        LossesLastWeekS4 = reader["LossesLastWeekS4"] as int?,
                        WinsSetsTotal = reader["WinsSetsTotal"] as int?,
                        LossesSetsTotal = reader["LossesSetsTotal"] as int?,
                        WinsSetsLastYear = reader["WinsSetsLastYear"] as int?,
                        LossesSetsLastYear = reader["LossesSetsLastYear"] as int?,
                        WinsSetsLastMonth = reader["WinsSetsLastMonth"] as int?,
                        LossesSetsLastMonth = reader["LossesSetsLastMonth"] as int?,
                        WinsSetsLastWeek = reader["WinsSetsLastWeek"] as int?,
                        LossesSetsLastWeek = reader["LossesSetsLastWeek"] as int?,
                        WinsSetsTotalS1 = reader["WinsSetsTotalS1"] as int?,
                        LossesSetsTotalS1 = reader["LossesSetsTotalS1"] as int?,
                        WinsSetsLastYearS1 = reader["WinsSetsLastYearS1"] as int?,
                        LossesSetsLastYearS1 = reader["LossesSetsLastYearS1"] as int?,
                        WinsSetsLastMonthS1 = reader["WinsSetsLastMonthS1"] as int?,
                        LossesSetsLastMonthS1 = reader["LossesSetsLastMonthS1"] as int?,
                        WinsSetsLastWeekS1 = reader["WinsSetsLastWeekS1"] as int?,
                        LossesSetsLastWeekS1 = reader["LossesSetsLastWeekS1"] as int?,
                        WinsSetsTotalS2 = reader["WinsSetsTotalS2"] as int?,
                        LossesSetsTotalS2 = reader["LossesSetsTotalS2"] as int?,
                        WinsSetsLastYearS2 = reader["WinsSetsLastYearS2"] as int?,
                        LossesSetsLastYearS2 = reader["LossesSetsLastYearS2"] as int?,
                        WinsSetsLastMonthS2 = reader["WinsSetsLastMonthS2"] as int?,
                        LossesSetsLastMonthS2 = reader["LossesSetsLastMonthS2"] as int?,
                        WinsSetsLastWeekS2 = reader["WinsSetsLastWeekS2"] as int?,
                        LossesSetsLastWeekS2 = reader["LossesSetsLastWeekS2"] as int?,
                        WinsSetsTotalS3 = reader["WinsSetsTotalS3"] as int?,
                        LossesSetsTotalS3 = reader["LossesSetsTotalS3"] as int?,
                        WinsSetsLastYearS3 = reader["WinsSetsLastYearS3"] as int?,
                        LossesSetsLastYearS3 = reader["LossesSetsLastYearS3"] as int?,
                        WinsSetsLastMonthS3 = reader["WinsSetsLastMonthS3"] as int?,
                        LossesSetsLastMonthS3 = reader["LossesSetsLastMonthS3"] as int?,
                        WinsSetsLastWeekS3 = reader["WinsSetsLastWeekS3"] as int?,
                        LossesSetsLastWeekS3 = reader["LossesSetsLastWeekS3"] as int?,
                        WinsSetsTotalS4 = reader["WinsSetsTotalS4"] as int?,
                        LossesSetsTotalS4 = reader["LossesSetsTotalS4"] as int?,
                        WinsSetsLastYearS4 = reader["WinsSetsLastYearS4"] as int?,
                        LossesSetsLastYearS4 = reader["LossesSetsLastYearS4"] as int?,
                        WinsSetsLastMonthS4 = reader["WinsSetsLastMonthS4"] as int?,
                        LossesSetsLastMonthS4 = reader["LossesSetsLastMonthS4"] as int?,
                        WinsSetsLastWeekS4 = reader["WinsSetsLastWeekS4"] as int?,
                        LossesSetsLastWeekS4 = reader["LossesSetsLastWeekS4"] as int?,
                        WinsGamesTotal = reader["WinsGamesTotal"] as int?,
                        LossesGamesTotal = reader["LossesGamesTotal"] as int?,
                        WinsGamesLastYear = reader["WinsGamesLastYear"] as int?,
                        LossesGamesLastYear = reader["LossesGamesLastYear"] as int?,
                        WinsGamesLastMonth = reader["WinsGamesLastMonth"] as int?,
                        LossesGamesLastMonth = reader["LossesGamesLastMonth"] as int?,
                        WinsGamesLastWeek = reader["WinsGamesLastWeek"] as int?,
                        LossesGamesLastWeek = reader["LossesGamesLastWeek"] as int?,
                        WinsGamesTotalS1 = reader["WinsGamesTotalS1"] as int?,
                        LossesGamesTotalS1 = reader["LossesGamesTotalS1"] as int?,
                        WinsGamesLastYearS1 = reader["WinsGamesLastYearS1"] as int?,
                        LossesGamesLastYearS1 = reader["LossesGamesLastYearS1"] as int?,
                        WinsGamesLastMonthS1 = reader["WinsGamesLastMonthS1"] as int?,
                        LossesGamesLastMonthS1 = reader["LossesGamesLastMonthS1"] as int?,
                        WinsGamesLastWeekS1 = reader["WinsGamesLastWeekS1"] as int?,
                        LossesGamesLastWeekS1 = reader["LossesGamesLastWeekS1"] as int?,
                        WinsGamesTotalS2 = reader["WinsGamesTotalS2"] as int?,
                        LossesGamesTotalS2 = reader["LossesGamesTotalS2"] as int?,
                        WinsGamesLastYearS2 = reader["WinsGamesLastYearS2"] as int?,
                        LossesGamesLastYearS2 = reader["LossesGamesLastYearS2"] as int?,
                        WinsGamesLastMonthS2 = reader["WinsGamesLastMonthS2"] as int?,
                        LossesGamesLastMonthS2 = reader["LossesGamesLastMonthS2"] as int?,
                        WinsGamesLastWeekS2 = reader["WinsGamesLastWeekS2"] as int?,
                        LossesGamesLastWeekS2 = reader["LossesGamesLastWeekS2"] as int?,
                        WinsGamesTotalS3 = reader["WinsGamesTotalS3"] as int?,
                        LossesGamesTotalS3 = reader["LossesGamesTotalS3"] as int?,
                        WinsGamesLastYearS3 = reader["WinsGamesLastYearS3"] as int?,
                        LossesGamesLastYearS3 = reader["LossesGamesLastYearS3"] as int?,
                        WinsGamesLastMonthS3 = reader["WinsGamesLastMonthS3"] as int?,
                        LossesGamesLastMonthS3 = reader["LossesGamesLastMonthS3"] as int?,
                        WinsGamesLastWeekS3 = reader["WinsGamesLastWeekS3"] as int?,
                        LossesGamesLastWeekS3 = reader["LossesGamesLastWeekS3"] as int?,
                        WinsGamesTotalS4 = reader["WinsGamesTotalS4"] as int?,
                        LossesGamesTotalS4 = reader["LossesGamesTotalS4"] as int?,
                        WinsGamesLastYearS4 = reader["WinsGamesLastYearS4"] as int?,
                        LossesGamesLastYearS4 = reader["LossesGamesLastYearS4"] as int?,
                        WinsGamesLastMonthS4 = reader["WinsGamesLastMonthS4"] as int?,
                        LossesGamesLastMonthS4 = reader["LossesGamesLastMonthS4"] as int?,
                        WinsGamesLastWeekS4 = reader["WinsGamesLastWeekS4"] as int?,
                        LossesGamesLastWeekS4 = reader["LossesGamesLastWeekS4"] as int?,
                        DateSinceLastWin = reader["DateSinceLastWin"] != DBNull.Value ? reader["DateSinceLastWin"] as DateTime? : null,
                        DateSinceLastWinS1 = reader["DateSinceLastWinS1"] != DBNull.Value ? reader["DateSinceLastWinS1"] as DateTime? : null,
                        DateSinceLastWinS2 = reader["DateSinceLastWinS2"] != DBNull.Value ? reader["DateSinceLastWinS2"] as DateTime? : null,
                        DateSinceLastWinS3 = reader["DateSinceLastWinS3"] != DBNull.Value ? reader["DateSinceLastWinS3"] as DateTime? : null,
                        DateSinceLastWinS4 = reader["DateSinceLastWinS4"] != DBNull.Value ? reader["DateSinceLastWinS4"] as DateTime? : null,
                        DateSinceLastLoss = reader["DateSinceLastLoss"] != DBNull.Value ? reader["DateSinceLastLoss"] as DateTime? : null,
                        DateSinceLastLossS1 = reader["DateSinceLastLossS1"] != DBNull.Value ? reader["DateSinceLastLossS1"] as DateTime? : null,
                        DateSinceLastLossS2 = reader["DateSinceLastLossS2"] != DBNull.Value ? reader["DateSinceLastLossS2"] as DateTime? : null,
                        DateSinceLastLossS3 = reader["DateSinceLastLossS3"] != DBNull.Value ? reader["DateSinceLastLossS3"] as DateTime? : null,
                        DateSinceLastLossS4 = reader["DateSinceLastLossS4"] != DBNull.Value ? reader["DateSinceLastLossS4"] as DateTime? : null,
                        TotalWinsAsFavourite = reader["TotalWinsAsFavourite"] as int?,
                        TotalWinsAsUnderdog = reader["TotalWinsAsUnderdog"] as int?,
                        TotalLossesAsFavourite = reader["TotalLossesAsFavourite"] as int?,
                        TotalLossesAsUnderdog = reader["TotalLossesAsUnderdog"] as int?,
                        WinsAsFavouriteRatio = reader["WinsAsFavouriteRatio"] != DBNull.Value ? reader["WinsAsFavouriteRatio"] as double? : null,
                        LossesAsFavouriteRatio = reader["LossesAsFavouriteRatio"] != DBNull.Value ? reader["LossesAsFavouriteRatio"] as double? : null,
                        WinsAsUnderdogRatio = reader["WinsAsUnderdogRatio"] != DBNull.Value ? reader["WinsAsUnderdogRatio"] as double? : null,
                        LossesAsUnderdogRatio = reader["LossesAsUnderdogRatio"] != DBNull.Value ? reader["LossesAsUnderdogRatio"] as double? : null,
                        AverageWinningProbabilityAtWonAsFavourite = reader["AverageWinningProbabilityAtWonAsFavourite"] != DBNull.Value ? reader["AverageWinningProbabilityAtWonAsFavourite"] as double? : null,
                        AverageWinningProbabilityAtWonAsUnderdog = reader["AverageWinningProbabilityAtWonAsUnderdog"] != DBNull.Value ? reader["AverageWinningProbabilityAtWonAsUnderdog"] as double? : null,
                        AverageWinningProbabilityAtLossAsFavourite = reader["AverageWinningProbabilityAtLossAsFavourite"] != DBNull.Value ? reader["AverageWinningProbabilityAtLossAsFavourite"] as double? : null,
                        AverageWinningProbabilityAtLossAsUnderdog = reader["AverageWinningProbabilityAtLossAsUnderdog"] != DBNull.Value ? reader["AverageWinningProbabilityAtLossAsUnderdog"] as double? : null,
                        TotalWinsAsFavouriteLastYear = reader["TotalWinsAsFavouriteLastYear"] as int?,
                        TotalWinsAsUnderdogLastYear = reader["TotalWinsAsUnderdogLastYear"] as int?,
                        TotalLossesAsFavouriteLastYear = reader["TotalLossesAsFavouriteLastYear"] as int?,
                        TotalLossesAsUnderdogLastYear = reader["TotalLossesAsUnderdogLastYear"] as int?,
                        WinsAsFavouriteLastYearRatio = reader["WinsAsFavouriteLastYearRatio"] != DBNull.Value ? reader["WinsAsFavouriteLastYearRatio"] as double? : null,
                        LossesAsFavouriteLastYearRatio = reader["LossesAsFavouriteLastYearRatio"] != DBNull.Value ? reader["LossesAsFavouriteLastYearRatio"] as double? : null,
                        WinsAsUnderdogLastYearRatio = reader["WinsAsUnderdogLastYearRatio"] != DBNull.Value ? reader["WinsAsUnderdogLastYearRatio"] as double? : null,
                        LossesAsUnderdogLastYearRatio = reader["LossesAsUnderdogLastYearRatio"] != DBNull.Value ? reader["LossesAsUnderdogLastYearRatio"] as double? : null,
                        AverageWinningProbabilityAtWonAsFavouriteLastYear = reader["AverageWinningProbabilityAtWonAsFavouriteLastYear"] != DBNull.Value ? reader["AverageWinningProbabilityAtWonAsFavouriteLastYear"] as double? : null,
                        AverageWinningProbabilityAtWonAsUnderdogLastYear = reader["AverageWinningProbabilityAtWonAsUnderdogLastYear"] != DBNull.Value ? reader["AverageWinningProbabilityAtWonAsUnderdogLastYear"] as double? : null,
                        AverageWinningProbabilityAtLossAsFavouriteLastYear = reader["AverageWinningProbabilityAtLossAsFavouriteLastYear"] != DBNull.Value ? reader["AverageWinningProbabilityAtLossAsFavouriteLastYear"] as double? : null,
                        AverageWinningProbabilityAtLossAsUnderdogLastYear = reader["AverageWinningProbabilityAtLossAsUnderdogLastYear"] != DBNull.Value ? reader["AverageWinningProbabilityAtLossAsUnderdogLastYear"] as double? : null,
                        TotalWinsAsFavouriteLastMonth = reader["TotalWinsAsFavouriteLastMonth"] as int?,
                        TotalWinsAsUnderdogLastMonth = reader["TotalWinsAsUnderdogLastMonth"] as int?,
                        TotalLossesAsFavouriteLastMonth = reader["TotalLossesAsFavouriteLastMonth"] as int?,
                        TotalLossesAsUnderdogLastMonth = reader["TotalLossesAsUnderdogLastMonth"] as int?,
                        WinsAsFavouriteLastMonthRatio = reader["WinsAsFavouriteLastMonthRatio"] != DBNull.Value ? reader["WinsAsFavouriteLastMonthRatio"] as double? : null,
                        LossesAsFavouriteLastMonthRatio = reader["LossesAsFavouriteLastMonthRatio"] != DBNull.Value ? reader["LossesAsFavouriteLastMonthRatio"] as double? : null,
                        WinsAsUnderdogLastMonthRatio = reader["WinsAsUnderdogLastMonthRatio"] != DBNull.Value ? reader["WinsAsUnderdogLastMonthRatio"] as double? : null,
                        LossesAsUnderdogLastMonthRatio = reader["LossesAsUnderdogLastMonthRatio"] != DBNull.Value ? reader["LossesAsUnderdogLastMonthRatio"] as double? : null,
                        AverageWinningProbabilityAtWonAsFavouriteLastMonth = reader["AverageWinningProbabilityAtWonAsFavouriteLastMonth"] != DBNull.Value ? reader["AverageWinningProbabilityAtWonAsFavouriteLastMonth"] as double? : null,
                        AverageWinningProbabilityAtWonAsUnderdogLastMonth = reader["AverageWinningProbabilityAtWonAsUnderdogLastMonth"] != DBNull.Value ? reader["AverageWinningProbabilityAtWonAsUnderdogLastMonth"] as double? : null,
                        AverageWinningProbabilityAtLossAsFavouriteLastMonth = reader["AverageWinningProbabilityAtLossAsFavouriteLastMonth"] != DBNull.Value ? reader["AverageWinningProbabilityAtLossAsFavouriteLastMonth"] as double? : null,
                        AverageWinningProbabilityAtLossAsUnderdogLastMonth = reader["AverageWinningProbabilityAtLossAsUnderdogLastMonth"] != DBNull.Value ? reader["AverageWinningProbabilityAtLossAsUnderdogLastMonth"] as double? : null,
                        TotalWinsAsFavouriteLastWeek = reader["TotalWinsAsFavouriteLastWeek"] as int?,
                        TotalWinsAsUnderdogLastWeek = reader["TotalWinsAsUnderdogLastWeek"] as int?,
                        TotalLossesAsFavouriteLastWeek = reader["TotalLossesAsFavouriteLastWeek"] as int?,
                        TotalLossesAsUnderdogLastWeek = reader["TotalLossesAsUnderdogLastWeek"] as int?,
                        WinsAsFavouriteLastWeekRatio = reader["WinsAsFavouriteLastWeekRatio"] != DBNull.Value ? reader["WinsAsFavouriteLastWeekRatio"] as double? : null,
                        LossesAsFavouriteLastWeekRatio = reader["LossesAsFavouriteLastWeekRatio"] != DBNull.Value ? reader["LossesAsFavouriteLastWeekRatio"] as double? : null,
                        WinsAsUnderdogLastWeekRatio = reader["WinsAsUnderdogLastWeekRatio"] != DBNull.Value ? reader["WinsAsUnderdogLastWeekRatio"] as double? : null,
                        LossesAsUnderdogLastWeekRatio = reader["LossesAsUnderdogLastWeekRatio"] != DBNull.Value ? reader["LossesAsUnderdogLastWeekRatio"] as double? : null,
                        AverageWinningProbabilityAtWonAsFavouriteLastWeek = reader["AverageWinningProbabilityAtWonAsFavouriteLastWeek"] != DBNull.Value ? reader["AverageWinningProbabilityAtWonAsFavouriteLastWeek"] as double? : null,
                        AverageWinningProbabilityAtWonAsUnderdogLastWeek = reader["AverageWinningProbabilityAtWonAsUnderdogLastWeek"] != DBNull.Value ? reader["AverageWinningProbabilityAtWonAsUnderdogLastWeek"] as double? : null,
                        AverageWinningProbabilityAtLossAsFavouriteLastWeek = reader["AverageWinningProbabilityAtLossAsFavouriteLastWeek"] != DBNull.Value ? reader["AverageWinningProbabilityAtLossAsFavouriteLastWeek"] as double? : null,
                        AverageWinningProbabilityAtLossAsUnderdogLastWeek = reader["AverageWinningProbabilityAtLossAsUnderdogLastWeek"] != DBNull.Value ? reader["AverageWinningProbabilityAtLossAsUnderdogLastWeek"] as double? : null,
                        Streak = reader["Streak"] as int?,
                        StreakS1 = reader["StreakS1"] as int?,
                        StreakS2 = reader["StreakS2"] as int?,
                        StreakS3 = reader["StreakS3"] as int?,
                        StreakS4 = reader["StreakS4"] as int?
                    };
                    Players.Add(Player);
                }
                catch (Exception ex)
                {
                    string bbb;
                    bbb = "";
                }

            }

            return Players;
        }

        public async Task<Player?> GetPlayerByTpIdAsync(int playerTpId)
        {
            using var command = _connection.CreateCommand();
            command.CommandText = "GetPlayerByTPId";
            command.CommandType = CommandType.StoredProcedure;

            var param = command.CreateParameter();
            param.ParameterName = "@PlayerTPId";
            param.Value = playerTpId;
            command.Parameters.Add(param);

            if (_connection.State != ConnectionState.Open) _connection.Open();

            using var reader = await Task.Run(() => command.ExecuteReader());
            if (await Task.Run(() => reader.Read()))
            {
                return new Player
                {
                    PlayerTPId = reader["PlayerTPId"] as int?,
                    PlayerName = reader["PlayerName"] as string,
                    CountryTPId = (int)reader["CountryTPId"],
                    PlayerBirthDate = reader["PlayerBirthDate"] as DateTime?,
                    PlayerHeight = reader["PlayerHeight"] as int?,
                    PlayerWeight = reader["PlayerWeight"] as int?,
                    PlayerTurnedPro = reader["PlayerTurnedPro"] as int?,
                    PlaysId = (int)reader["PlaysId"],
                    TrueSkillMeanM = reader["TrueSkillMeanM"] as double?,
                    TrueSkillStandardDeviationM = reader["TrueSkillStandardDeviationM"] as double?,
                    TrueSkillMeanSM = reader["TrueSkillMeanSM"] as double?,
                    TrueSkillStandardDeviationSM = reader["TrueSkillStandardDeviationSM"] as double?,
                    TrueSkillMeanGSM = reader["TrueSkillMeanGSM"] as double?,
                    TrueSkillStandardDeviationGSM = reader["TrueSkillStandardDeviationGSM"] as double?,
                    TrueSkillMeanMS1 = reader["TrueSkillMeanMS1"] as double?,
                    TrueSkillStandardDeviationMS1 = reader["TrueSkillStandardDeviationMS1"] as double?,
                    TrueSkillMeanSMS1 = reader["TrueSkillMeanSMS1"] as double?,
                    TrueSkillStandardDeviationSMS1 = reader["TrueSkillStandardDeviationSMS1"] as double?,
                    TrueSkillMeanGSMS1 = reader["TrueSkillMeanGSMS1"] as double?,
                    TrueSkillStandardDeviationGSMS1 = reader["TrueSkillStandardDeviationGSMS1"] as double?,
                    TrueSkillMeanMS2 = reader["TrueSkillMeanMS2"] as double?,
                    TrueSkillStandardDeviationMS2 = reader["TrueSkillStandardDeviationMS2"] as double?,
                    TrueSkillMeanSMS2 = reader["TrueSkillMeanSMS2"] as double?,
                    TrueSkillStandardDeviationSMS2 = reader["TrueSkillStandardDeviationSMS2"] as double?,
                    TrueSkillMeanGSMS2 = reader["TrueSkillMeanGSMS2"] as double?,
                    TrueSkillStandardDeviationGSMS2 = reader["TrueSkillStandardDeviationGSMS2"] as double?,
                    TrueSkillMeanMS3 = reader["TrueSkillMeanMS3"] as double?,
                    TrueSkillStandardDeviationMS3 = reader["TrueSkillStandardDeviationMS3"] as double?,
                    TrueSkillMeanSMS3 = reader["TrueSkillMeanSMS3"] as double?,
                    TrueSkillStandardDeviationSMS3 = reader["TrueSkillStandardDeviationSMS3"] as double?,
                    TrueSkillMeanGSMS3 = reader["TrueSkillMeanGSMS3"] as double?,
                    TrueSkillStandardDeviationGSMS3 = reader["TrueSkillStandardDeviationGSMS3"] as double?,
                    TrueSkillMeanMS4 = reader["TrueSkillMeanMS4"] as double?,
                    TrueSkillStandardDeviationMS4 = reader["TrueSkillStandardDeviationMS4"] as double?,
                    TrueSkillMeanSMS4 = reader["TrueSkillMeanSMS4"] as double?,
                    TrueSkillStandardDeviationSMS4 = reader["TrueSkillStandardDeviationSMS4"] as double?,
                    TrueSkillMeanGSMS4 = reader["TrueSkillMeanGSMS4"] as double?,
                    TrueSkillStandardDeviationGSMS4 = reader["TrueSkillStandardDeviationGSMS4"] as double?,
                    WinsTotal = reader["WinsTotal"] as int?,
                    LossesTotal = reader["LossesTotal"] as int?,
                    WinsLastYear = reader["WinsLastYear"] as int?,
                    LossesLastYear = reader["LossesLastYear"] as int?,
                    WinsLastMonth = reader["WinsLastMonth"] as int?,
                    LossesLastMonth = reader["LossesLastMonth"] as int?,
                    WinsLastWeek = reader["WinsLastWeek"] as int?,
                    LossesLastWeek = reader["LossesLastWeek"] as int?,
                    WinsTotalS1 = reader["WinsTotalS1"] as int?,
                    LossesTotalS1 = reader["LossesTotalS1"] as int?,
                    WinsLastYearS1 = reader["WinsLastYearS1"] as int?,
                    LossesLastYearS1 = reader["LossesLastYearS1"] as int?,
                    WinsLastMonthS1 = reader["WinsLastMonthS1"] as int?,
                    LossesLastMonthS1 = reader["LossesLastMonthS1"] as int?,
                    WinsLastWeekS1 = reader["WinsLastWeekS1"] as int?,
                    LossesLastWeekS1 = reader["LossesLastWeekS1"] as int?,
                    WinsTotalS2 = reader["WinsTotalS2"] as int?,
                    LossesTotalS2 = reader["LossesTotalS2"] as int?,
                    WinsLastYearS2 = reader["WinsLastYearS2"] as int?,
                    LossesLastYearS2 = reader["LossesLastYearS2"] as int?,
                    WinsLastMonthS2 = reader["WinsLastMonthS2"] as int?,
                    LossesLastMonthS2 = reader["LossesLastMonthS2"] as int?,
                    WinsLastWeekS2 = reader["WinsLastWeekS2"] as int?,
                    LossesLastWeekS2 = reader["LossesLastWeekS2"] as int?,
                    WinsTotalS3 = reader["WinsTotalS3"] as int?,
                    LossesTotalS3 = reader["LossesTotalS3"] as int?,
                    WinsLastYearS3 = reader["WinsLastYearS3"] as int?,
                    LossesLastYearS3 = reader["LossesLastYearS3"] as int?,
                    WinsLastMonthS3 = reader["WinsLastMonthS3"] as int?,
                    LossesLastMonthS3 = reader["LossesLastMonthS3"] as int?,
                    WinsLastWeekS3 = reader["WinsLastWeekS3"] as int?,
                    LossesLastWeekS3 = reader["LossesLastWeekS3"] as int?,
                    WinsTotalS4 = reader["WinsTotalS4"] as int?,
                    LossesTotalS4 = reader["LossesTotalS4"] as int?,
                    WinsLastYearS4 = reader["WinsLastYearS4"] as int?,
                    LossesLastYearS4 = reader["LossesLastYearS4"] as int?,
                    WinsLastMonthS4 = reader["WinsLastMonthS4"] as int?,
                    LossesLastMonthS4 = reader["LossesLastMonthS4"] as int?,
                    WinsLastWeekS4 = reader["WinsLastWeekS4"] as int?,
                    LossesLastWeekS4 = reader["LossesLastWeekS4"] as int?,
                    WinsSetsTotal = reader["WinsSetsTotal"] as int?,
                    LossesSetsTotal = reader["LossesSetsTotal"] as int?,
                    WinsSetsLastYear = reader["WinsSetsLastYear"] as int?,
                    LossesSetsLastYear = reader["LossesSetsLastYear"] as int?,
                    WinsSetsLastMonth = reader["WinsSetsLastMonth"] as int?,
                    LossesSetsLastMonth = reader["LossesSetsLastMonth"] as int?,
                    WinsSetsLastWeek = reader["WinsSetsLastWeek"] as int?,
                    LossesSetsLastWeek = reader["LossesSetsLastWeek"] as int?,
                    WinsSetsTotalS1 = reader["WinsSetsTotalS1"] as int?,
                    LossesSetsTotalS1 = reader["LossesSetsTotalS1"] as int?,
                    WinsSetsLastYearS1 = reader["WinsSetsLastYearS1"] as int?,
                    LossesSetsLastYearS1 = reader["LossesSetsLastYearS1"] as int?,
                    WinsSetsLastMonthS1 = reader["WinsSetsLastMonthS1"] as int?,
                    LossesSetsLastMonthS1 = reader["LossesSetsLastMonthS1"] as int?,
                    WinsSetsLastWeekS1 = reader["WinsSetsLastWeekS1"] as int?,
                    LossesSetsLastWeekS1 = reader["LossesSetsLastWeekS1"] as int?,
                    WinsSetsTotalS2 = reader["WinsSetsTotalS2"] as int?,
                    LossesSetsTotalS2 = reader["LossesSetsTotalS2"] as int?,
                    WinsSetsLastYearS2 = reader["WinsSetsLastYearS2"] as int?,
                    LossesSetsLastYearS2 = reader["LossesSetsLastYearS2"] as int?,
                    WinsSetsLastMonthS2 = reader["WinsSetsLastMonthS2"] as int?,
                    LossesSetsLastMonthS2 = reader["LossesSetsLastMonthS2"] as int?,
                    WinsSetsLastWeekS2 = reader["WinsSetsLastWeekS2"] as int?,
                    LossesSetsLastWeekS2 = reader["LossesSetsLastWeekS2"] as int?,
                    WinsSetsTotalS3 = reader["WinsSetsTotalS3"] as int?,
                    LossesSetsTotalS3 = reader["LossesSetsTotalS3"] as int?,
                    WinsSetsLastYearS3 = reader["WinsSetsLastYearS3"] as int?,
                    LossesSetsLastYearS3 = reader["LossesSetsLastYearS3"] as int?,
                    WinsSetsLastMonthS3 = reader["WinsSetsLastMonthS3"] as int?,
                    LossesSetsLastMonthS3 = reader["LossesSetsLastMonthS3"] as int?,
                    WinsSetsLastWeekS3 = reader["WinsSetsLastWeekS3"] as int?,
                    LossesSetsLastWeekS3 = reader["LossesSetsLastWeekS3"] as int?,
                    WinsSetsTotalS4 = reader["WinsSetsTotalS4"] as int?,
                    LossesSetsTotalS4 = reader["LossesSetsTotalS4"] as int?,
                    WinsSetsLastYearS4 = reader["WinsSetsLastYearS4"] as int?,
                    LossesSetsLastYearS4 = reader["LossesSetsLastYearS4"] as int?,
                    WinsSetsLastMonthS4 = reader["WinsSetsLastMonthS4"] as int?,
                    LossesSetsLastMonthS4 = reader["LossesSetsLastMonthS4"] as int?,
                    WinsSetsLastWeekS4 = reader["WinsSetsLastWeekS4"] as int?,
                    LossesSetsLastWeekS4 = reader["LossesSetsLastWeekS4"] as int?,
                    WinsGamesTotal = reader["WinsGamesTotal"] as int?,
                    LossesGamesTotal = reader["LossesGamesTotal"] as int?,
                    WinsGamesLastYear = reader["WinsGamesLastYear"] as int?,
                    LossesGamesLastYear = reader["LossesGamesLastYear"] as int?,
                    WinsGamesLastMonth = reader["WinsGamesLastMonth"] as int?,
                    LossesGamesLastMonth = reader["LossesGamesLastMonth"] as int?,
                    WinsGamesLastWeek = reader["WinsGamesLastWeek"] as int?,
                    LossesGamesLastWeek = reader["LossesGamesLastWeek"] as int?,
                    WinsGamesTotalS1 = reader["WinsGamesTotalS1"] as int?,
                    LossesGamesTotalS1 = reader["LossesGamesTotalS1"] as int?,
                    WinsGamesLastYearS1 = reader["WinsGamesLastYearS1"] as int?,
                    LossesGamesLastYearS1 = reader["LossesGamesLastYearS1"] as int?,
                    WinsGamesLastMonthS1 = reader["WinsGamesLastMonthS1"] as int?,
                    LossesGamesLastMonthS1 = reader["LossesGamesLastMonthS1"] as int?,
                    WinsGamesLastWeekS1 = reader["WinsGamesLastWeekS1"] as int?,
                    LossesGamesLastWeekS1 = reader["LossesGamesLastWeekS1"] as int?,
                    WinsGamesTotalS2 = reader["WinsGamesTotalS2"] as int?,
                    LossesGamesTotalS2 = reader["LossesGamesTotalS2"] as int?,
                    WinsGamesLastYearS2 = reader["WinsGamesLastYearS2"] as int?,
                    LossesGamesLastYearS2 = reader["LossesGamesLastYearS2"] as int?,
                    WinsGamesLastMonthS2 = reader["WinsGamesLastMonthS2"] as int?,
                    LossesGamesLastMonthS2 = reader["LossesGamesLastMonthS2"] as int?,
                    WinsGamesLastWeekS2 = reader["WinsGamesLastWeekS2"] as int?,
                    LossesGamesLastWeekS2 = reader["LossesGamesLastWeekS2"] as int?,
                    WinsGamesTotalS3 = reader["WinsGamesTotalS3"] as int?,
                    LossesGamesTotalS3 = reader["LossesGamesTotalS3"] as int?,
                    WinsGamesLastYearS3 = reader["WinsGamesLastYearS3"] as int?,
                    LossesGamesLastYearS3 = reader["LossesGamesLastYearS3"] as int?,
                    WinsGamesLastMonthS3 = reader["WinsGamesLastMonthS3"] as int?,
                    LossesGamesLastMonthS3 = reader["LossesGamesLastMonthS3"] as int?,
                    WinsGamesLastWeekS3 = reader["WinsGamesLastWeekS3"] as int?,
                    LossesGamesLastWeekS3 = reader["LossesGamesLastWeekS3"] as int?,
                    WinsGamesTotalS4 = reader["WinsGamesTotalS4"] as int?,
                    LossesGamesTotalS4 = reader["LossesGamesTotalS4"] as int?,
                    WinsGamesLastYearS4 = reader["WinsGamesLastYearS4"] as int?,
                    LossesGamesLastYearS4 = reader["LossesGamesLastYearS4"] as int?,
                    WinsGamesLastMonthS4 = reader["WinsGamesLastMonthS4"] as int?,
                    LossesGamesLastMonthS4 = reader["LossesGamesLastMonthS4"] as int?,
                    WinsGamesLastWeekS4 = reader["WinsGamesLastWeekS4"] as int?,
                    LossesGamesLastWeekS4 = reader["LossesGamesLastWeekS4"] as int?,
                    DateSinceLastWin = reader["DateSinceLastWin"] as DateTime?,
                    DateSinceLastWinS1 = reader["DateSinceLastWinS1"] as DateTime?,
                    DateSinceLastWinS2 = reader["DateSinceLastWinS2"] as DateTime?,
                    DateSinceLastWinS3 = reader["DateSinceLastWinS3"] as DateTime?,
                    DateSinceLastWinS4 = reader["DateSinceLastWinS4"] as DateTime?,
                    DateSinceLastLoss = reader["DateSinceLastLoss"] as DateTime?,
                    DateSinceLastLossS1 = reader["DateSinceLastLossS1"] as DateTime?,
                    DateSinceLastLossS2 = reader["DateSinceLastLossS2"] as DateTime?,
                    DateSinceLastLossS3 = reader["DateSinceLastLossS3"] as DateTime?,
                    DateSinceLastLossS4 = reader["DateSinceLastLossS4"] as DateTime?,
                    TotalWinsAsFavourite = reader["TotalWinsAsFavourite"] as int?,
                    TotalWinsAsUnderdog = reader["TotalWinsAsUnderdog"] as int?,
                    TotalLossesAsFavourite = reader["TotalLossesAsFavourite"] as int?,
                    TotalLossesAsUnderdog = reader["TotalLossesAsUnderdog"] as int?,
                    WinsAsFavouriteRatio = reader["WinsAsFavouriteRatio"] as double?,
                    LossesAsFavouriteRatio = reader["LossesAsFavouriteRatio"] as double?,
                    WinsAsUnderdogRatio = reader["WinsAsUnderdogRatio"] as double?,
                    LossesAsUnderdogRatio = reader["LossesAsUnderdogRatio"] as double?,
                    AverageWinningProbabilityAtWonAsFavourite = reader["AverageWinningProbabilityAtWonAsFavourite"] as double?,
                    AverageWinningProbabilityAtWonAsUnderdog = reader["AverageWinningProbabilityAtWonAsUnderdog"] as double?,
                    AverageWinningProbabilityAtLossAsFavourite = reader["AverageWinningProbabilityAtLossAsFavourite"] as double?,
                    AverageWinningProbabilityAtLossAsUnderdog = reader["AverageWinningProbabilityAtLossAsUnderdog"] as double?,
                    TotalWinsAsFavouriteLastYear = reader["TotalWinsAsFavouriteLastYear"] as int?,
                    TotalWinsAsUnderdogLastYear = reader["TotalWinsAsUnderdogLastYear"] as int?,
                    TotalLossesAsFavouriteLastYear = reader["TotalLossesAsFavouriteLastYear"] as int?,
                    TotalLossesAsUnderdogLastYear = reader["TotalLossesAsUnderdogLastYear"] as int?,
                    WinsAsFavouriteLastYearRatio = reader["WinsAsFavouriteLastYearRatio"] as double?,
                    LossesAsFavouriteLastYearRatio = reader["LossesAsFavouriteLastYearRatio"] as double?,
                    WinsAsUnderdogLastYearRatio = reader["WinsAsUnderdogLastYearRatio"] as double?,
                    LossesAsUnderdogLastYearRatio = reader["LossesAsUnderdogLastYearRatio"] as double?,
                    AverageWinningProbabilityAtWonAsFavouriteLastYear = reader["AverageWinningProbabilityAtWonAsFavouriteLastYear"] as double?,
                    AverageWinningProbabilityAtWonAsUnderdogLastYear = reader["AverageWinningProbabilityAtWonAsUnderdogLastYear"] as double?,
                    AverageWinningProbabilityAtLossAsFavouriteLastYear = reader["AverageWinningProbabilityAtLossAsFavouriteLastYear"] as double?,
                    AverageWinningProbabilityAtLossAsUnderdogLastYear = reader["AverageWinningProbabilityAtLossAsUnderdogLastYear"] as double?,
                    TotalWinsAsFavouriteLastMonth = reader["TotalWinsAsFavouriteLastMonth"] as int?,
                    TotalWinsAsUnderdogLastMonth = reader["TotalWinsAsUnderdogLastMonth"] as int?,
                    TotalLossesAsFavouriteLastMonth = reader["TotalLossesAsFavouriteLastMonth"] as int?,
                    TotalLossesAsUnderdogLastMonth = reader["TotalLossesAsUnderdogLastMonth"] as int?,
                    WinsAsFavouriteLastMonthRatio = reader["WinsAsFavouriteLastMonthRatio"] as double?,
                    LossesAsFavouriteLastMonthRatio = reader["LossesAsFavouriteLastMonthRatio"] as double?,
                    WinsAsUnderdogLastMonthRatio = reader["WinsAsUnderdogLastMonthRatio"] as double?,
                    LossesAsUnderdogLastMonthRatio = reader["LossesAsUnderdogLastMonthRatio"] as double?,
                    AverageWinningProbabilityAtWonAsFavouriteLastMonth = reader["AverageWinningProbabilityAtWonAsFavouriteLastMonth"] as double?,
                    AverageWinningProbabilityAtWonAsUnderdogLastMonth = reader["AverageWinningProbabilityAtWonAsUnderdogLastMonth"] as double?,
                    AverageWinningProbabilityAtLossAsFavouriteLastMonth = reader["AverageWinningProbabilityAtLossAsFavouriteLastMonth"] as double?,
                    AverageWinningProbabilityAtLossAsUnderdogLastMonth = reader["AverageWinningProbabilityAtLossAsUnderdogLastMonth"] as double?,
                    TotalWinsAsFavouriteLastWeek = reader["TotalWinsAsFavouriteLastWeek"] as int?,
                    TotalWinsAsUnderdogLastWeek = reader["TotalWinsAsUnderdogLastWeek"] as int?,
                    TotalLossesAsFavouriteLastWeek = reader["TotalLossesAsFavouriteLastWeek"] as int?,
                    TotalLossesAsUnderdogLastWeek = reader["TotalLossesAsUnderdogLastWeek"] as int?,
                    WinsAsFavouriteLastWeekRatio = reader["WinsAsFavouriteLastWeekRatio"] as double?,
                    LossesAsFavouriteLastWeekRatio = reader["LossesAsFavouriteLastWeekRatio"] as double?,
                    WinsAsUnderdogLastWeekRatio = reader["WinsAsUnderdogLastWeekRatio"] as double?,
                    LossesAsUnderdogLastWeekRatio = reader["LossesAsUnderdogLastWeekRatio"] as double?,
                    AverageWinningProbabilityAtWonAsFavouriteLastWeek = reader["AverageWinningProbabilityAtWonAsFavouriteLastWeek"] as double?,
                    AverageWinningProbabilityAtWonAsUnderdogLastWeek = reader["AverageWinningProbabilityAtWonAsUnderdogLastWeek"] as double?,
                    AverageWinningProbabilityAtLossAsFavouriteLastWeek = reader["AverageWinningProbabilityAtLossAsFavouriteLastWeek"] as double?,
                    AverageWinningProbabilityAtLossAsUnderdogLastWeek = reader["AverageWinningProbabilityAtLossAsUnderdogLastWeek"] as double?,
                    Streak = reader["Streak"] as int?,
                    StreakS1 = reader["StreakS1"] as int?,
                    StreakS2 = reader["StreakS2"] as int?,
                    StreakS3 = reader["StreakS3"] as int?,
                    StreakS4 = reader["StreakS4"] as int?
                };
            }

            return null;
        }

        public async Task InsertPlayerAsync(Player player)
        {
            try
            {
                using var command = _connection.CreateCommand();
                command.CommandText = "InsertPlayer";
                command.CommandType = CommandType.StoredProcedure;

                var parameters = new (string, object?)[]
                {
                ("@PlayerTPId"                                         ,player.PlayerTPId),
                ("@PlayerName"                                         ,player.PlayerName),
                ("@CountryTPId"                                        ,player.CountryTPId),
                ("@PlayerBirthDate"                                    ,player.PlayerBirthDate),
                ("@PlayerHeight"                                       ,player.PlayerHeight),
                ("@PlayerWeight"                                       ,player.PlayerWeight),
                ("@PlayerTurnedPro"                                    ,player.PlayerTurnedPro),
                ("@PlaysId"                                            ,player.PlaysId),
                ("@TrueSkillMeanM"                                     ,_trueSkillSettings.InitialMean),
                ("@TrueSkillStandardDeviationM"                        ,_trueSkillSettings.InitialStandardDeviation),
                ("@TrueSkillMeanSM"                                    ,_trueSkillSettings.InitialMean),
                ("@TrueSkillStandardDeviationSM"                       ,_trueSkillSettings.InitialStandardDeviation),
                ("@TrueSkillMeanGSM"                                   ,_trueSkillSettings.InitialMean),
                ("@TrueSkillStandardDeviationGSM"                      ,_trueSkillSettings.InitialStandardDeviation),
                ("@TrueSkillMeanMS1"                                   ,_trueSkillSettings.InitialMean),
                ("@TrueSkillStandardDeviationMS1"                      ,_trueSkillSettings.InitialStandardDeviation),
                ("@TrueSkillMeanSMS1"                                  ,_trueSkillSettings.InitialMean),
                ("@TrueSkillStandardDeviationSMS1"                     ,_trueSkillSettings.InitialStandardDeviation),
                ("@TrueSkillMeanGSMS1"                                 ,_trueSkillSettings.InitialMean),
                ("@TrueSkillStandardDeviationGSMS1"                    ,_trueSkillSettings.InitialStandardDeviation),
                ("@TrueSkillMeanMS2"                                   ,_trueSkillSettings.InitialMean),
                ("@TrueSkillStandardDeviationMS2"                      ,_trueSkillSettings.InitialStandardDeviation),
                ("@TrueSkillMeanSMS2"                                  ,_trueSkillSettings.InitialMean),
                ("@TrueSkillStandardDeviationSMS2"                     ,_trueSkillSettings.InitialStandardDeviation),
                ("@TrueSkillMeanGSMS2"                                 ,_trueSkillSettings.InitialMean),
                ("@TrueSkillStandardDeviationGSMS2"                    ,_trueSkillSettings.InitialStandardDeviation),
                ("@TrueSkillMeanMS3"                                   ,_trueSkillSettings.InitialMean),
                ("@TrueSkillStandardDeviationMS3"                      ,_trueSkillSettings.InitialStandardDeviation),
                ("@TrueSkillMeanSMS3"                                  ,_trueSkillSettings.InitialMean),
                ("@TrueSkillStandardDeviationSMS3"                     ,_trueSkillSettings.InitialStandardDeviation),
                ("@TrueSkillMeanGSMS3"                                 ,_trueSkillSettings.InitialMean),
                ("@TrueSkillStandardDeviationGSMS3"                    ,_trueSkillSettings.InitialStandardDeviation),
                ("@TrueSkillMeanMS4"                                   ,_trueSkillSettings.InitialMean),
                ("@TrueSkillStandardDeviationMS4"                      ,_trueSkillSettings.InitialStandardDeviation),
                ("@TrueSkillMeanSMS4"                                  ,_trueSkillSettings.InitialMean),
                ("@TrueSkillStandardDeviationSMS4"                     ,_trueSkillSettings.InitialStandardDeviation),
                ("@TrueSkillMeanGSMS4"                                 ,_trueSkillSettings.InitialMean),
                ("@TrueSkillStandardDeviationGSMS4"                    ,_trueSkillSettings.InitialStandardDeviation),
                ("@WinsTotal"                                          ,0),
                ("@LossesTotal"                                        ,0),
                ("@WinsLastYear"                                       ,0),
                ("@LossesLastYear"                                     ,0),
                ("@WinsLastMonth"                                      ,0),
                ("@LossesLastMonth"                                    ,0),
                ("@WinsLastWeek"                                       ,0),
                ("@LossesLastWeek"                                     ,0),
                ("@WinsTotalS1"                                        ,0),
                ("@LossesTotalS1"                                      ,0),
                ("@WinsLastYearS1"                                     ,0),
                ("@LossesLastYearS1"                                   ,0),
                ("@WinsLastMonthS1"                                    ,0),
                ("@LossesLastMonthS1"                                  ,0),
                ("@WinsLastWeekS1"                                     ,0),
                ("@LossesLastWeekS1"                                   ,0),
                ("@WinsTotalS2"                                        ,0),
                ("@LossesTotalS2"                                      ,0),
                ("@WinsLastYearS2"                                     ,0),
                ("@LossesLastYearS2"                                   ,0),
                ("@WinsLastMonthS2"                                    ,0),
                ("@LossesLastMonthS2"                                  ,0),
                ("@WinsLastWeekS2"                                     ,0),
                ("@LossesLastWeekS2"                                   ,0),
                ("@WinsTotalS3"                                        ,0),
                ("@LossesTotalS3"                                      ,0),
                ("@WinsLastYearS3"                                     ,0),
                ("@LossesLastYearS3"                                   ,0),
                ("@WinsLastMonthS3"                                    ,0),
                ("@LossesLastMonthS3"                                  ,0),
                ("@WinsLastWeekS3"                                     ,0),
                ("@LossesLastWeekS3"                                   ,0),
                ("@WinsTotalS4"                                        ,0),
                ("@LossesTotalS4"                                      ,0),
                ("@WinsLastYearS4"                                     ,0),
                ("@LossesLastYearS4"                                   ,0),
                ("@WinsLastMonthS4"                                    ,0),
                ("@LossesLastMonthS4"                                  ,0),
                ("@WinsLastWeekS4"                                     ,0),
                ("@LossesLastWeekS4"                                   ,0),
                ("@WinsSetsTotal"                                      ,0),
                ("@LossesSetsTotal"                                    ,0),
                ("@WinsSetsLastYear"                                   ,0),
                ("@LossesSetsLastYear"                                 ,0),
                ("@WinsSetsLastMonth"                                  ,0),
                ("@LossesSetsLastMonth"                                ,0),
                ("@WinsSetsLastWeek"                                   ,0),
                ("@LossesSetsLastWeek"                                 ,0),
                ("@WinsSetsTotalS1"                                    ,0),
                ("@LossesSetsTotalS1"                                  ,0),
                ("@WinsSetsLastYearS1"                                 ,0),
                ("@LossesSetsLastYearS1"                               ,0),
                ("@WinsSetsLastMonthS1"                                ,0),
                ("@LossesSetsLastMonthS1"                              ,0),
                ("@WinsSetsLastWeekS1"                                 ,0),
                ("@LossesSetsLastWeekS1"                               ,0),
                ("@WinsSetsTotalS2"                                    ,0),
                ("@LossesSetsTotalS2"                                  ,0),
                ("@WinsSetsLastYearS2"                                 ,0),
                ("@LossesSetsLastYearS2"                               ,0),
                ("@WinsSetsLastMonthS2"                                ,0),
                ("@LossesSetsLastMonthS2"                              ,0),
                ("@WinsSetsLastWeekS2"                                 ,0),
                ("@LossesSetsLastWeekS2"                               ,0),
                ("@WinsSetsTotalS3"                                    ,0),
                ("@LossesSetsTotalS3"                                  ,0),
                ("@WinsSetsLastYearS3"                                 ,0),
                ("@LossesSetsLastYearS3"                               ,0),
                ("@WinsSetsLastMonthS3"                                ,0),
                ("@LossesSetsLastMonthS3"                              ,0),
                ("@WinsSetsLastWeekS3"                                 ,0),
                ("@LossesSetsLastWeekS3"                               ,0),
                ("@WinsSetsTotalS4"                                    ,0),
                ("@LossesSetsTotalS4"                                  ,0),
                ("@WinsSetsLastYearS4"                                 ,0),
                ("@LossesSetsLastYearS4"                               ,0),
                ("@WinsSetsLastMonthS4"                                ,0),
                ("@LossesSetsLastMonthS4"                              ,0),
                ("@WinsSetsLastWeekS4"                                 ,0),
                ("@LossesSetsLastWeekS4"                               ,0),
                ("@WinsGamesTotal"                                     ,0),
                ("@LossesGamesTotal"                                   ,0),
                ("@WinsGamesLastYear"                                  ,0),
                ("@LossesGamesLastYear"                                ,0),
                ("@WinsGamesLastMonth"                                 ,0),
                ("@LossesGamesLastMonth"                               ,0),
                ("@WinsGamesLastWeek"                                  ,0),
                ("@LossesGamesLastWeek"                                ,0),
                ("@WinsGamesTotalS1"                                   ,0),
                ("@LossesGamesTotalS1"                                 ,0),
                ("@WinsGamesLastYearS1"                                ,0),
                ("@LossesGamesLastYearS1"                              ,0),
                ("@WinsGamesLastMonthS1"                               ,0),
                ("@LossesGamesLastMonthS1"                             ,0),
                ("@WinsGamesLastWeekS1"                                ,0),
                ("@LossesGamesLastWeekS1"                              ,0),
                ("@WinsGamesTotalS2"                                   ,0),
                ("@LossesGamesTotalS2"                                 ,0),
                ("@WinsGamesLastYearS2"                                ,0),
                ("@LossesGamesLastYearS2"                              ,0),
                ("@WinsGamesLastMonthS2"                               ,0),
                ("@LossesGamesLastMonthS2"                             ,0),
                ("@WinsGamesLastWeekS2"                                ,0),
                ("@LossesGamesLastWeekS2"                              ,0),
                ("@WinsGamesTotalS3"                                   ,0),
                ("@LossesGamesTotalS3"                                 ,0),
                ("@WinsGamesLastYearS3"                                ,0),
                ("@LossesGamesLastYearS3"                              ,0),
                ("@WinsGamesLastMonthS3"                               ,0),
                ("@LossesGamesLastMonthS3"                             ,0),
                ("@WinsGamesLastWeekS3"                                ,0),
                ("@LossesGamesLastWeekS3"                              ,0),
                ("@WinsGamesTotalS4"                                   ,0),
                ("@LossesGamesTotalS4"                                 ,0),
                ("@WinsGamesLastYearS4"                                ,0),
                ("@LossesGamesLastYearS4"                              ,0),
                ("@WinsGamesLastMonthS4"                               ,0),
                ("@LossesGamesLastMonthS4"                             ,0),
                ("@WinsGamesLastWeekS4"                                ,0),
                ("@LossesGamesLastWeekS4"                              ,0),
                ("@DateSinceLastWin"                                   ,null),
                ("@DateSinceLastWinS1"                                 ,null),
                ("@DateSinceLastWinS2"                                 ,null),
                ("@DateSinceLastWinS3"                                 ,null),
                ("@DateSinceLastWinS4"                                 ,null),
                ("@DateSinceLastLoss"                                  ,null),
                ("@DateSinceLastLossS1"                                ,null),
                ("@DateSinceLastLossS2"                                ,null),
                ("@DateSinceLastLossS3"                                ,null),
                ("@DateSinceLastLossS4"                                ,null),
                ("@TotalWinsAsFavourite"                               ,0),
                ("@TotalWinsAsUnderdog"                                ,0),
                ("@TotalLossesAsFavourite"                             ,0),
                ("@TotalLossesAsUnderdog"                              ,0),
                ("@WinsAsFavouriteRatio"                               ,null),
                ("@LossesAsFavouriteRatio"                             ,null),
                ("@WinsAsUnderdogRatio"                                ,null),
                ("@LossesAsUnderdogRatio"                              ,null),
                ("@AverageWinningProbabilityAtWonAsFavourite"          ,null),
                ("@AverageWinningProbabilityAtWonAsUnderdog"           ,null),
                ("@AverageWinningProbabilityAtLossAsFavourite"         ,null),
                ("@AverageWinningProbabilityAtLossAsUnderdog"          ,null),
                ("@TotalWinsAsFavouriteLastYear"                       ,0),
                ("@TotalWinsAsUnderdogLastYear"                        ,0),
                ("@TotalLossesAsFavouriteLastYear"                     ,0),
                ("@TotalLossesAsUnderdogLastYear"                      ,0),
                ("@WinsAsFavouriteLastYearRatio"                       ,null),
                ("@LossesAsFavouriteLastYearRatio"                     ,null),
                ("@WinsAsUnderdogLastYearRatio"                        ,null),
                ("@LossesAsUnderdogLastYearRatio"                      ,null),
                ("@AverageWinningProbabilityAtWonAsFavouriteLastYear"  ,null),
                ("@AverageWinningProbabilityAtWonAsUnderdogLastYear"   ,null),
                ("@AverageWinningProbabilityAtLossAsFavouriteLastYear" ,null),
                ("@AverageWinningProbabilityAtLossAsUnderdogLastYear"  ,null),
                ("@TotalWinsAsFavouriteLastMonth"                      ,0),
                ("@TotalWinsAsUnderdogLastMonth"                       ,0),
                ("@TotalLossesAsFavouriteLastMonth"                    ,0),
                ("@TotalLossesAsUnderdogLastMonth"                     ,0),
                ("@WinsAsFavouriteLastMonthRatio"                      ,null),
                ("@LossesAsFavouriteLastMonthRatio"                    ,null),
                ("@WinsAsUnderdogLastMonthRatio"                       ,null),
                ("@LossesAsUnderdogLastMonthRatio"                     ,null),
                ("@AverageWinningProbabilityAtWonAsFavouriteLastMonth" ,null),
                ("@AverageWinningProbabilityAtWonAsUnderdogLastMonth"  ,null),
                ("@AverageWinningProbabilityAtLossAsFavouriteLastMonth",null),
                ("@AverageWinningProbabilityAtLossAsUnderdogLastMonth" ,null),
                ("@TotalWinsAsFavouriteLastWeek"                       ,0),
                ("@TotalWinsAsUnderdogLastWeek"                        ,0),
                ("@TotalLossesAsFavouriteLastWeek"                     ,0),
                ("@TotalLossesAsUnderdogLastWeek"                      ,0),
                ("@WinsAsFavouriteLastWeekRatio"                       ,null),
                ("@LossesAsFavouriteLastWeekRatio"                     ,null),
                ("@WinsAsUnderdogLastWeekRatio"                        ,null),
                ("@LossesAsUnderdogLastWeekRatio"                      ,null),
                ("@AverageWinningProbabilityAtWonAsFavouriteLastWeek"  ,null),
                ("@AverageWinningProbabilityAtWonAsUnderdogLastWeek"   ,null),
                ("@AverageWinningProbabilityAtLossAsFavouriteLastWeek" ,null),
                ("@AverageWinningProbabilityAtLossAsUnderdogLastWeek"  ,null),
                ("@Streak"                                             ,0),
                ("@StreakS1"                                           ,0),
                ("@StreakS2"                                           ,0),
                ("@StreakS3"                                           ,0),
                ("@StreakS4"                                           ,0)
                };

                foreach (var (name, value) in parameters)
                {
                    var p = command.CreateParameter();
                    p.ParameterName = name;
                    p.Value = value ?? DBNull.Value;
                    command.Parameters.Add(p);
                }

                if (_connection.State != ConnectionState.Open) _connection.Open();
                await Task.Run(() => command.ExecuteNonQuery());
            }
            catch (Exception ex)
            {
                string aaa;
                aaa = "";
            }
        }

        public async Task UpdatePlayerAsync(Player player, Models.Match match)
        {
            try
            {
                using var command = _connection.CreateCommand();
                command.CommandText = "UpdatePlayer";
                command.CommandType = CommandType.StoredProcedure;

                var parameters = new (string, object?)[]
                {
                ("@PlayerTPId"                                         ,player.PlayerTPId                                         ),
                ("@PlayerName"                                         ,player.PlayerName                                         ),
                ("@CountryTPId"                                        ,player.CountryTPId                                        ),
                ("@PlayerBirthDate"                                    ,player.PlayerBirthDate                                    ),
                ("@PlayerHeight"                                       ,player.PlayerHeight                                       ),
                ("@PlayerWeight"                                       ,player.PlayerWeight                                       ),
                ("@PlayerTurnedPro"                                    ,player.PlayerTurnedPro                                    ),
                ("@PlaysId"                                            ,player.PlaysId                                            ),
                ("@TrueSkillMeanM"                                     ,player.TrueSkillMeanM                                     ),
                ("@TrueSkillStandardDeviationM"                        ,player.TrueSkillStandardDeviationM                        ),
                ("@TrueSkillMeanSM"                                    ,player.TrueSkillMeanSM                                    ),
                ("@TrueSkillStandardDeviationSM"                       ,player.TrueSkillStandardDeviationSM                       ),
                ("@TrueSkillMeanGSM"                                   ,player.TrueSkillMeanGSM                                   ),
                ("@TrueSkillStandardDeviationGSM"                      ,player.TrueSkillStandardDeviationGSM                      ),
                ("@TrueSkillMeanMS1"                                   ,player.TrueSkillMeanMS1                                   ),
                ("@TrueSkillStandardDeviationMS1"                      ,player.TrueSkillStandardDeviationMS1                      ),
                ("@TrueSkillMeanSMS1"                                  ,player.TrueSkillMeanSMS1                                  ),
                ("@TrueSkillStandardDeviationSMS1"                     ,player.TrueSkillStandardDeviationSMS1                     ),
                ("@TrueSkillMeanGSMS1"                                 ,player.TrueSkillMeanGSMS1                                 ),
                ("@TrueSkillStandardDeviationGSMS1"                    ,player.TrueSkillStandardDeviationGSMS1                    ),
                ("@TrueSkillMeanMS2"                                   ,player.TrueSkillMeanMS2                                   ),
                ("@TrueSkillStandardDeviationMS2"                      ,player.TrueSkillStandardDeviationMS2                      ),
                ("@TrueSkillMeanSMS2"                                  ,player.TrueSkillMeanSMS2                                  ),
                ("@TrueSkillStandardDeviationSMS2"                     ,player.TrueSkillStandardDeviationSMS2                     ),
                ("@TrueSkillMeanGSMS2"                                 ,player.TrueSkillMeanGSMS2                                 ),
                ("@TrueSkillStandardDeviationGSMS2"                    ,player.TrueSkillStandardDeviationGSMS2                    ),
                ("@TrueSkillMeanMS3"                                   ,player.TrueSkillMeanMS3                                   ),
                ("@TrueSkillStandardDeviationMS3"                      ,player.TrueSkillStandardDeviationMS3                      ),
                ("@TrueSkillMeanSMS3"                                  ,player.TrueSkillMeanSMS3                                  ),
                ("@TrueSkillStandardDeviationSMS3"                     ,player.TrueSkillStandardDeviationSMS3                     ),
                ("@TrueSkillMeanGSMS3"                                 ,player.TrueSkillMeanGSMS3                                 ),
                ("@TrueSkillStandardDeviationGSMS3"                    ,player.TrueSkillStandardDeviationGSMS3                    ),
                ("@TrueSkillMeanMS4"                                   ,player.TrueSkillMeanMS4                                   ),
                ("@TrueSkillStandardDeviationMS4"                      ,player.TrueSkillStandardDeviationMS4                      ),
                ("@TrueSkillMeanSMS4"                                  ,player.TrueSkillMeanSMS4                                  ),
                ("@TrueSkillStandardDeviationSMS4"                     ,player.TrueSkillStandardDeviationSMS4                     ),
                ("@TrueSkillMeanGSMS4"                                 ,player.TrueSkillMeanGSMS4                                 ),
                ("@TrueSkillStandardDeviationGSMS4"                    ,player.TrueSkillStandardDeviationGSMS4                    ),
                ("@WinsTotal"                                          ,player.WinsTotal                                          ),
                ("@LossesTotal"                                        ,player.LossesTotal                                        ),
                ("@WinsLastYear"                                       ,player.WinsLastYear                                       ),
                ("@LossesLastYear"                                     ,player.LossesLastYear                                     ),
                ("@WinsLastMonth"                                      ,player.WinsLastMonth                                      ),
                ("@LossesLastMonth"                                    ,player.LossesLastMonth                                    ),
                ("@WinsLastWeek"                                       ,player.WinsLastWeek                                       ),
                ("@LossesLastWeek"                                     ,player.LossesLastWeek                                     ),
                ("@WinsTotalS1"                                        ,player.WinsTotalS1                                        ),
                ("@LossesTotalS1"                                      ,player.LossesTotalS1                                      ),
                ("@WinsLastYearS1"                                     ,player.WinsLastYearS1                                     ),
                ("@LossesLastYearS1"                                   ,player.LossesLastYearS1                                   ),
                ("@WinsLastMonthS1"                                    ,player.WinsLastMonthS1                                    ),
                ("@LossesLastMonthS1"                                  ,player.LossesLastMonthS1                                  ),
                ("@WinsLastWeekS1"                                     ,player.WinsLastWeekS1                                     ),
                ("@LossesLastWeekS1"                                   ,player.LossesLastWeekS1                                   ),
                ("@WinsTotalS2"                                        ,player.WinsTotalS2                                        ),
                ("@LossesTotalS2"                                      ,player.LossesTotalS2                                      ),
                ("@WinsLastYearS2"                                     ,player.WinsLastYearS2                                     ),
                ("@LossesLastYearS2"                                   ,player.LossesLastYearS2                                   ),
                ("@WinsLastMonthS2"                                    ,player.WinsLastMonthS2                                    ),
                ("@LossesLastMonthS2"                                  ,player.LossesLastMonthS2                                  ),
                ("@WinsLastWeekS2"                                     ,player.WinsLastWeekS2                                     ),
                ("@LossesLastWeekS2"                                   ,player.LossesLastWeekS2                                   ),
                ("@WinsTotalS3"                                        ,player.WinsTotalS3                                        ),
                ("@LossesTotalS3"                                      ,player.LossesTotalS3                                      ),
                ("@WinsLastYearS3"                                     ,player.WinsLastYearS3                                     ),
                ("@LossesLastYearS3"                                   ,player.LossesLastYearS3                                   ),
                ("@WinsLastMonthS3"                                    ,player.WinsLastMonthS3                                    ),
                ("@LossesLastMonthS3"                                  ,player.LossesLastMonthS3                                  ),
                ("@WinsLastWeekS3"                                     ,player.WinsLastWeekS3                                     ),
                ("@LossesLastWeekS3"                                   ,player.LossesLastWeekS3                                   ),
                ("@WinsTotalS4"                                        ,player.WinsTotalS4                                        ),
                ("@LossesTotalS4"                                      ,player.LossesTotalS4                                      ),
                ("@WinsLastYearS4"                                     ,player.WinsLastYearS4                                     ),
                ("@LossesLastYearS4"                                   ,player.LossesLastYearS4                                   ),
                ("@WinsLastMonthS4"                                    ,player.WinsLastMonthS4                                    ),
                ("@LossesLastMonthS4"                                  ,player.LossesLastMonthS4                                  ),
                ("@WinsLastWeekS4"                                     ,player.WinsLastWeekS4                                     ),
                ("@LossesLastWeekS4"                                   ,player.LossesLastWeekS4                                   ),
                ("@WinsSetsTotal"                                      ,player.WinsSetsTotal                                      ),
                ("@LossesSetsTotal"                                    ,player.LossesSetsTotal                                    ),
                ("@WinsSetsLastYear"                                   ,player.WinsSetsLastYear                                   ),
                ("@LossesSetsLastYear"                                 ,player.LossesSetsLastYear                                 ),
                ("@WinsSetsLastMonth"                                  ,player.WinsSetsLastMonth                                  ),
                ("@LossesSetsLastMonth"                                ,player.LossesSetsLastMonth                                ),
                ("@WinsSetsLastWeek"                                   ,player.WinsSetsLastWeek                                   ),
                ("@LossesSetsLastWeek"                                 ,player.LossesSetsLastWeek                                 ),
                ("@WinsSetsTotalS1"                                    ,player.WinsSetsTotalS1                                    ),
                ("@LossesSetsTotalS1"                                  ,player.LossesSetsTotalS1                                  ),
                ("@WinsSetsLastYearS1"                                 ,player.WinsSetsLastYearS1                                 ),
                ("@LossesSetsLastYearS1"                               ,player.LossesSetsLastYearS1                               ),
                ("@WinsSetsLastMonthS1"                                ,player.WinsSetsLastMonthS1                                ),
                ("@LossesSetsLastMonthS1"                              ,player.LossesSetsLastMonthS1                              ),
                ("@WinsSetsLastWeekS1"                                 ,player.WinsSetsLastWeekS1                                 ),
                ("@LossesSetsLastWeekS1"                               ,player.LossesSetsLastWeekS1                               ),
                ("@WinsSetsTotalS2"                                    ,player.WinsSetsTotalS2                                    ),
                ("@LossesSetsTotalS2"                                  ,player.LossesSetsTotalS2                                  ),
                ("@WinsSetsLastYearS2"                                 ,player.WinsSetsLastYearS2                                 ),
                ("@LossesSetsLastYearS2"                               ,player.LossesSetsLastYearS2                               ),
                ("@WinsSetsLastMonthS2"                                ,player.WinsSetsLastMonthS2                                ),
                ("@LossesSetsLastMonthS2"                              ,player.LossesSetsLastMonthS2                              ),
                ("@WinsSetsLastWeekS2"                                 ,player.WinsSetsLastWeekS2                                 ),
                ("@LossesSetsLastWeekS2"                               ,player.LossesSetsLastWeekS2                               ),
                ("@WinsSetsTotalS3"                                    ,player.WinsSetsTotalS3                                    ),
                ("@LossesSetsTotalS3"                                  ,player.LossesSetsTotalS3                                  ),
                ("@WinsSetsLastYearS3"                                 ,player.WinsSetsLastYearS3                                 ),
                ("@LossesSetsLastYearS3"                               ,player.LossesSetsLastYearS3                               ),
                ("@WinsSetsLastMonthS3"                                ,player.WinsSetsLastMonthS3                                ),
                ("@LossesSetsLastMonthS3"                              ,player.LossesSetsLastMonthS3                              ),
                ("@WinsSetsLastWeekS3"                                 ,player.WinsSetsLastWeekS3                                 ),
                ("@LossesSetsLastWeekS3"                               ,player.LossesSetsLastWeekS3                               ),
                ("@WinsSetsTotalS4"                                    ,player.WinsSetsTotalS4                                    ),
                ("@LossesSetsTotalS4"                                  ,player.LossesSetsTotalS4                                  ),
                ("@WinsSetsLastYearS4"                                 ,player.WinsSetsLastYearS4                                 ),
                ("@LossesSetsLastYearS4"                               ,player.LossesSetsLastYearS4                               ),
                ("@WinsSetsLastMonthS4"                                ,player.WinsSetsLastMonthS4                                ),
                ("@LossesSetsLastMonthS4"                              ,player.LossesSetsLastMonthS4                              ),
                ("@WinsSetsLastWeekS4"                                 ,player.WinsSetsLastWeekS4                                 ),
                ("@LossesSetsLastWeekS4"                               ,player.LossesSetsLastWeekS4                               ),
                ("@WinsGamesTotal"                                     ,player.WinsGamesTotal                                     ),
                ("@LossesGamesTotal"                                   ,player.LossesGamesTotal                                   ),
                ("@WinsGamesLastYear"                                  ,player.WinsGamesLastYear                                  ),
                ("@LossesGamesLastYear"                                ,player.LossesGamesLastYear                                ),
                ("@WinsGamesLastMonth"                                 ,player.WinsGamesLastMonth                                 ),
                ("@LossesGamesLastMonth"                               ,player.LossesGamesLastMonth                               ),
                ("@WinsGamesLastWeek"                                  ,player.WinsGamesLastWeek                                  ),
                ("@LossesGamesLastWeek"                                ,player.LossesGamesLastWeek                                ),
                ("@WinsGamesTotalS1"                                   ,player.WinsGamesTotalS1                                   ),
                ("@LossesGamesTotalS1"                                 ,player.LossesGamesTotalS1                                 ),
                ("@WinsGamesLastYearS1"                                ,player.WinsGamesLastYearS1                                ),
                ("@LossesGamesLastYearS1"                              ,player.LossesGamesLastYearS1                              ),
                ("@WinsGamesLastMonthS1"                               ,player.WinsGamesLastMonthS1                               ),
                ("@LossesGamesLastMonthS1"                             ,player.LossesGamesLastMonthS1                             ),
                ("@WinsGamesLastWeekS1"                                ,player.WinsGamesLastWeekS1                                ),
                ("@LossesGamesLastWeekS1"                              ,player.LossesGamesLastWeekS1                              ),
                ("@WinsGamesTotalS2"                                   ,player.WinsGamesTotalS2                                   ),
                ("@LossesGamesTotalS2"                                 ,player.LossesGamesTotalS2                                 ),
                ("@WinsGamesLastYearS2"                                ,player.WinsGamesLastYearS2                                ),
                ("@LossesGamesLastYearS2"                              ,player.LossesGamesLastYearS2                              ),
                ("@WinsGamesLastMonthS2"                               ,player.WinsGamesLastMonthS2                               ),
                ("@LossesGamesLastMonthS2"                             ,player.LossesGamesLastMonthS2                             ),
                ("@WinsGamesLastWeekS2"                                ,player.WinsGamesLastWeekS2                                ),
                ("@LossesGamesLastWeekS2"                              ,player.LossesGamesLastWeekS2                              ),
                ("@WinsGamesTotalS3"                                   ,player.WinsGamesTotalS3                                   ),
                ("@LossesGamesTotalS3"                                 ,player.LossesGamesTotalS3                                 ),
                ("@WinsGamesLastYearS3"                                ,player.WinsGamesLastYearS3                                ),
                ("@LossesGamesLastYearS3"                              ,player.LossesGamesLastYearS3                              ),
                ("@WinsGamesLastMonthS3"                               ,player.WinsGamesLastMonthS3                               ),
                ("@LossesGamesLastMonthS3"                             ,player.LossesGamesLastMonthS3                             ),
                ("@WinsGamesLastWeekS3"                                ,player.WinsGamesLastWeekS3                                ),
                ("@LossesGamesLastWeekS3"                              ,player.LossesGamesLastWeekS3                              ),
                ("@WinsGamesTotalS4"                                   ,player.WinsGamesTotalS4                                   ),
                ("@LossesGamesTotalS4"                                 ,player.LossesGamesTotalS4                                 ),
                ("@WinsGamesLastYearS4"                                ,player.WinsGamesLastYearS4                                ),
                ("@LossesGamesLastYearS4"                              ,player.LossesGamesLastYearS4                              ),
                ("@WinsGamesLastMonthS4"                               ,player.WinsGamesLastMonthS4                               ),
                ("@LossesGamesLastMonthS4"                             ,player.LossesGamesLastMonthS4                             ),
                ("@WinsGamesLastWeekS4"                                ,player.WinsGamesLastWeekS4                                ),
                ("@LossesGamesLastWeekS4"                              ,player.LossesGamesLastWeekS4                              ),
                ("@DateSinceLastWin"                                   ,player.DateSinceLastWin                                   ),
                ("@DateSinceLastWinS1"                                 ,player.DateSinceLastWinS1                                 ),
                ("@DateSinceLastWinS2"                                 ,player.DateSinceLastWinS2                                 ),
                ("@DateSinceLastWinS3"                                 ,player.DateSinceLastWinS3                                 ),
                ("@DateSinceLastWinS4"                                 ,player.DateSinceLastWinS4                                 ),
                ("@DateSinceLastLoss"                                  ,player.DateSinceLastLoss                                  ),
                ("@DateSinceLastLossS1"                                ,player.DateSinceLastLossS1                                ),
                ("@DateSinceLastLossS2"                                ,player.DateSinceLastLossS2                                ),
                ("@DateSinceLastLossS3"                                ,player.DateSinceLastLossS3                                ),
                ("@DateSinceLastLossS4"                                ,player.DateSinceLastLossS4                                ),
                ("@TotalWinsAsFavourite"                               ,player.TotalWinsAsFavourite                               ),
                ("@TotalWinsAsUnderdog"                                ,player.TotalWinsAsUnderdog                                ),
                ("@TotalLossesAsFavourite"                             ,player.TotalLossesAsFavourite                             ),
                ("@TotalLossesAsUnderdog"                              ,player.TotalLossesAsUnderdog                              ),
                ("@WinsAsFavouriteRatio"                               ,player.WinsAsFavouriteRatio                               ),
                ("@LossesAsFavouriteRatio"                             ,player.LossesAsFavouriteRatio                             ),
                ("@WinsAsUnderdogRatio"                                ,player.WinsAsUnderdogRatio                                ),
                ("@LossesAsUnderdogRatio"                              ,player.LossesAsUnderdogRatio                              ),
                ("@AverageWinningProbabilityAtWonAsFavourite"          ,player.AverageWinningProbabilityAtWonAsFavourite          ),
                ("@AverageWinningProbabilityAtWonAsUnderdog"           ,player.AverageWinningProbabilityAtWonAsUnderdog           ),
                ("@AverageWinningProbabilityAtLossAsFavourite"         ,player.AverageWinningProbabilityAtLossAsFavourite         ),
                ("@AverageWinningProbabilityAtLossAsUnderdog"          ,player.AverageWinningProbabilityAtLossAsUnderdog          ),
                ("@TotalWinsAsFavouriteLastYear"                       ,player.TotalWinsAsFavouriteLastYear                       ),
                ("@TotalWinsAsUnderdogLastYear"                        ,player.TotalWinsAsUnderdogLastYear                        ),
                ("@TotalLossesAsFavouriteLastYear"                     ,player.TotalLossesAsFavouriteLastYear                     ),
                ("@TotalLossesAsUnderdogLastYear"                      ,player.TotalLossesAsUnderdogLastYear                      ),
                ("@WinsAsFavouriteLastYearRatio"                       ,player.WinsAsFavouriteLastYearRatio                       ),
                ("@LossesAsFavouriteLastYearRatio"                     ,player.LossesAsFavouriteLastYearRatio                     ),
                ("@WinsAsUnderdogLastYearRatio"                        ,player.WinsAsUnderdogLastYearRatio                        ),
                ("@LossesAsUnderdogLastYearRatio"                      ,player.LossesAsUnderdogLastYearRatio                      ),
                ("@AverageWinningProbabilityAtWonAsFavouriteLastYear"  ,player.AverageWinningProbabilityAtWonAsFavouriteLastYear  ),
                ("@AverageWinningProbabilityAtWonAsUnderdogLastYear"   ,player.AverageWinningProbabilityAtWonAsUnderdogLastYear   ),
                ("@AverageWinningProbabilityAtLossAsFavouriteLastYear" ,player.AverageWinningProbabilityAtLossAsFavouriteLastYear ),
                ("@AverageWinningProbabilityAtLossAsUnderdogLastYear"  ,player.AverageWinningProbabilityAtLossAsUnderdogLastYear  ),
                ("@TotalWinsAsFavouriteLastMonth"                      ,player.TotalWinsAsFavouriteLastMonth                      ),
                ("@TotalWinsAsUnderdogLastMonth"                       ,player.TotalWinsAsUnderdogLastMonth                       ),
                ("@TotalLossesAsFavouriteLastMonth"                    ,player.TotalLossesAsFavouriteLastMonth                    ),
                ("@TotalLossesAsUnderdogLastMonth"                     ,player.TotalLossesAsUnderdogLastMonth                     ),
                ("@WinsAsFavouriteLastMonthRatio"                      ,player.WinsAsFavouriteLastMonthRatio                      ),
                ("@LossesAsFavouriteLastMonthRatio"                    ,player.LossesAsFavouriteLastMonthRatio                    ),
                ("@WinsAsUnderdogLastMonthRatio"                       ,player.WinsAsUnderdogLastMonthRatio                       ),
                ("@LossesAsUnderdogLastMonthRatio"                     ,player.LossesAsUnderdogLastMonthRatio                     ),
                ("@AverageWinningProbabilityAtWonAsFavouriteLastMonth" ,player.AverageWinningProbabilityAtWonAsFavouriteLastMonth ),
                ("@AverageWinningProbabilityAtWonAsUnderdogLastMonth"  ,player.AverageWinningProbabilityAtWonAsUnderdogLastMonth  ),
                ("@AverageWinningProbabilityAtLossAsFavouriteLastMonth",player.AverageWinningProbabilityAtLossAsFavouriteLastMonth),
                ("@AverageWinningProbabilityAtLossAsUnderdogLastMonth" ,player.AverageWinningProbabilityAtLossAsUnderdogLastMonth ),
                ("@TotalWinsAsFavouriteLastWeek"                       ,player.TotalWinsAsFavouriteLastWeek                       ),
                ("@TotalWinsAsUnderdogLastWeek"                        ,player.TotalWinsAsUnderdogLastWeek                        ),
                ("@TotalLossesAsFavouriteLastWeek"                     ,player.TotalLossesAsFavouriteLastWeek                     ),
                ("@TotalLossesAsUnderdogLastWeek"                      ,player.TotalLossesAsUnderdogLastWeek                      ),
                ("@WinsAsFavouriteLastWeekRatio"                       ,player.WinsAsFavouriteLastWeekRatio                       ),
                ("@LossesAsFavouriteLastWeekRatio"                     ,player.LossesAsFavouriteLastWeekRatio                     ),
                ("@WinsAsUnderdogLastWeekRatio"                        ,player.WinsAsUnderdogLastWeekRatio                        ),
                ("@LossesAsUnderdogLastWeekRatio"                      ,player.LossesAsUnderdogLastWeekRatio                      ),
                ("@AverageWinningProbabilityAtWonAsFavouriteLastWeek"  ,player.AverageWinningProbabilityAtWonAsFavouriteLastWeek  ),
                ("@AverageWinningProbabilityAtWonAsUnderdogLastWeek"   ,player.AverageWinningProbabilityAtWonAsUnderdogLastWeek   ),
                ("@AverageWinningProbabilityAtLossAsFavouriteLastWeek" ,player.AverageWinningProbabilityAtLossAsFavouriteLastWeek ),
                ("@AverageWinningProbabilityAtLossAsUnderdogLastWeek"  ,player.AverageWinningProbabilityAtLossAsUnderdogLastWeek  ),
                ("@Streak"                                             ,player.Streak                                             ),
                ("@StreakS1"                                           ,player.StreakS1                                           ),
                ("@StreakS2"                                           ,player.StreakS2                                           ),
                ("@StreakS3"                                           ,player.StreakS3                                           ),
                ("@StreakS4"                                           ,player.StreakS4                                           )
                };

                foreach (var (name, value) in parameters)
                {
                    var p = command.CreateParameter();
                    p.ParameterName = name;
                    p.Value = value ?? DBNull.Value;
                    command.Parameters.Add(p);
                }

                if (_connection.State != ConnectionState.Open) _connection.Open();
                await Task.Run(() => command.ExecuteNonQuery());
            }
            catch (Exception ex)
            {
                string aaa;
                aaa = ex.Message;
            }

        }

        public async Task<bool> ExistsAsync(int playerTPId)
        {
            const string sql = "SELECT TOP(1) 1 FROM dbo.[Player] WITH (NOLOCK) WHERE PlayerTPId = @id;";
            await using var con = new SqlConnection(_connection.ConnectionString);
            await con.OpenAsync();

            await using var cmd = new SqlCommand(sql, con);
            cmd.Parameters.Add("@id", SqlDbType.Int).Value = playerTPId;

            var obj = await cmd.ExecuteScalarAsync();
            return obj != null && obj != DBNull.Value;
        }
    }
}