USE [BonzoByte]
GO

/****** Object:  View [dbo].[Matches4NN]    Script Date: 22.8.2025. 15:41:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE view [dbo].[vw_Matches4NN] AS
select 
	   m.MatchTPId
	 , m.TournamentEventTPId
	 , te.TournamentEventDate
	 , te.Prize
	 , tec.CountryTPId as TournamentEventCountryTPId
	 , tl.TournamentLevelId
	 , tt.TournamentTypeId
	 , tes.SurfaceId as TournamentEventSurfaceId
	 , m.DateTime
	 , m.Player1TPId
	 , p1.PlayerName as Player1Name
	 , p1c.CountryTPId as Player1CountryTPId
	 , p1.PlayerBirthDate as Player1BirthDate
	 , p1.PlayerHeight as Player1Height
	 , p1.PlayerWeight as Player1Weight
	 , p1.PlayerTurnedPro as Player1TurnedPro
	 , p1p.PlaysId as Player1PlaysId
	 , p1p.PlaysName as Player1PlaysName
	 , m.Player1Seed
	 , m.Player2TPId
	 , p2.PlayerName as Player2Name
	 , p2c.CountryTPId as Player2CountryTPId
	 , p2.PlayerBirthDate as Player2BirthDate
	 , p2.PlayerHeight as Player2Height
	 , p2.PlayerWeight as Player2Weight
	 , p2.PlayerTurnedPro as Player2TurnedPro
	 , p2p.PlaysId as Player2PlaysId
	 , p2p.PlaysName as Player2PlaysName
	 , m.Player2Seed
	 , m.SurfaceId as MatchSurfaceId
	 , s.SurfaceName as MatchSurfaceName
	 , m.RoundId
	 , r.RoundName
	 , m.Player1TrueSkillMeanOldM
	 , m.Player1TrueSkillStandardDeviationOldM
	 , m.Player2TrueSkillMeanOldM
	 , m.Player2TrueSkillStandardDeviationOldM
	 , m.WinProbabilityPlayer1M
	 , m.Player1TrueSkillMeanOldSM
	 , m.Player1TrueSkillStandardDeviationOldSM
	 , m.Player2TrueSkillMeanOldSM
	 , m.Player2TrueSkillStandardDeviationOldSM
	 , m.WinProbabilityPlayer1SM
	 , m.Player1TrueSkillMeanOldGSM
	 , m.Player1TrueSkillStandardDeviationOldGSM
	 , m.Player2TrueSkillMeanOldGSM
	 , m.Player2TrueSkillStandardDeviationOldGSM
	 , m.WinProbabilityPlayer1GSM
	 , m.Player1TrueSkillMeanOldMS1
	 , m.Player1TrueSkillStandardDeviationOldMS1
	 , m.Player2TrueSkillMeanOldMS1
	 , m.Player2TrueSkillStandardDeviationOldMS1
	 , m.WinProbabilityPlayer1MS1
	 , m.Player1TrueSkillMeanOldSMS1
	 , m.Player1TrueSkillStandardDeviationOldSMS1
	 , m.Player2TrueSkillMeanOldSMS1
	 , m.Player2TrueSkillStandardDeviationOldSMS1
	 , m.WinProbabilityPlayer1SMS1
	 , m.Player1TrueSkillMeanOldGSMS1
	 , m.Player1TrueSkillStandardDeviationOldGSMS1
	 , m.Player2TrueSkillMeanOldGSMS1
	 , m.Player2TrueSkillStandardDeviationOldGSMS1
	 , m.WinProbabilityPlayer1GSMS1
	 , m.Player1TrueSkillMeanOldMS2
	 , m.Player1TrueSkillStandardDeviationOldMS2
	 , m.Player2TrueSkillMeanOldMS2
	 , m.Player2TrueSkillStandardDeviationOldMS2
	 , m.WinProbabilityPlayer1MS2
	 , m.Player1TrueSkillMeanOldSMS2
	 , m.Player1TrueSkillStandardDeviationOldSMS2
	 , m.Player2TrueSkillMeanOldSMS2
	 , m.Player2TrueSkillStandardDeviationOldSMS2
	 , m.WinProbabilityPlayer1SMS2
	 , m.Player1TrueSkillMeanOldGSMS2
	 , m.Player1TrueSkillStandardDeviationOldGSMS2
	 , m.Player2TrueSkillMeanOldGSMS2
	 , m.Player2TrueSkillStandardDeviationOldGSMS2
	 , m.WinProbabilityPlayer1GSMS2
	 , m.Player1TrueSkillMeanOldMS3
	 , m.Player1TrueSkillStandardDeviationOldMS3
	 , m.Player2TrueSkillMeanOldMS3
	 , m.Player2TrueSkillStandardDeviationOldMS3
	 , m.WinProbabilityPlayer1MS3
	 , m.Player1TrueSkillMeanOldSMS3
	 , m.Player1TrueSkillStandardDeviationOldSMS3
	 , m.Player2TrueSkillMeanOldSMS3
	 , m.Player2TrueSkillStandardDeviationOldSMS3
	 , m.WinProbabilityPlayer1SMS3
	 , m.Player1TrueSkillMeanOldGSMS3
	 , m.Player1TrueSkillStandardDeviationOldGSMS3
	 , m.Player2TrueSkillMeanOldGSMS3
	 , m.Player2TrueSkillStandardDeviationOldGSMS3
	 , m.WinProbabilityPlayer1GSMS3
	 , m.Player1TrueSkillMeanOldMS4
	 , m.Player1TrueSkillStandardDeviationOldMS4
	 , m.Player2TrueSkillMeanOldMS4
	 , m.Player2TrueSkillStandardDeviationOldMS4
	 , m.WinProbabilityPlayer1MS4
	 , m.Player1TrueSkillMeanOldSMS4
	 , m.Player1TrueSkillStandardDeviationOldSMS4
	 , m.Player2TrueSkillMeanOldSMS4
	 , m.Player2TrueSkillStandardDeviationOldSMS4
	 , m.WinProbabilityPlayer1SMS4
	 , m.Player1TrueSkillMeanOldGSMS4
	 , m.Player1TrueSkillStandardDeviationOldGSMS4
	 , m.Player2TrueSkillMeanOldGSMS4
	 , m.Player2TrueSkillStandardDeviationOldGSMS4
	 , m.WinProbabilityPlayer1GSMS4
	 , m.Player1WinsTotal
	 , m.Player1LossesTotal
	 , m.Player1WinsLastYear
	 , m.Player1LossesLastYear
	 , m.Player1WinsLastMonth
	 , m.Player1LossesLastMonth
	 , m.Player1WinsLastWeek
	 , m.Player1LossesLastWeek
	 , m.Player2WinsTotal
	 , m.Player2LossesTotal
	 , m.Player2WinsLastYear
	 , m.Player2LossesLastYear
	 , m.Player2WinsLastMonth
	 , m.Player2LossesLastMonth
	 , m.Player2WinsLastWeek
	 , m.Player2LossesLastWeek
	 , m.Player1WinsTotalS1
	 , m.Player1LossesTotalS1
	 , m.Player1WinsLastYearS1
	 , m.Player1LossesLastYearS1
	 , m.Player1WinsLastMonthS1
	 , m.Player1LossesLastMonthS1
	 , m.Player1WinsLastWeekS1
	 , m.Player1LossesLastWeekS1
	 , m.Player2WinsTotalS1
	 , m.Player2LossesTotalS1
	 , m.Player2WinsLastYearS1
	 , m.Player2LossesLastYearS1
	 , m.Player2WinsLastMonthS1
	 , m.Player2LossesLastMonthS1
	 , m.Player2WinsLastWeekS1
	 , m.Player2LossesLastWeekS1
	 , m.Player1WinsTotalS2
	 , m.Player1LossesTotalS2
	 , m.Player1WinsLastYearS2
	 , m.Player1LossesLastYearS2
	 , m.Player1WinsLastMonthS2
	 , m.Player1LossesLastMonthS2
	 , m.Player1WinsLastWeekS2
	 , m.Player1LossesLastWeekS2
	 , m.Player2WinsTotalS2
	 , m.Player2LossesTotalS2
	 , m.Player2WinsLastYearS2
	 , m.Player2LossesLastYearS2
	 , m.Player2WinsLastMonthS2
	 , m.Player2LossesLastMonthS2
	 , m.Player2WinsLastWeekS2
	 , m.Player2LossesLastWeekS2
	 , m.Player1WinsTotalS3
	 , m.Player1LossesTotalS3
	 , m.Player1WinsLastYearS3
	 , m.Player1LossesLastYearS3
	 , m.Player1WinsLastMonthS3
	 , m.Player1LossesLastMonthS3
	 , m.Player1WinsLastWeekS3
	 , m.Player1LossesLastWeekS3
	 , m.Player2WinsTotalS3
	 , m.Player2LossesTotalS3
	 , m.Player2WinsLastYearS3
	 , m.Player2LossesLastYearS3
	 , m.Player2WinsLastMonthS3
	 , m.Player2LossesLastMonthS3
	 , m.Player2WinsLastWeekS3
	 , m.Player2LossesLastWeekS3
	 , m.Player1WinsTotalS4
	 , m.Player1LossesTotalS4
	 , m.Player1WinsLastYearS4
	 , m.Player1LossesLastYearS4
	 , m.Player1WinsLastMonthS4
	 , m.Player1LossesLastMonthS4
	 , m.Player1WinsLastWeekS4
	 , m.Player1LossesLastWeekS4
	 , m.Player2WinsTotalS4
	 , m.Player2LossesTotalS4
	 , m.Player2WinsLastYearS4
	 , m.Player2LossesLastYearS4
	 , m.Player2WinsLastMonthS4
	 , m.Player2LossesLastMonthS4
	 , m.Player2WinsLastWeekS4
	 , m.Player2LossesLastWeekS4
	 , m.Player1WinsSetsTotal
	 , m.Player1LossesSetsTotal
	 , m.Player1WinsSetsLastYear
	 , m.Player1LossesSetsLastYear
	 , m.Player1WinsSetsLastMonth
	 , m.Player1LossesSetsLastMonth
	 , m.Player1WinsSetsLastWeek
	 , m.Player1LossesSetsLastWeek
	 , m.Player2WinsSetsTotal
	 , m.Player2LossesSetsTotal
	 , m.Player2WinsSetsLastYear
	 , m.Player2LossesSetsLastYear
	 , m.Player2WinsSetsLastMonth
	 , m.Player2LossesSetsLastMonth
	 , m.Player2WinsSetsLastWeek
	 , m.Player2LossesSetsLastWeek
	 , m.Player1WinsSetsTotalS1
	 , m.Player1LossesSetsTotalS1
	 , m.Player1WinsSetsLastYearS1
	 , m.Player1LossesSetsLastYearS1
	 , m.Player1WinsSetsLastMonthS1
	 , m.Player1LossesSetsLastMonthS1
	 , m.Player1WinsSetsLastWeekS1
	 , m.Player1LossesSetsLastWeekS1
	 , m.Player2WinsSetsTotalS1
	 , m.Player2LossesSetsTotalS1
	 , m.Player2WinsSetsLastYearS1
	 , m.Player2LossesSetsLastYearS1
	 , m.Player2WinsSetsLastMonthS1
	 , m.Player2LossesSetsLastMonthS1
	 , m.Player2WinsSetsLastWeekS1
	 , m.Player2LossesSetsLastWeekS1
	 , m.Player1WinsSetsTotalS2
	 , m.Player1LossesSetsTotalS2
	 , m.Player1WinsSetsLastYearS2
	 , m.Player1LossesSetsLastYearS2
	 , m.Player1WinsSetsLastMonthS2
	 , m.Player1LossesSetsLastMonthS2
	 , m.Player1WinsSetsLastWeekS2
	 , m.Player1LossesSetsLastWeekS2
	 , m.Player2WinsSetsTotalS2
	 , m.Player2LossesSetsTotalS2
	 , m.Player2WinsSetsLastYearS2
	 , m.Player2LossesSetsLastYearS2
	 , m.Player2WinsSetsLastMonthS2
	 , m.Player2LossesSetsLastMonthS2
	 , m.Player2WinsSetsLastWeekS2
	 , m.Player2LossesSetsLastWeekS2
	 , m.Player1WinsSetsTotalS3
	 , m.Player1LossesSetsTotalS3
	 , m.Player1WinsSetsLastYearS3
	 , m.Player1LossesSetsLastYearS3
	 , m.Player1WinsSetsLastMonthS3
	 , m.Player1LossesSetsLastMonthS3
	 , m.Player1WinsSetsLastWeekS3
	 , m.Player1LossesSetsLastWeekS3
	 , m.Player2WinsSetsTotalS3
	 , m.Player2LossesSetsTotalS3
	 , m.Player2WinsSetsLastYearS3
	 , m.Player2LossesSetsLastYearS3
	 , m.Player2WinsSetsLastMonthS3
	 , m.Player2LossesSetsLastMonthS3
	 , m.Player2WinsSetsLastWeekS3
	 , m.Player2LossesSetsLastWeekS3
	 , m.Player1WinsSetsTotalS4
	 , m.Player1LossesSetsTotalS4
	 , m.Player1WinsSetsLastYearS4
	 , m.Player1LossesSetsLastYearS4
	 , m.Player1WinsSetsLastMonthS4
	 , m.Player1LossesSetsLastMonthS4
	 , m.Player1WinsSetsLastWeekS4
	 , m.Player1LossesSetsLastWeekS4
	 , m.Player2WinsSetsTotalS4
	 , m.Player2LossesSetsTotalS4
	 , m.Player2WinsSetsLastYearS4
	 , m.Player2LossesSetsLastYearS4
	 , m.Player2WinsSetsLastMonthS4
	 , m.Player2LossesSetsLastMonthS4
	 , m.Player2WinsSetsLastWeekS4
	 , m.Player2LossesSetsLastWeekS4
	 , m.Player1WinsGamesTotal
	 , m.Player1LossesGamesTotal
	 , m.Player1WinsGamesLastYear
	 , m.Player1LossesGamesLastYear
	 , m.Player1WinsGamesLastMonth
	 , m.Player1LossesGamesLastMonth
	 , m.Player1WinsGamesLastWeek
	 , m.Player1LossesGamesLastWeek
	 , m.Player2WinsGamesTotal
	 , m.Player2LossesGamesTotal
	 , m.Player2WinsGamesLastYear
	 , m.Player2LossesGamesLastYear
	 , m.Player2WinsGamesLastMonth
	 , m.Player2LossesGamesLastMonth
	 , m.Player2WinsGamesLastWeek
	 , m.Player2LossesGamesLastWeek
	 , m.Player1WinsGamesTotalS1
	 , m.Player1LossesGamesTotalS1
	 , m.Player1WinsGamesLastYearS1
	 , m.Player1LossesGamesLastYearS1
	 , m.Player1WinsGamesLastMonthS1
	 , m.Player1LossesGamesLastMonthS1
	 , m.Player1WinsGamesLastWeekS1
	 , m.Player1LossesGamesLastWeekS1
	 , m.Player2WinsGamesTotalS1
	 , m.Player2LossesGamesTotalS1
	 , m.Player2WinsGamesLastYearS1
	 , m.Player2LossesGamesLastYearS1
	 , m.Player2WinsGamesLastMonthS1
	 , m.Player2LossesGamesLastMonthS1
	 , m.Player2WinsGamesLastWeekS1
	 , m.Player2LossesGamesLastWeekS1
	 , m.Player1WinsGamesTotalS2
	 , m.Player1LossesGamesTotalS2
	 , m.Player1WinsGamesLastYearS2
	 , m.Player1LossesGamesLastYearS2
	 , m.Player1WinsGamesLastMonthS2
	 , m.Player1LossesGamesLastMonthS2
	 , m.Player1WinsGamesLastWeekS2
	 , m.Player1LossesGamesLastWeekS2
	 , m.Player2WinsGamesTotalS2
	 , m.Player2LossesGamesTotalS2
	 , m.Player2WinsGamesLastYearS2
	 , m.Player2LossesGamesLastYearS2
	 , m.Player2WinsGamesLastMonthS2
	 , m.Player2LossesGamesLastMonthS2
	 , m.Player2WinsGamesLastWeekS2
	 , m.Player2LossesGamesLastWeekS2
	 , m.Player1WinsGamesTotalS3
	 , m.Player1LossesGamesTotalS3
	 , m.Player1WinsGamesLastYearS3
	 , m.Player1LossesGamesLastYearS3
	 , m.Player1WinsGamesLastMonthS3
	 , m.Player1LossesGamesLastMonthS3
	 , m.Player1WinsGamesLastWeekS3
	 , m.Player1LossesGamesLastWeekS3
	 , m.Player2WinsGamesTotalS3
	 , m.Player2LossesGamesTotalS3
	 , m.Player2WinsGamesLastYearS3
	 , m.Player2LossesGamesLastYearS3
	 , m.Player2WinsGamesLastMonthS3
	 , m.Player2LossesGamesLastMonthS3
	 , m.Player2WinsGamesLastWeekS3
	 , m.Player2LossesGamesLastWeekS3
	 , m.Player1WinsGamesTotalS4
	 , m.Player1LossesGamesTotalS4
	 , m.Player1WinsGamesLastYearS4
	 , m.Player1LossesGamesLastYearS4
	 , m.Player1WinsGamesLastMonthS4
	 , m.Player1LossesGamesLastMonthS4
	 , m.Player1WinsGamesLastWeekS4
	 , m.Player1LossesGamesLastWeekS4
	 , m.Player2WinsGamesTotalS4
	 , m.Player2LossesGamesTotalS4
	 , m.Player2WinsGamesLastYearS4
	 , m.Player2LossesGamesLastYearS4
	 , m.Player2WinsGamesLastMonthS4
	 , m.Player2LossesGamesLastMonthS4
	 , m.Player2WinsGamesLastWeekS4
	 , m.Player2LossesGamesLastWeekS4
	 , m.Player1DaysSinceLastWin
	 , m.Player2DaysSinceLastWin
	 , m.Player1DaysSinceLastWinS1
	 , m.Player2DaysSinceLastWinS1
	 , m.Player1DaysSinceLastWinS2
	 , m.Player2DaysSinceLastWinS2
	 , m.Player1DaysSinceLastWinS3
	 , m.Player2DaysSinceLastWinS3
	 , m.Player1DaysSinceLastWinS4
	 , m.Player2DaysSinceLastWinS4
	 , m.Player1DaysSinceLastLoss
	 , m.Player2DaysSinceLastLoss
	 , m.Player1DaysSinceLastLossS1
	 , m.Player2DaysSinceLastLossS1
	 , m.Player1DaysSinceLastLossS2
	 , m.Player2DaysSinceLastLossS2
	 , m.Player1DaysSinceLastLossS3
	 , m.Player2DaysSinceLastLossS3
	 , m.Player1DaysSinceLastLossS4
	 , m.Player2DaysSinceLastLossS4
	 , m.Player1TotalWinsAsFavourite
	 , m.Player2TotalWinsAsFavourite
	 , m.Player1TotalWinsAsUnderdog
	 , m.Player2TotalWinsAsUnderdog
	 , m.Player1TotalLossesAsFavourite
	 , m.Player2TotalLossesAsFavourite
	 , m.Player1TotalLossesAsUnderdog
	 , m.Player2TotalLossesAsUnderdog
	 , m.Player1AverageWinningProbabilityAtWonAsFavourite
	 , m.Player2AverageWinningProbabilityAtWonAsFavourite
	 , m.Player1AverageWinningProbabilityAtWonAsUnderdog
	 , m.Player2AverageWinningProbabilityAtWonAsUnderdog
	 , m.Player1AverageWinningProbabilityAtLossAsFavourite
	 , m.Player2AverageWinningProbabilityAtLossAsFavourite
	 , m.Player1AverageWinningProbabilityAtLossAsUnderdog
	 , m.Player2AverageWinningProbabilityAtLossAsUnderdog
	 , m.Player1TotalWinsAsFavouriteLastYear
	 , m.Player2TotalWinsAsFavouriteLastYear
	 , m.Player1TotalWinsAsUnderdogLastYear
	 , m.Player2TotalWinsAsUnderdogLastYear
	 , m.Player1TotalLossesAsFavouriteLastYear
	 , m.Player2TotalLossesAsFavouriteLastYear
	 , m.Player1TotalLossesAsUnderdogLastYear
	 , m.Player2TotalLossesAsUnderdogLastYear
	 , m.Player1AverageWinningProbabilityAtWonAsFavouriteLastYear
	 , m.Player2AverageWinningProbabilityAtWonAsFavouriteLastYear
	 , m.Player1AverageWinningProbabilityAtWonAsUnderdogLastYear
	 , m.Player2AverageWinningProbabilityAtWonAsUnderdogLastYear
	 , m.Player1AverageWinningProbabilityAtLossAsFavouriteLastYear
	 , m.Player2AverageWinningProbabilityAtLossAsFavouriteLastYear
	 , m.Player1AverageWinningProbabilityAtLossAsUnderdogLastYear
	 , m.Player2AverageWinningProbabilityAtLossAsUnderdogLastYear
	 , m.Player1TotalWinsAsFavouriteLastMonth
	 , m.Player2TotalWinsAsFavouriteLastMonth
	 , m.Player1TotalWinsAsUnderdogLastMonth
	 , m.Player2TotalWinsAsUnderdogLastMonth
	 , m.Player1TotalLossesAsFavouriteLastMonth
	 , m.Player2TotalLossesAsFavouriteLastMonth
	 , m.Player1TotalLossesAsUnderdogLastMonth
	 , m.Player2TotalLossesAsUnderdogLastMonth
	 , m.Player1AverageWinningProbabilityAtWonAsFavouriteLastMonth
	 , m.Player2AverageWinningProbabilityAtWonAsFavouriteLastMonth
	 , m.Player1AverageWinningProbabilityAtWonAsUnderdogLastMonth
	 , m.Player2AverageWinningProbabilityAtWonAsUnderdogLastMonth
	 , m.Player1AverageWinningProbabilityAtLossAsFavouriteLastMonth
	 , m.Player2AverageWinningProbabilityAtLossAsFavouriteLastMonth
	 , m.Player1AverageWinningProbabilityAtLossAsUnderdogLastMonth
	 , m.Player2AverageWinningProbabilityAtLossAsUnderdogLastMonth
	 , m.Player1TotalWinsAsFavouriteLastWeek
	 , m.Player2TotalWinsAsFavouriteLastWeek
	 , m.Player1TotalWinsAsUnderdogLastWeek
	 , m.Player2TotalWinsAsUnderdogLastWeek
	 , m.Player1TotalLossesAsFavouriteLastWeek
	 , m.Player2TotalLossesAsFavouriteLastWeek
	 , m.Player1TotalLossesAsUnderdogLastWeek
	 , m.Player2TotalLossesAsUnderdogLastWeek
	 , m.Player1AverageWinningProbabilityAtWonAsFavouriteLastWeek
	 , m.Player2AverageWinningProbabilityAtWonAsFavouriteLastWeek
	 , m.Player1AverageWinningProbabilityAtWonAsUnderdogLastWeek
	 , m.Player2AverageWinningProbabilityAtWonAsUnderdogLastWeek
	 , m.Player1AverageWinningProbabilityAtLossAsFavouriteLastWeek
	 , m.Player2AverageWinningProbabilityAtLossAsFavouriteLastWeek
	 , m.Player1AverageWinningProbabilityAtLossAsUnderdogLastWeek
	 , m.Player2AverageWinningProbabilityAtLossAsUnderdogLastWeek
	 , m.Player1H2HOld
	 , m.Player2H2HOld
	 , m.Player1H2HOldS1
	 , m.Player2H2HOldS1
	 , m.Player1H2HOldS2
	 , m.Player2H2HOldS2
	 , m.Player1H2HOldS3
	 , m.Player2H2HOldS3
	 , m.Player1H2HOldS4
	 , m.Player2H2HOldS4
	 , m.Player1H2HTrueSkillMeanOldM
	 , m.Player1H2HTrueSkillStandardDeviationOldM
	 , m.Player2H2HTrueSkillMeanOldM
	 , m.Player2H2HTrueSkillStandardDeviationOldM
	 , m.WinProbabilityPlayer1H2HM
	 , m.Player1H2HTrueSkillMeanOldSM
	 , m.Player1H2HTrueSkillStandardDeviationOldSM
	 , m.Player2H2HTrueSkillMeanOldSM
	 , m.Player2H2HTrueSkillStandardDeviationOldSM
	 , m.WinProbabilityPlayer1H2HSM
	 , m.Player1H2HTrueSkillMeanOldGSM
	 , m.Player1H2HTrueSkillStandardDeviationOldGSM
	 , m.Player2H2HTrueSkillMeanOldGSM
	 , m.Player2H2HTrueSkillStandardDeviationOldGSM
	 , m.WinProbabilityPlayer1H2HGSM
	 , m.Player1H2HTrueSkillMeanOldMS1
	 , m.Player1H2HTrueSkillStandardDeviationOldMS1
	 , m.Player2H2HTrueSkillMeanOldMS1
	 , m.Player2H2HTrueSkillStandardDeviationOldMS1
	 , m.WinProbabilityPlayer1H2HMS1
	 , m.Player1H2HTrueSkillMeanOldSMS1
	 , m.Player1H2HTrueSkillStandardDeviationOldSMS1
	 , m.Player2H2HTrueSkillMeanOldSMS1
	 , m.Player2H2HTrueSkillStandardDeviationOldSMS1
	 , m.WinProbabilityPlayer1H2HSMS1
	 , m.Player1H2HTrueSkillMeanOldGSMS1
	 , m.Player1H2HTrueSkillStandardDeviationOldGSMS1
	 , m.Player2H2HTrueSkillMeanOldGSMS1
	 , m.Player2H2HTrueSkillStandardDeviationOldGSMS1
	 , m.WinProbabilityPlayer1H2HGSMS1
	 , m.Player1H2HTrueSkillMeanOldMS2
	 , m.Player1H2HTrueSkillStandardDeviationOldMS2
	 , m.Player2H2HTrueSkillMeanOldMS2
	 , m.Player2H2HTrueSkillStandardDeviationOldMS2
	 , m.WinProbabilityPlayer1H2HMS2
	 , m.Player1H2HTrueSkillMeanOldSMS2
	 , m.Player1H2HTrueSkillStandardDeviationOldSMS2
	 , m.Player2H2HTrueSkillMeanOldSMS2
	 , m.Player2H2HTrueSkillStandardDeviationOldSMS2
	 , m.WinProbabilityPlayer1H2HSMS2
	 , m.Player1H2HTrueSkillMeanOldGSMS2
	 , m.Player1H2HTrueSkillStandardDeviationOldGSMS2
	 , m.Player2H2HTrueSkillMeanOldGSMS2
	 , m.Player2H2HTrueSkillStandardDeviationOldGSMS2
	 , m.WinProbabilityPlayer1H2HGSMS2
	 , m.Player1H2HTrueSkillMeanOldMS3
	 , m.Player1H2HTrueSkillStandardDeviationOldMS3
	 , m.Player2H2HTrueSkillMeanOldMS3
	 , m.Player2H2HTrueSkillStandardDeviationOldMS3
	 , m.WinProbabilityPlayer1H2HMS3
	 , m.Player1H2HTrueSkillMeanOldSMS3
	 , m.Player1H2HTrueSkillStandardDeviationOldSMS3
	 , m.Player2H2HTrueSkillMeanOldSMS3
	 , m.Player2H2HTrueSkillStandardDeviationOldSMS3
	 , m.WinProbabilityPlayer1H2HSMS3
	 , m.Player1H2HTrueSkillMeanOldGSMS3
	 , m.Player1H2HTrueSkillStandardDeviationOldGSMS3
	 , m.Player2H2HTrueSkillMeanOldGSMS3
	 , m.Player2H2HTrueSkillStandardDeviationOldGSMS3
	 , m.WinProbabilityPlayer1H2HGSMS3
	 , m.Player1H2HTrueSkillMeanOldMS4
	 , m.Player1H2HTrueSkillStandardDeviationOldMS4
	 , m.Player2H2HTrueSkillMeanOldMS4
	 , m.Player2H2HTrueSkillStandardDeviationOldMS4
	 , m.WinProbabilityPlayer1H2HMS4
	 , m.Player1H2HTrueSkillMeanOldSMS4
	 , m.Player1H2HTrueSkillStandardDeviationOldSMS4
	 , m.Player2H2HTrueSkillMeanOldSMS4
	 , m.Player2H2HTrueSkillStandardDeviationOldSMS4
	 , m.WinProbabilityPlayer1H2HSMS4
	 , m.Player1H2HTrueSkillMeanOldGSMS4
	 , m.Player1H2HTrueSkillStandardDeviationOldGSMS4
	 , m.Player2H2HTrueSkillMeanOldGSMS4
	 , m.Player2H2HTrueSkillStandardDeviationOldGSMS4
	 , m.WinProbabilityPlayer1H2HGSMS4
	 , m.Player1Streak
	 , m.Player2Streak
	 , m.Player1StreakS1
	 , m.Player2StreakS1
	 , m.Player1StreakS2
	 , m.Player2StreakS2
	 , m.Player1StreakS3
	 , m.Player2StreakS3
	 , m.Player1StreakS4
	 , m.Player2StreakS4
from Match m
left join TournamentEvent te on m.TournamentEventTPId = te.TournamentEventTPId
left join Country tec on te.CountryTPId = tec.CountryTPId
left join TournamentLevel tl on te.TournamentLevelId = tl.TournamentLevelId
left join TournamentType tt on te.TournamentTypeId = tt.TournamentTypeId
left join Surface tes on te.SurfaceId = tes.SurfaceId
left join Player p1 on m.Player1TPId = p1.PlayerTPId
left join Country p1c on p1.CountryTPId = p1c.CountryTPId
left join Plays p1p on p1.PlaysId = p1p.PlaysId
left join Player p2 on m.Player2TPId = p2.PlayerTPId
left join Country p2c on p2.CountryTPId = p2c.CountryTPId
left join Plays p2p on p2.PlaysId = p2p.PlaysId
left join Surface s on m.SurfaceId = s.SurfaceId
left join Round r on m.RoundId = r.RoundId
GO


