using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace BonzoByte.Core.DTOs
{
    public class MatchDetailsDTO
    {
        [BsonId]
        public int                 matchTPId                                                  { get; set; }
        public DateTime          ? dateTime                                                   { get; set; }
        public int               ? tournamentEventTPId                                        { get; set; }
        public int               ? tournamentEventCountryTPId                                 { get; set; }
        public string            ? tournamentEventCountryISO2                                 { get; set; }
        public string            ? tournamentEventCountryISO3                                 { get; set; }
        public string            ? tournamentEventCountryFull                                 { get; set; }
        public int               ? prize                                                      { get; set; }
        public int               ? tournamentEventSurfaceId                                   { get; set; }
        public string            ? tournamentEventSurfaceName                                 { get; set; }
        public DateTime          ? tournamentEventDate                                        { get; set; }
        public string            ? tournamentEventName                                        { get; set; }
        public int               ? tournamentLevelId                                          { get; set; }
        public string            ? tournamentLevelName                                        { get; set; }
        public int               ? tournamentTypeId                                           { get; set; }
        public string            ? tournamentTypeName                                         { get; set; }
        public int               ? player1TPId                                                { get; set; }
        public string            ? player1Seed                                                { get; set; }
        public string            ? player1Name                                                { get; set; }
        public int               ? player1CountryTPId                                         { get; set; }
        public string            ? player1CountryISO2                                         { get; set; }
        public string            ? player1CountryISO3                                         { get; set; }
        public string            ? player1CountryFull                                         { get; set; }
        public int               ? player1PlaysId                                             { get; set; }
        public string            ? player1PlaysName                                           { get; set; }
        public int               ? player2TPId                                                { get; set; }
        public string            ? player2Seed                                                { get; set; }
        public string            ? player2Name                                                { get; set; }
        public int               ? player2CountryTPId                                         { get; set; }
        public string            ? player2CountryISO2                                         { get; set; }
        public string            ? player2CountryISO3                                         { get; set; }
        public string            ? player2CountryFull                                         { get; set; }
        public int               ? player2PlaysId                                             { get; set; }
        public string            ? player2PlaysName                                           { get; set; }
        public string            ? result                                                     { get; set; }
        public string            ? resultDetails                                              { get; set; }
        public double            ? player1Odds                                                { get; set; }
        public double            ? player2Odds                                                { get; set; }
        public double            ? player1Percentage                                          { get; set; }
        public double            ? player2Percentage                                          { get; set; }
        public int               ? matchSurfaceId                                             { get; set; }
        public string            ? matchSurfaceName                                           { get; set; }
        public int               ? roundId                                                    { get; set; }
        public string            ? roundName                                                  { get; set; }
        public double            ? player1TrueSkillMeanM                                      { get; set; }
        public double            ? player1TrueSkillStandardDeviationM                         { get; set; }
        public double            ? player2TrueSkillMeanM                                      { get; set; }
        public double            ? player2TrueSkillStandardDeviationM                         { get; set; }
        public double            ? player1TrueSkillMeanOldM                                   { get; set; }
        public double            ? player1TrueSkillStandardDeviationOldM                      { get; set; }
        public double            ? player2TrueSkillMeanOldM                                   { get; set; }
        public double            ? player2TrueSkillStandardDeviationOldM                      { get; set; }
        public double            ? winProbabilityPlayer1M                                     { get; set; }
        public double            ? winProbabilityPlayer2M                                     { get; set; }
        public double            ? player1TrueSkillMeanSM                                     { get; set; }
        public double            ? player1TrueSkillStandardDeviationSM                        { get; set; }
        public double            ? player2TrueSkillMeanSM                                     { get; set; }
        public double            ? player2TrueSkillStandardDeviationSM                        { get; set; }
        public double            ? player1TrueSkillMeanOldSM                                  { get; set; }
        public double            ? player1TrueSkillStandardDeviationOldSM                     { get; set; }
        public double            ? player2TrueSkillMeanOldSM                                  { get; set; }
        public double            ? player2TrueSkillStandardDeviationOldSM                     { get; set; }
        public double            ? winProbabilityPlayer1SM                                    { get; set; }
        public double            ? winProbabilityPlayer2SM                                    { get; set; }
        public double            ? player1TrueSkillMeanGSM                                    { get; set; }
        public double            ? player1TrueSkillStandardDeviationGSM                       { get; set; }
        public double            ? player2TrueSkillMeanGSM                                    { get; set; }
        public double            ? player2TrueSkillStandardDeviationGSM                       { get; set; }
        public double            ? player1TrueSkillMeanOldGSM                                 { get; set; }
        public double            ? player1TrueSkillStandardDeviationOldGSM                    { get; set; }
        public double            ? player2TrueSkillMeanOldGSM                                 { get; set; }
        public double            ? player2TrueSkillStandardDeviationOldGSM                    { get; set; }
        public double            ? winProbabilityPlayer1GSM                                   { get; set; }
        public double            ? winProbabilityPlayer2GSM                                   { get; set; }
        public double            ? player1TrueSkillMeanMS1                                    { get; set; }
        public double            ? player1TrueSkillStandardDeviationMS1                       { get; set; }
        public double            ? player2TrueSkillMeanMS1                                    { get; set; }
        public double            ? player2TrueSkillStandardDeviationMS1                       { get; set; }
        public double            ? player1TrueSkillMeanOldMS1                                 { get; set; }
        public double            ? player1TrueSkillStandardDeviationOldMS1                    { get; set; }
        public double            ? player2TrueSkillMeanOldMS1                                 { get; set; }
        public double            ? player2TrueSkillStandardDeviationOldMS1                    { get; set; }
        public double            ? winProbabilityPlayer1MS1                                   { get; set; }
        public double            ? winProbabilityPlayer2MS1                                   { get; set; }
        public double            ? player1TrueSkillMeanSMS1                                   { get; set; }
        public double            ? player1TrueSkillStandardDeviationSMS1                      { get; set; }
        public double            ? player2TrueSkillMeanSMS1                                   { get; set; }
        public double            ? player2TrueSkillStandardDeviationSMS1                      { get; set; }
        public double            ? player1TrueSkillMeanOldSMS1                                { get; set; }
        public double            ? player1TrueSkillStandardDeviationOldSMS1                   { get; set; }
        public double            ? player2TrueSkillMeanOldSMS1                                { get; set; }
        public double            ? player2TrueSkillStandardDeviationOldSMS1                   { get; set; }
        public double            ? winProbabilityPlayer1SMS1                                  { get; set; }
        public double            ? winProbabilityPlayer2SMS1                                  { get; set; }
        public double            ? player1TrueSkillMeanGSMS1                                  { get; set; }
        public double            ? player1TrueSkillStandardDeviationGSMS1                     { get; set; }
        public double            ? player2TrueSkillMeanGSMS1                                  { get; set; }
        public double            ? player2TrueSkillStandardDeviationGSMS1                     { get; set; }
        public double            ? player1TrueSkillMeanOldGSMS1                               { get; set; }
        public double            ? player1TrueSkillStandardDeviationOldGSMS1                  { get; set; }
        public double            ? player2TrueSkillMeanOldGSMS1                               { get; set; }
        public double            ? player2TrueSkillStandardDeviationOldGSMS1                  { get; set; }
        public double            ? winProbabilityPlayer1GSMS1                                 { get; set; }
        public double            ? winProbabilityPlayer2GSMS1                                 { get; set; }
        public double            ? player1TrueSkillMeanMS2                                    { get; set; }
        public double            ? player1TrueSkillStandardDeviationMS2                       { get; set; }
        public double            ? player2TrueSkillMeanMS2                                    { get; set; }
        public double            ? player2TrueSkillStandardDeviationMS2                       { get; set; }
        public double            ? player1TrueSkillMeanOldMS2                                 { get; set; }
        public double            ? player1TrueSkillStandardDeviationOldMS2                    { get; set; }
        public double            ? player2TrueSkillMeanOldMS2                                 { get; set; }
        public double            ? player2TrueSkillStandardDeviationOldMS2                    { get; set; }
        public double            ? winProbabilityPlayer1MS2                                   { get; set; }
        public double            ? winProbabilityPlayer2MS2                                   { get; set; }
        public double            ? player1TrueSkillMeanSMS2                                   { get; set; }
        public double            ? player1TrueSkillStandardDeviationSMS2                      { get; set; }
        public double            ? player2TrueSkillMeanSMS2                                   { get; set; }
        public double            ? player2TrueSkillStandardDeviationSMS2                      { get; set; }
        public double            ? player1TrueSkillMeanOldSMS2                                { get; set; }
        public double            ? player1TrueSkillStandardDeviationOldSMS2                   { get; set; }
        public double            ? player2TrueSkillMeanOldSMS2                                { get; set; }
        public double            ? player2TrueSkillStandardDeviationOldSMS2                   { get; set; }
        public double            ? winProbabilityPlayer1SMS2                                  { get; set; }
        public double            ? winProbabilityPlayer2SMS2                                  { get; set; }
        public double            ? player1TrueSkillMeanGSMS2                                  { get; set; }
        public double            ? player1TrueSkillStandardDeviationGSMS2                     { get; set; }
        public double            ? player2TrueSkillMeanGSMS2                                  { get; set; }
        public double            ? player2TrueSkillStandardDeviationGSMS2                     { get; set; }
        public double            ? player1TrueSkillMeanOldGSMS2                               { get; set; }
        public double            ? player1TrueSkillStandardDeviationOldGSMS2                  { get; set; }
        public double            ? player2TrueSkillMeanOldGSMS2                               { get; set; }
        public double            ? player2TrueSkillStandardDeviationOldGSMS2                  { get; set; }
        public double            ? winProbabilityPlayer1GSMS2                                 { get; set; }
        public double            ? winProbabilityPlayer2GSMS2                                 { get; set; }
        public double            ? player1TrueSkillMeanMS3                                    { get; set; }
        public double            ? player1TrueSkillStandardDeviationMS3                       { get; set; }
        public double            ? player2TrueSkillMeanMS3                                    { get; set; }
        public double            ? player2TrueSkillStandardDeviationMS3                       { get; set; }
        public double            ? player1TrueSkillMeanOldMS3                                 { get; set; }
        public double            ? player1TrueSkillStandardDeviationOldMS3                    { get; set; }
        public double            ? player2TrueSkillMeanOldMS3                                 { get; set; }
        public double            ? player2TrueSkillStandardDeviationOldMS3                    { get; set; }
        public double            ? winProbabilityPlayer1MS3                                   { get; set; }
        public double            ? winProbabilityPlayer2MS3                                   { get; set; }
        public double            ? player1TrueSkillMeanSMS3                                   { get; set; }
        public double            ? player1TrueSkillStandardDeviationSMS3                      { get; set; }
        public double            ? player2TrueSkillMeanSMS3                                   { get; set; }
        public double            ? player2TrueSkillStandardDeviationSMS3                      { get; set; }
        public double            ? player1TrueSkillMeanOldSMS3                                { get; set; }
        public double            ? player1TrueSkillStandardDeviationOldSMS3                   { get; set; }
        public double            ? player2TrueSkillMeanOldSMS3                                { get; set; }
        public double            ? player2TrueSkillStandardDeviationOldSMS3                   { get; set; }
        public double            ? winProbabilityPlayer1SMS3                                  { get; set; }
        public double            ? winProbabilityPlayer2SMS3                                  { get; set; }
        public double            ? player1TrueSkillMeanGSMS3                                  { get; set; }
        public double            ? player1TrueSkillStandardDeviationGSMS3                     { get; set; }
        public double            ? player2TrueSkillMeanGSMS3                                  { get; set; }
        public double            ? player2TrueSkillStandardDeviationGSMS3                     { get; set; }
        public double            ? player1TrueSkillMeanOldGSMS3                               { get; set; }
        public double            ? player1TrueSkillStandardDeviationOldGSMS3                  { get; set; }
        public double            ? player2TrueSkillMeanOldGSMS3                               { get; set; }
        public double            ? player2TrueSkillStandardDeviationOldGSMS3                  { get; set; }
        public double            ? winProbabilityPlayer1GSMS3                                 { get; set; }
        public double            ? winProbabilityPlayer2GSMS3                                 { get; set; }
        public double            ? player1TrueSkillMeanMS4                                    { get; set; }
        public double            ? player1TrueSkillStandardDeviationMS4                       { get; set; }
        public double            ? player2TrueSkillMeanMS4                                    { get; set; }
        public double            ? player2TrueSkillStandardDeviationMS4                       { get; set; }
        public double            ? player1TrueSkillMeanOldMS4                                 { get; set; }
        public double            ? player1TrueSkillStandardDeviationOldMS4                    { get; set; }
        public double            ? player2TrueSkillMeanOldMS4                                 { get; set; }
        public double            ? player2TrueSkillStandardDeviationOldMS4                    { get; set; }
        public double            ? winProbabilityPlayer1MS4                                   { get; set; }
        public double            ? winProbabilityPlayer2MS4                                   { get; set; }
        public double            ? player1TrueSkillMeanSMS4                                   { get; set; }
        public double            ? player1TrueSkillStandardDeviationSMS4                      { get; set; }
        public double            ? player2TrueSkillMeanSMS4                                   { get; set; }
        public double            ? player2TrueSkillStandardDeviationSMS4                      { get; set; }
        public double            ? player1TrueSkillMeanOldSMS4                                { get; set; }
        public double            ? player1TrueSkillStandardDeviationOldSMS4                   { get; set; }
        public double            ? player2TrueSkillMeanOldSMS4                                { get; set; }
        public double            ? player2TrueSkillStandardDeviationOldSMS4                   { get; set; }
        public double            ? winProbabilityPlayer1SMS4                                  { get; set; }
        public double            ? winProbabilityPlayer2SMS4                                  { get; set; }
        public double            ? player1TrueSkillMeanGSMS4                                  { get; set; }
        public double            ? player1TrueSkillStandardDeviationGSMS4                     { get; set; }
        public double            ? player2TrueSkillMeanGSMS4                                  { get; set; }
        public double            ? player2TrueSkillStandardDeviationGSMS4                     { get; set; }
        public double            ? player1TrueSkillMeanOldGSMS4                               { get; set; }
        public double            ? player1TrueSkillStandardDeviationOldGSMS4                  { get; set; }
        public double            ? player2TrueSkillMeanOldGSMS4                               { get; set; }
        public double            ? player2TrueSkillStandardDeviationOldGSMS4                  { get; set; }
        public double            ? winProbabilityPlayer1GSMS4                                 { get; set; }
        public double            ? winProbabilityPlayer2GSMS4                                 { get; set; }
        public int               ? player1WinsTotal                                           { get; set; }
        public int               ? player1LossesTotal                                         { get; set; }
        public int               ? player1WinsLastYear                                        { get; set; }
        public int               ? player1LossesLastYear                                      { get; set; }
        public int               ? player1WinsLastMonth                                       { get; set; }
        public int               ? player1LossesLastMonth                                     { get; set; }
        public int               ? player1WinsLastWeek                                        { get; set; }
        public int               ? player1LossesLastWeek                                      { get; set; }
        public int               ? player2WinsTotal                                           { get; set; }
        public int               ? player2LossesTotal                                         { get; set; }
        public int               ? player2WinsLastYear                                        { get; set; }
        public int               ? player2LossesLastYear                                      { get; set; }
        public int               ? player2WinsLastMonth                                       { get; set; }
        public int               ? player2LossesLastMonth                                     { get; set; }
        public int               ? player2WinsLastWeek                                        { get; set; }
        public int               ? player2LossesLastWeek                                      { get; set; }
        public int               ? player1WinsTotalS1                                         { get; set; }
        public int               ? player1LossesTotalS1                                       { get; set; }
        public int               ? player1WinsLastYearS1                                      { get; set; }
        public int               ? player1LossesLastYearS1                                    { get; set; }
        public int               ? player1WinsLastMonthS1                                     { get; set; }
        public int               ? player1LossesLastMonthS1                                   { get; set; }
        public int               ? player1WinsLastWeekS1                                      { get; set; }
        public int               ? player1LossesLastWeekS1                                    { get; set; }
        public int               ? player2WinsTotalS1                                         { get; set; }
        public int               ? player2LossesTotalS1                                       { get; set; }
        public int               ? player2WinsLastYearS1                                      { get; set; }
        public int               ? player2LossesLastYearS1                                    { get; set; }
        public int               ? player2WinsLastMonthS1                                     { get; set; }
        public int               ? player2LossesLastMonthS1                                   { get; set; }
        public int               ? player2WinsLastWeekS1                                      { get; set; }
        public int               ? player2LossesLastWeekS1                                    { get; set; }
        public int               ? player1WinsTotalS2                                         { get; set; }
        public int               ? player1LossesTotalS2                                       { get; set; }
        public int               ? player1WinsLastYearS2                                      { get; set; }
        public int               ? player1LossesLastYearS2                                    { get; set; }
        public int               ? player1WinsLastMonthS2                                     { get; set; }
        public int               ? player1LossesLastMonthS2                                   { get; set; }
        public int               ? player1WinsLastWeekS2                                      { get; set; }
        public int               ? player1LossesLastWeekS2                                    { get; set; }
        public int               ? player2WinsTotalS2                                         { get; set; }
        public int               ? player2LossesTotalS2                                       { get; set; }
        public int               ? player2WinsLastYearS2                                      { get; set; }
        public int               ? player2LossesLastYearS2                                    { get; set; }
        public int               ? player2WinsLastMonthS2                                     { get; set; }
        public int               ? player2LossesLastMonthS2                                   { get; set; }
        public int               ? player2WinsLastWeekS2                                      { get; set; }
        public int               ? player2LossesLastWeekS2                                    { get; set; }
        public int               ? player1WinsTotalS3                                         { get; set; }
        public int               ? player1LossesTotalS3                                       { get; set; }
        public int               ? player1WinsLastYearS3                                      { get; set; }
        public int               ? player1LossesLastYearS3                                    { get; set; }
        public int               ? player1WinsLastMonthS3                                     { get; set; }
        public int               ? player1LossesLastMonthS3                                   { get; set; }
        public int               ? player1WinsLastWeekS3                                      { get; set; }
        public int               ? player1LossesLastWeekS3                                    { get; set; }
        public int               ? player2WinsTotalS3                                         { get; set; }
        public int               ? player2LossesTotalS3                                       { get; set; }
        public int               ? player2WinsLastYearS3                                      { get; set; }
        public int               ? player2LossesLastYearS3                                    { get; set; }
        public int               ? player2WinsLastMonthS3                                     { get; set; }
        public int               ? player2LossesLastMonthS3                                   { get; set; }
        public int               ? player2WinsLastWeekS3                                      { get; set; }
        public int               ? player2LossesLastWeekS3                                    { get; set; }
        public int               ? player1WinsTotalS4                                         { get; set; }
        public int               ? player1LossesTotalS4                                       { get; set; }
        public int               ? player1WinsLastYearS4                                      { get; set; }
        public int               ? player1LossesLastYearS4                                    { get; set; }
        public int               ? player1WinsLastMonthS4                                     { get; set; }
        public int               ? player1LossesLastMonthS4                                   { get; set; }
        public int               ? player1WinsLastWeekS4                                      { get; set; }
        public int               ? player1LossesLastWeekS4                                    { get; set; }
        public int               ? player2WinsTotalS4                                         { get; set; }
        public int               ? player2LossesTotalS4                                       { get; set; }
        public int               ? player2WinsLastYearS4                                      { get; set; }
        public int               ? player2LossesLastYearS4                                    { get; set; }
        public int               ? player2WinsLastMonthS4                                     { get; set; }
        public int               ? player2LossesLastMonthS4                                   { get; set; }
        public int               ? player2WinsLastWeekS4                                      { get; set; }
        public int               ? player2LossesLastWeekS4                                    { get; set; }
        public int               ? player1WinsSetsTotal                                       { get; set; }
        public int               ? player1LossesSetsTotal                                     { get; set; }
        public int               ? player1WinsSetsLastYear                                    { get; set; }
        public int               ? player1LossesSetsLastYear                                  { get; set; }
        public int               ? player1WinsSetsLastMonth                                   { get; set; }
        public int               ? player1LossesSetsLastMonth                                 { get; set; }
        public int               ? player1WinsSetsLastWeek                                    { get; set; }
        public int               ? player1LossesSetsLastWeek                                  { get; set; }
        public int               ? player2WinsSetsTotal                                       { get; set; }
        public int               ? player2LossesSetsTotal                                     { get; set; }
        public int               ? player2WinsSetsLastYear                                    { get; set; }
        public int               ? player2LossesSetsLastYear                                  { get; set; }
        public int               ? player2WinsSetsLastMonth                                   { get; set; }
        public int               ? player2LossesSetsLastMonth                                 { get; set; }
        public int               ? player2WinsSetsLastWeek                                    { get; set; }
        public int               ? player2LossesSetsLastWeek                                  { get; set; }
        public int               ? player1WinsSetsTotalS1                                     { get; set; }
        public int               ? player1LossesSetsTotalS1                                   { get; set; }
        public int               ? player1WinsSetsLastYearS1                                  { get; set; }
        public int               ? player1LossesSetsLastYearS1                                { get; set; }
        public int               ? player1WinsSetsLastMonthS1                                 { get; set; }
        public int               ? player1LossesSetsLastMonthS1                               { get; set; }
        public int               ? player1WinsSetsLastWeekS1                                  { get; set; }
        public int               ? player1LossesSetsLastWeekS1                                { get; set; }
        public int               ? player2WinsSetsTotalS1                                     { get; set; }
        public int               ? player2LossesSetsTotalS1                                   { get; set; }
        public int               ? player2WinsSetsLastYearS1                                  { get; set; }
        public int               ? player2LossesSetsLastYearS1                                { get; set; }
        public int               ? player2WinsSetsLastMonthS1                                 { get; set; }
        public int               ? player2LossesSetsLastMonthS1                               { get; set; }
        public int               ? player2WinsSetsLastWeekS1                                  { get; set; }
        public int               ? player2LossesSetsLastWeekS1                                { get; set; }
        public int               ? player1WinsSetsTotalS2                                     { get; set; }
        public int               ? player1LossesSetsTotalS2                                   { get; set; }
        public int               ? player1WinsSetsLastYearS2                                  { get; set; }
        public int               ? player1LossesSetsLastYearS2                                { get; set; }
        public int               ? player1WinsSetsLastMonthS2                                 { get; set; }
        public int               ? player1LossesSetsLastMonthS2                               { get; set; }
        public int               ? player1WinsSetsLastWeekS2                                  { get; set; }
        public int               ? player1LossesSetsLastWeekS2                                { get; set; }
        public int               ? player2WinsSetsTotalS2                                     { get; set; }
        public int               ? player2LossesSetsTotalS2                                   { get; set; }
        public int               ? player2WinsSetsLastYearS2                                  { get; set; }
        public int               ? player2LossesSetsLastYearS2                                { get; set; }
        public int               ? player2WinsSetsLastMonthS2                                 { get; set; }
        public int               ? player2LossesSetsLastMonthS2                               { get; set; }
        public int               ? player2WinsSetsLastWeekS2                                  { get; set; }
        public int               ? player2LossesSetsLastWeekS2                                { get; set; }
        public int               ? player1WinsSetsTotalS3                                     { get; set; }
        public int               ? player1LossesSetsTotalS3                                   { get; set; }
        public int               ? player1WinsSetsLastYearS3                                  { get; set; }
        public int               ? player1LossesSetsLastYearS3                                { get; set; }
        public int               ? player1WinsSetsLastMonthS3                                 { get; set; }
        public int               ? player1LossesSetsLastMonthS3                               { get; set; }
        public int               ? player1WinsSetsLastWeekS3                                  { get; set; }
        public int               ? player1LossesSetsLastWeekS3                                { get; set; }
        public int               ? player2WinsSetsTotalS3                                     { get; set; }
        public int               ? player2LossesSetsTotalS3                                   { get; set; }
        public int               ? player2WinsSetsLastYearS3                                  { get; set; }
        public int               ? player2LossesSetsLastYearS3                                { get; set; }
        public int               ? player2WinsSetsLastMonthS3                                 { get; set; }
        public int               ? player2LossesSetsLastMonthS3                               { get; set; }
        public int               ? player2WinsSetsLastWeekS3                                  { get; set; }
        public int               ? player2LossesSetsLastWeekS3                                { get; set; }
        public int               ? player1WinsSetsTotalS4                                     { get; set; }
        public int               ? player1LossesSetsTotalS4                                   { get; set; }
        public int               ? player1WinsSetsLastYearS4                                  { get; set; }
        public int               ? player1LossesSetsLastYearS4                                { get; set; }
        public int               ? player1WinsSetsLastMonthS4                                 { get; set; }
        public int               ? player1LossesSetsLastMonthS4                               { get; set; }
        public int               ? player1WinsSetsLastWeekS4                                  { get; set; }
        public int               ? player1LossesSetsLastWeekS4                                { get; set; }
        public int               ? player2WinsSetsTotalS4                                     { get; set; }
        public int               ? player2LossesSetsTotalS4                                   { get; set; }
        public int               ? player2WinsSetsLastYearS4                                  { get; set; }
        public int               ? player2LossesSetsLastYearS4                                { get; set; }
        public int               ? player2WinsSetsLastMonthS4                                 { get; set; }
        public int               ? player2LossesSetsLastMonthS4                               { get; set; }
        public int               ? player2WinsSetsLastWeekS4                                  { get; set; }
        public int               ? player2LossesSetsLastWeekS4                                { get; set; }
        public int               ? player1WinsGamesTotal                                      { get; set; }
        public int               ? player1LossesGamesTotal                                    { get; set; }
        public int               ? player1WinsGamesLastYear                                   { get; set; }
        public int               ? player1LossesGamesLastYear                                 { get; set; }
        public int               ? player1WinsGamesLastMonth                                  { get; set; }
        public int               ? player1LossesGamesLastMonth                                { get; set; }
        public int               ? player1WinsGamesLastWeek                                   { get; set; }
        public int               ? player1LossesGamesLastWeek                                 { get; set; }
        public int               ? player2WinsGamesTotal                                      { get; set; }
        public int               ? player2LossesGamesTotal                                    { get; set; }
        public int               ? player2WinsGamesLastYear                                   { get; set; }
        public int               ? player2LossesGamesLastYear                                 { get; set; }
        public int               ? player2WinsGamesLastMonth                                  { get; set; }
        public int               ? player2LossesGamesLastMonth                                { get; set; }
        public int               ? player2WinsGamesLastWeek                                   { get; set; }
        public int               ? player2LossesGamesLastWeek                                 { get; set; }
        public int               ? player1WinsGamesTotalS1                                    { get; set; }
        public int               ? player1LossesGamesTotalS1                                  { get; set; }
        public int               ? player1WinsGamesLastYearS1                                 { get; set; }
        public int               ? player1LossesGamesLastYearS1                               { get; set; }
        public int               ? player1WinsGamesLastMonthS1                                { get; set; }
        public int               ? player1LossesGamesLastMonthS1                              { get; set; }
        public int               ? player1WinsGamesLastWeekS1                                 { get; set; }
        public int               ? player1LossesGamesLastWeekS1                               { get; set; }
        public int               ? player2WinsGamesTotalS1                                    { get; set; }
        public int               ? player2LossesGamesTotalS1                                  { get; set; }
        public int               ? player2WinsGamesLastYearS1                                 { get; set; }
        public int               ? player2LossesGamesLastYearS1                               { get; set; }
        public int               ? player2WinsGamesLastMonthS1                                { get; set; }
        public int               ? player2LossesGamesLastMonthS1                              { get; set; }
        public int               ? player2WinsGamesLastWeekS1                                 { get; set; }
        public int               ? player2LossesGamesLastWeekS1                               { get; set; }
        public int               ? player1WinsGamesTotalS2                                    { get; set; }
        public int               ? player1LossesGamesTotalS2                                  { get; set; }
        public int               ? player1WinsGamesLastYearS2                                 { get; set; }
        public int               ? player1LossesGamesLastYearS2                               { get; set; }
        public int               ? player1WinsGamesLastMonthS2                                { get; set; }
        public int               ? player1LossesGamesLastMonthS2                              { get; set; }
        public int               ? player1WinsGamesLastWeekS2                                 { get; set; }
        public int               ? player1LossesGamesLastWeekS2                               { get; set; }
        public int               ? player2WinsGamesTotalS2                                    { get; set; }
        public int               ? player2LossesGamesTotalS2                                  { get; set; }
        public int               ? player2WinsGamesLastYearS2                                 { get; set; }
        public int               ? player2LossesGamesLastYearS2                               { get; set; }
        public int               ? player2WinsGamesLastMonthS2                                { get; set; }
        public int               ? player2LossesGamesLastMonthS2                              { get; set; }
        public int               ? player2WinsGamesLastWeekS2                                 { get; set; }
        public int               ? player2LossesGamesLastWeekS2                               { get; set; }
        public int               ? player1WinsGamesTotalS3                                    { get; set; }
        public int               ? player1LossesGamesTotalS3                                  { get; set; }
        public int               ? player1WinsGamesLastYearS3                                 { get; set; }
        public int               ? player1LossesGamesLastYearS3                               { get; set; }
        public int               ? player1WinsGamesLastMonthS3                                { get; set; }
        public int               ? player1LossesGamesLastMonthS3                              { get; set; }
        public int               ? player1WinsGamesLastWeekS3                                 { get; set; }
        public int               ? player1LossesGamesLastWeekS3                               { get; set; }
        public int               ? player2WinsGamesTotalS3                                    { get; set; }
        public int               ? player2LossesGamesTotalS3                                  { get; set; }
        public int               ? player2WinsGamesLastYearS3                                 { get; set; }
        public int               ? player2LossesGamesLastYearS3                               { get; set; }
        public int               ? player2WinsGamesLastMonthS3                                { get; set; }
        public int               ? player2LossesGamesLastMonthS3                              { get; set; }
        public int               ? player2WinsGamesLastWeekS3                                 { get; set; }
        public int               ? player2LossesGamesLastWeekS3                               { get; set; }
        public int               ? player1WinsGamesTotalS4                                    { get; set; }
        public int               ? player1LossesGamesTotalS4                                  { get; set; }
        public int               ? player1WinsGamesLastYearS4                                 { get; set; }
        public int               ? player1LossesGamesLastYearS4                               { get; set; }
        public int               ? player1WinsGamesLastMonthS4                                { get; set; }
        public int               ? player1LossesGamesLastMonthS4                              { get; set; }
        public int               ? player1WinsGamesLastWeekS4                                 { get; set; }
        public int               ? player1LossesGamesLastWeekS4                               { get; set; }
        public int               ? player2WinsGamesTotalS4                                    { get; set; }
        public int               ? player2LossesGamesTotalS4                                  { get; set; }
        public int               ? player2WinsGamesLastYearS4                                 { get; set; }
        public int               ? player2LossesGamesLastYearS4                               { get; set; }
        public int               ? player2WinsGamesLastMonthS4                                { get; set; }
        public int               ? player2LossesGamesLastMonthS4                              { get; set; }
        public int               ? player2WinsGamesLastWeekS4                                 { get; set; }
        public int               ? player2LossesGamesLastWeekS4                               { get; set; }
        public int               ? player1DaysSinceLastWin                                    { get; set; }
        public int               ? player2DaysSinceLastWin                                    { get; set; }
        public int               ? player1DaysSinceLastWinS1                                  { get; set; }
        public int               ? player2DaysSinceLastWinS1                                  { get; set; }
        public int               ? player1DaysSinceLastWinS2                                  { get; set; }
        public int               ? player2DaysSinceLastWinS2                                  { get; set; }
        public int               ? player1DaysSinceLastWinS3                                  { get; set; }
        public int               ? player2DaysSinceLastWinS3                                  { get; set; }
        public int               ? player1DaysSinceLastWinS4                                  { get; set; }
        public int               ? player2DaysSinceLastWinS4                                  { get; set; }
        public int               ? player1DaysSinceLastLoss                                   { get; set; }
        public int               ? player2DaysSinceLastLoss                                   { get; set; }
        public int               ? player1DaysSinceLastLossS1                                 { get; set; }
        public int               ? player2DaysSinceLastLossS1                                 { get; set; }
        public int               ? player1DaysSinceLastLossS2                                 { get; set; }
        public int               ? player2DaysSinceLastLossS2                                 { get; set; }
        public int               ? player1DaysSinceLastLossS3                                 { get; set; }
        public int               ? player2DaysSinceLastLossS3                                 { get; set; }
        public int               ? player1DaysSinceLastLossS4                                 { get; set; }
        public int               ? player2DaysSinceLastLossS4                                 { get; set; }
        public int               ? player1TotalWinsAsFavourite                                { get; set; }
        public int               ? player2TotalWinsAsFavourite                                { get; set; }
        public int               ? player1TotalWinsAsUnderdog                                 { get; set; }
        public int               ? player2TotalWinsAsUnderdog                                 { get; set; }
        public int               ? player1TotalLossesAsFavourite                              { get; set; }
        public int               ? player2TotalLossesAsFavourite                              { get; set; }
        public int               ? player1TotalLossesAsUnderdog                               { get; set; }
        public int               ? player2TotalLossesAsUnderdog                               { get; set; }
        public double            ? player1AverageWinningProbabilityAtWonAsFavourite           { get; set; }
        public double            ? player2AverageWinningProbabilityAtWonAsFavourite           { get; set; }
        public double            ? player1AverageWinningProbabilityAtWonAsUnderdog            { get; set; }
        public double            ? player2AverageWinningProbabilityAtWonAsUnderdog            { get; set; }
        public double            ? player1AverageWinningProbabilityAtLossAsFavourite          { get; set; }
        public double            ? player2AverageWinningProbabilityAtLossAsFavourite          { get; set; }
        public double            ? player1AverageWinningProbabilityAtLossAsUnderdog           { get; set; }
        public double            ? player2AverageWinningProbabilityAtLossAsUnderdog           { get; set; }
        public int               ? player1TotalWinsAsFavouriteLastYear                        { get; set; }
        public int               ? player2TotalWinsAsFavouriteLastYear                        { get; set; }
        public int               ? player1TotalWinsAsUnderdogLastYear                         { get; set; }
        public int               ? player2TotalWinsAsUnderdogLastYear                         { get; set; }
        public int               ? player1TotalLossesAsFavouriteLastYear                      { get; set; }
        public int               ? player2TotalLossesAsFavouriteLastYear                      { get; set; }
        public int               ? player1TotalLossesAsUnderdogLastYear                       { get; set; }
        public int               ? player2TotalLossesAsUnderdogLastYear                       { get; set; }
        public double            ? player1AverageWinningProbabilityAtWonAsFavouriteLastYear   { get; set; }
        public double            ? player2AverageWinningProbabilityAtWonAsFavouriteLastYear   { get; set; }
        public double            ? player1AverageWinningProbabilityAtWonAsUnderdogLastYear    { get; set; }
        public double            ? player2AverageWinningProbabilityAtWonAsUnderdogLastYear    { get; set; }
        public double            ? player1AverageWinningProbabilityAtLossAsFavouriteLastYear  { get; set; }
        public double            ? player2AverageWinningProbabilityAtLossAsFavouriteLastYear  { get; set; }
        public double            ? player1AverageWinningProbabilityAtLossAsUnderdogLastYear   { get; set; }
        public double            ? player2AverageWinningProbabilityAtLossAsUnderdogLastYear   { get; set; }
        public int               ? player1TotalWinsAsFavouriteLastMonth                       { get; set; }
        public int               ? player2TotalWinsAsFavouriteLastMonth                       { get; set; }
        public int               ? player1TotalWinsAsUnderdogLastMonth                        { get; set; }
        public int               ? player2TotalWinsAsUnderdogLastMonth                        { get; set; }
        public int               ? player1TotalLossesAsFavouriteLastMonth                     { get; set; }
        public int               ? player2TotalLossesAsFavouriteLastMonth                     { get; set; }
        public int               ? player1TotalLossesAsUnderdogLastMonth                      { get; set; }
        public int               ? player2TotalLossesAsUnderdogLastMonth                      { get; set; }
        public double            ? player1AverageWinningProbabilityAtWonAsFavouriteLastMonth  { get; set; }
        public double            ? player2AverageWinningProbabilityAtWonAsFavouriteLastMonth  { get; set; }
        public double            ? player1AverageWinningProbabilityAtWonAsUnderdogLastMonth   { get; set; }
        public double            ? player2AverageWinningProbabilityAtWonAsUnderdogLastMonth   { get; set; }
        public double            ? player1AverageWinningProbabilityAtLossAsFavouriteLastMonth { get; set; }
        public double            ? player2AverageWinningProbabilityAtLossAsFavouriteLastMonth { get; set; }
        public double            ? player1AverageWinningProbabilityAtLossAsUnderdogLastMonth  { get; set; }
        public double            ? player2AverageWinningProbabilityAtLossAsUnderdogLastMonth  { get; set; }
        public int               ? player1TotalWinsAsFavouriteLastWeek                        { get; set; }
        public int               ? player2TotalWinsAsFavouriteLastWeek                        { get; set; }
        public int               ? player1TotalWinsAsUnderdogLastWeek                         { get; set; }
        public int               ? player2TotalWinsAsUnderdogLastWeek                         { get; set; }
        public int               ? player1TotalLossesAsFavouriteLastWeek                      { get; set; }
        public int               ? player2TotalLossesAsFavouriteLastWeek                      { get; set; }
        public int               ? player1TotalLossesAsUnderdogLastWeek                       { get; set; }
        public int               ? player2TotalLossesAsUnderdogLastWeek                       { get; set; }
        public double            ? player1AverageWinningProbabilityAtWonAsFavouriteLastWeek   { get; set; }
        public double            ? player2AverageWinningProbabilityAtWonAsFavouriteLastWeek   { get; set; }
        public double            ? player1AverageWinningProbabilityAtWonAsUnderdogLastWeek    { get; set; }
        public double            ? player2AverageWinningProbabilityAtWonAsUnderdogLastWeek    { get; set; }
        public double            ? player1AverageWinningProbabilityAtLossAsFavouriteLastWeek  { get; set; }
        public double            ? player2AverageWinningProbabilityAtLossAsFavouriteLastWeek  { get; set; }
        public double            ? player1AverageWinningProbabilityAtLossAsUnderdogLastWeek   { get; set; }
        public double            ? player2AverageWinningProbabilityAtLossAsUnderdogLastWeek   { get; set; }
        public int               ? player1H2H                                                 { get; set; }
        public int               ? player2H2H                                                 { get; set; }
        public int               ? player1H2HOld                                              { get; set; }
        public int               ? player2H2HOld                                              { get; set; }
        public double            ? player1H2HTrueSkillMeanM                                   { get; set; }
        public double            ? player1H2HTrueSkillStandardDeviationM                      { get; set; }
        public double            ? player2H2HTrueSkillMeanM                                   { get; set; }
        public double            ? player2H2HTrueSkillStandardDeviationM                      { get; set; }
        public double            ? player1H2HTrueSkillMeanOldM                                { get; set; }
        public double            ? player1H2HTrueSkillStandardDeviationOldM                   { get; set; }
        public double            ? player2H2HTrueSkillMeanOldM                                { get; set; }
        public double            ? player2H2HTrueSkillStandardDeviationOldM                   { get; set; }
        public double            ? winProbabilityPlayer1H2HM                                  { get; set; }
        public double            ? winProbabilityPlayer2H2HM                                  { get; set; }
        public double            ? player1H2HTrueSkillMeanSM                                  { get; set; }
        public double            ? player1H2HTrueSkillStandardDeviationSM                     { get; set; }
        public double            ? player2H2HTrueSkillMeanSM                                  { get; set; }
        public double            ? player2H2HTrueSkillStandardDeviationSM                     { get; set; }
        public double            ? player1H2HTrueSkillMeanOldSM                               { get; set; }
        public double            ? player1H2HTrueSkillStandardDeviationOldSM                  { get; set; }
        public double            ? player2H2HTrueSkillMeanOldSM                               { get; set; }
        public double            ? player2H2HTrueSkillStandardDeviationOldSM                  { get; set; }
        public double            ? winProbabilityPlayer1H2HSM                                 { get; set; }
        public double            ? winProbabilityPlayer2H2HSM                                 { get; set; }
        public double            ? player1H2HTrueSkillMeanGSM                                 { get; set; }
        public double            ? player1H2HTrueSkillStandardDeviationGSM                    { get; set; }
        public double            ? player2H2HTrueSkillMeanGSM                                 { get; set; }
        public double            ? player2H2HTrueSkillStandardDeviationGSM                    { get; set; }
        public double            ? player1H2HTrueSkillMeanOldGSM                              { get; set; }
        public double            ? player1H2HTrueSkillStandardDeviationOldGSM                 { get; set; }
        public double            ? player2H2HTrueSkillMeanOldGSM                              { get; set; }
        public double            ? player2H2HTrueSkillStandardDeviationOldGSM                 { get; set; }
        public double            ? winProbabilityPlayer1H2HGSM                                { get; set; }
        public double            ? winProbabilityPlayer2H2HGSM                                { get; set; }
        public int               ? player1H2HS1                                               { get; set; }
        public int               ? player2H2HS1                                               { get; set; }
        public int               ? player1H2HOldS1                                            { get; set; }
        public int               ? player2H2HOldS1                                            { get; set; }
        public double            ? player1H2HTrueSkillMeanMS1                                 { get; set; }
        public double            ? player1H2HTrueSkillStandardDeviationMS1                    { get; set; }
        public double            ? player2H2HTrueSkillMeanMS1                                 { get; set; }
        public double            ? player2H2HTrueSkillStandardDeviationMS1                    { get; set; }
        public double            ? player1H2HTrueSkillMeanOldMS1                              { get; set; }
        public double            ? player1H2HTrueSkillStandardDeviationOldMS1                 { get; set; }
        public double            ? player2H2HTrueSkillMeanOldMS1                              { get; set; }
        public double            ? player2H2HTrueSkillStandardDeviationOldMS1                 { get; set; }
        public double            ? winProbabilityPlayer1H2HMS1                                { get; set; }
        public double            ? winProbabilityPlayer2H2HMS1                                { get; set; }
        public double            ? player1H2HTrueSkillMeanSMS1                                { get; set; }
        public double            ? player1H2HTrueSkillStandardDeviationSMS1                   { get; set; }
        public double            ? player2H2HTrueSkillMeanSMS1                                { get; set; }
        public double            ? player2H2HTrueSkillStandardDeviationSMS1                   { get; set; }
        public double            ? player1H2HTrueSkillMeanOldSMS1                             { get; set; }
        public double            ? player1H2HTrueSkillStandardDeviationOldSMS1                { get; set; }
        public double            ? player2H2HTrueSkillMeanOldSMS1                             { get; set; }
        public double            ? player2H2HTrueSkillStandardDeviationOldSMS1                { get; set; }
        public double            ? winProbabilityPlayer1H2HSMS1                               { get; set; }
        public double            ? winProbabilityPlayer2H2HSMS1                               { get; set; }
        public double            ? player1H2HTrueSkillMeanGSMS1                               { get; set; }
        public double            ? player1H2HTrueSkillStandardDeviationGSMS1                  { get; set; }
        public double            ? player2H2HTrueSkillMeanGSMS1                               { get; set; }
        public double            ? player2H2HTrueSkillStandardDeviationGSMS1                  { get; set; }
        public double            ? player1H2HTrueSkillMeanOldGSMS1                            { get; set; }
        public double            ? player1H2HTrueSkillStandardDeviationOldGSMS1               { get; set; }
        public double            ? player2H2HTrueSkillMeanOldGSMS1                            { get; set; }
        public double            ? player2H2HTrueSkillStandardDeviationOldGSMS1               { get; set; }
        public double            ? winProbabilityPlayer1H2HGSMS1                              { get; set; }
        public double            ? winProbabilityPlayer2H2HGSMS1                              { get; set; }
        public int               ? player1H2HS2                                               { get; set; }
        public int               ? player2H2HS2                                               { get; set; }
        public int               ? player1H2HOldS2                                            { get; set; }
        public int               ? player2H2HOldS2                                            { get; set; }
        public double            ? player1H2HTrueSkillMeanMS2                                 { get; set; }
        public double            ? player1H2HTrueSkillStandardDeviationMS2                    { get; set; }
        public double            ? player2H2HTrueSkillMeanMS2                                 { get; set; }
        public double            ? player2H2HTrueSkillStandardDeviationMS2                    { get; set; }
        public double            ? player1H2HTrueSkillMeanOldMS2                              { get; set; }
        public double            ? player1H2HTrueSkillStandardDeviationOldMS2                 { get; set; }
        public double            ? player2H2HTrueSkillMeanOldMS2                              { get; set; }
        public double            ? player2H2HTrueSkillStandardDeviationOldMS2                 { get; set; }
        public double            ? winProbabilityPlayer1H2HMS2                                { get; set; }
        public double            ? winProbabilityPlayer2H2HMS2                                { get; set; }
        public double            ? player1H2HTrueSkillMeanSMS2                                { get; set; }
        public double            ? player1H2HTrueSkillStandardDeviationSMS2                   { get; set; }
        public double            ? player2H2HTrueSkillMeanSMS2                                { get; set; }
        public double            ? player2H2HTrueSkillStandardDeviationSMS2                   { get; set; }
        public double            ? player1H2HTrueSkillMeanOldSMS2                             { get; set; }
        public double            ? player1H2HTrueSkillStandardDeviationOldSMS2                { get; set; }
        public double            ? player2H2HTrueSkillMeanOldSMS2                             { get; set; }
        public double            ? player2H2HTrueSkillStandardDeviationOldSMS2                { get; set; }
        public double            ? winProbabilityPlayer1H2HSMS2                               { get; set; }
        public double            ? winProbabilityPlayer2H2HSMS2                               { get; set; }
        public double            ? player1H2HTrueSkillMeanGSMS2                               { get; set; }
        public double            ? player1H2HTrueSkillStandardDeviationGSMS2                  { get; set; }
        public double            ? player2H2HTrueSkillMeanGSMS2                               { get; set; }
        public double            ? player2H2HTrueSkillStandardDeviationGSMS2                  { get; set; }
        public double            ? player1H2HTrueSkillMeanOldGSMS2                            { get; set; }
        public double            ? player1H2HTrueSkillStandardDeviationOldGSMS2               { get; set; }
        public double            ? player2H2HTrueSkillMeanOldGSMS2                            { get; set; }
        public double            ? player2H2HTrueSkillStandardDeviationOldGSMS2               { get; set; }
        public double            ? winProbabilityPlayer1H2HGSMS2                              { get; set; }
        public double            ? winProbabilityPlayer2H2HGSMS2                              { get; set; }
        public int               ? player1H2HS3                                               { get; set; }
        public int               ? player2H2HS3                                               { get; set; }
        public int               ? player1H2HOldS3                                            { get; set; }
        public int               ? player2H2HOldS3                                            { get; set; }
        public double            ? player1H2HTrueSkillMeanMS3                                 { get; set; }
        public double            ? player1H2HTrueSkillStandardDeviationMS3                    { get; set; }
        public double            ? player2H2HTrueSkillMeanMS3                                 { get; set; }
        public double            ? player2H2HTrueSkillStandardDeviationMS3                    { get; set; }
        public double            ? player1H2HTrueSkillMeanOldMS3                              { get; set; }
        public double            ? player1H2HTrueSkillStandardDeviationOldMS3                 { get; set; }
        public double            ? player2H2HTrueSkillMeanOldMS3                              { get; set; }
        public double            ? player2H2HTrueSkillStandardDeviationOldMS3                 { get; set; }
        public double            ? winProbabilityPlayer1H2HMS3                                { get; set; }
        public double            ? winProbabilityPlayer2H2HMS3                                { get; set; }
        public double            ? player1H2HTrueSkillMeanSMS3                                { get; set; }
        public double            ? player1H2HTrueSkillStandardDeviationSMS3                   { get; set; }
        public double            ? player2H2HTrueSkillMeanSMS3                                { get; set; }
        public double            ? player2H2HTrueSkillStandardDeviationSMS3                   { get; set; }
        public double            ? player1H2HTrueSkillMeanOldSMS3                             { get; set; }
        public double            ? player1H2HTrueSkillStandardDeviationOldSMS3                { get; set; }
        public double            ? player2H2HTrueSkillMeanOldSMS3                             { get; set; }
        public double            ? player2H2HTrueSkillStandardDeviationOldSMS3                { get; set; }
        public double            ? winProbabilityPlayer1H2HSMS3                               { get; set; }
        public double            ? winProbabilityPlayer2H2HSMS3                               { get; set; }
        public double            ? player1H2HTrueSkillMeanGSMS3                               { get; set; }
        public double            ? player1H2HTrueSkillStandardDeviationGSMS3                  { get; set; }
        public double            ? player2H2HTrueSkillMeanGSMS3                               { get; set; }
        public double            ? player2H2HTrueSkillStandardDeviationGSMS3                  { get; set; }
        public double            ? player1H2HTrueSkillMeanOldGSMS3                            { get; set; }
        public double            ? player1H2HTrueSkillStandardDeviationOldGSMS3               { get; set; }
        public double            ? player2H2HTrueSkillMeanOldGSMS3                            { get; set; }
        public double            ? player2H2HTrueSkillStandardDeviationOldGSMS3               { get; set; }
        public double            ? winProbabilityPlayer1H2HGSMS3                              { get; set; }
        public double            ? winProbabilityPlayer2H2HGSMS3                              { get; set; }
        public int               ? player1H2HS4                                               { get; set; }
        public int               ? player2H2HS4                                               { get; set; }
        public int               ? player1H2HOldS4                                            { get; set; }
        public int               ? player2H2HOldS4                                            { get; set; }
        public double            ? player1H2HTrueSkillMeanMS4                                 { get; set; }
        public double            ? player1H2HTrueSkillStandardDeviationMS4                    { get; set; }
        public double            ? player2H2HTrueSkillMeanMS4                                 { get; set; }
        public double            ? player2H2HTrueSkillStandardDeviationMS4                    { get; set; }
        public double            ? player1H2HTrueSkillMeanOldMS4                              { get; set; }
        public double            ? player1H2HTrueSkillStandardDeviationOldMS4                 { get; set; }
        public double            ? player2H2HTrueSkillMeanOldMS4                              { get; set; }
        public double            ? player2H2HTrueSkillStandardDeviationOldMS4                 { get; set; }
        public double            ? winProbabilityPlayer1H2HMS4                                { get; set; }
        public double            ? winProbabilityPlayer2H2HMS4                                { get; set; }
        public double            ? player1H2HTrueSkillMeanSMS4                                { get; set; }
        public double            ? player1H2HTrueSkillStandardDeviationSMS4                   { get; set; }
        public double            ? player2H2HTrueSkillMeanSMS4                                { get; set; }
        public double            ? player2H2HTrueSkillStandardDeviationSMS4                   { get; set; }
        public double            ? player1H2HTrueSkillMeanOldSMS4                             { get; set; }
        public double            ? player1H2HTrueSkillStandardDeviationOldSMS4                { get; set; }
        public double            ? player2H2HTrueSkillMeanOldSMS4                             { get; set; }
        public double            ? player2H2HTrueSkillStandardDeviationOldSMS4                { get; set; }
        public double            ? winProbabilityPlayer1H2HSMS4                               { get; set; }
        public double            ? winProbabilityPlayer2H2HSMS4                               { get; set; }
        public double            ? player1H2HTrueSkillMeanGSMS4                               { get; set; }
        public double            ? player1H2HTrueSkillStandardDeviationGSMS4                  { get; set; }
        public double            ? player2H2HTrueSkillMeanGSMS4                               { get; set; }
        public double            ? player2H2HTrueSkillStandardDeviationGSMS4                  { get; set; }
        public double            ? player1H2HTrueSkillMeanOldGSMS4                            { get; set; }
        public double            ? player1H2HTrueSkillStandardDeviationOldGSMS4               { get; set; }
        public double            ? player2H2HTrueSkillMeanOldGSMS4                            { get; set; }
        public double            ? player2H2HTrueSkillStandardDeviationOldGSMS4               { get; set; }
        public double            ? winProbabilityPlayer1H2HGSMS4                              { get; set; }
        public double            ? winProbabilityPlayer2H2HGSMS4                              { get; set; }
        public int               ? player1Streak                                              { get; set; }
        public int               ? player2Streak                                              { get; set; }
        public int               ? player1StreakS1                                            { get; set; }
        public int               ? player2StreakS1                                            { get; set; }
        public int               ? player1StreakS2                                            { get; set; }
        public int               ? player2StreakS2                                            { get; set; }
        public int               ? player1StreakS3                                            { get; set; }
        public int               ? player2StreakS3                                            { get; set; }
        public int               ? player1StreakS4                                            { get; set; }
        public int               ? player2StreakS4                                            { get; set; }
        public int               ? p1SetsWon                                                  { get; set; }
        public int               ? p2SetsWon                                                  { get; set; }
        public int               ? p1GamesWon                                                 { get; set; }
        public int               ? p2GamesWon                                                 { get; set; }
        public int               ? p1SetsLoss                                                 { get; set; }
        public int               ? p2SetsLoss                                                 { get; set; }
        public int               ? p1GamesLoss                                                { get; set; }
        public int               ? p2GamesLoss                                                { get; set; }
        public double            ? winProbabilityPlayer1NN                                    { get; set; }
        public double            ? winProbabilityPlayer2NN                                    { get; set; }
        public double            ? bestP1                                                     { get; set; }
        public double            ? bestP2                                                     { get; set; }
        public double            ? valueMarginPlayer1                                         { get; set; }
        public double            ? valueMarginPlayer2                                         { get; set; }
        public int               ? who2Bet                                                    { get; set; }
        public bool              ? isFinished                                                 { get; set; }
        [BsonIgnoreIfNull]
        [BsonElement("odds")]
        public MatchOddsBundleDTO? Odds                                                       { get; set; }
    }
}