namespace BonzoByte.Core.DTOs
{
    public class PlayerDetailsDTO : PlayerMongoDTO
    {
        public double  ? trueSkillMeanM                                      { get; set; }
        public double  ? trueSkillStandardDeviationM                         { get; set; }
        public double  ? trueSkillMeanSM                                     { get; set; }
        public double  ? trueSkillStandardDeviationSM                        { get; set; }
        public double  ? trueSkillMeanGSM                                    { get; set; }
        public double  ? trueSkillStandardDeviationGSM                       { get; set; }
        public double  ? trueSkillMeanMS1                                    { get; set; }
        public double  ? trueSkillStandardDeviationMS1                       { get; set; }
        public double  ? trueSkillMeanSMS1                                   { get; set; }
        public double  ? trueSkillStandardDeviationSMS1                      { get; set; }
        public double  ? trueSkillMeanGSMS1                                  { get; set; }
        public double  ? trueSkillStandardDeviationGSMS1                     { get; set; }
        public double  ? trueSkillMeanMS2                                    { get; set; }
        public double  ? trueSkillStandardDeviationMS2                       { get; set; }
        public double  ? trueSkillMeanSMS2                                   { get; set; }
        public double  ? trueSkillStandardDeviationSMS2                      { get; set; }
        public double  ? trueSkillMeanGSMS2                                  { get; set; }
        public double  ? trueSkillStandardDeviationGSMS2                     { get; set; }
        public double  ? trueSkillMeanMS3                                    { get; set; }
        public double  ? trueSkillStandardDeviationMS3                       { get; set; }
        public double  ? trueSkillMeanSMS3                                   { get; set; }
        public double  ? trueSkillStandardDeviationSMS3                      { get; set; }
        public double  ? trueSkillMeanGSMS3                                  { get; set; }
        public double  ? trueSkillStandardDeviationGSMS3                     { get; set; }
        public double  ? trueSkillMeanMS4                                    { get; set; }
        public double  ? trueSkillStandardDeviationMS4                       { get; set; }
        public double  ? trueSkillMeanSMS4                                   { get; set; }
        public double  ? trueSkillStandardDeviationSMS4                      { get; set; }
        public double  ? trueSkillMeanGSMS4                                  { get; set; }
        public double  ? trueSkillStandardDeviationGSMS4                     { get; set; }
        public int     ? matchesTotal                                        { get; set; }
        public double  ? matchesWinRatio                                     { get; set; }
        public double  ? matchesLossRatio                                    { get; set; }
        public int     ? winsTotal                                           { get; set; }
        public int     ? lossesTotal                                         { get; set; }
        public int     ? matchesLastYear                                     { get; set; }
        public double  ? matchesLastYearWinRatio                             { get; set; }
        public double  ? matchesLastYearLossRatio                            { get; set; }
        public int     ? winsLastYear                                        { get; set; }
        public int     ? lossesLastYear                                      { get; set; }
        public int     ? matchesLastMonth                                    { get; set; }
        public double  ? matchesLastMonthWinRatio                            { get; set; }
        public double  ? matchesLastMonthLossRatio                           { get; set; }
        public int     ? winsLastMonth                                       { get; set; }
        public int     ? lossesLastMonth                                     { get; set; }
        public int     ? matchesLastWeek                                     { get; set; }
        public double  ? matchesLastWeekWinRatio                             { get; set; }
        public double  ? matchesLastWeekLossRatio                            { get; set; }
        public int     ? winsLastWeek                                        { get; set; }
        public int     ? lossesLastWeek                                      { get; set; }
        public int     ? matchesTotalS1                                      { get; set; }
        public double  ? matchesTotalS1WinRatio                              { get; set; }
        public double  ? matchesTotalS1LossRatio                             { get; set; }
        public int     ? winsTotalS1                                         { get; set; }
        public int     ? lossesTotalS1                                       { get; set; }
        public int     ? matchesLastYearS1                                   { get; set; }
        public double  ? matchesLastYearS1WinRatio                           { get; set; }
        public double  ? matchesLastYearS1LossRatio                          { get; set; }
        public int     ? winsLastYearS1                                      { get; set; }
        public int     ? lossesLastYearS1                                    { get; set; }
        public int     ? matchesLastMonthS1                                  { get; set; }
        public double  ? matchesLastMonthS1WinRatio                          { get; set; }
        public double  ? matchesLastMonthS1LossRatio                         { get; set; }
        public int     ? winsLastMonthS1                                     { get; set; }
        public int     ? lossesLastMonthS1                                   { get; set; }
        public int     ? matchesLastWeekS1                                   { get; set; }
        public double  ? matchesLastWeekS1WinRatio                           { get; set; }
        public double  ? matchesLastWeekS1LossRatio                          { get; set; }
        public int     ? winsLastWeekS1                                      { get; set; }
        public int     ? lossesLastWeekS1                                    { get; set; }
        public int     ? matchesTotalS2                                      { get; set; }
        public double  ? matchesTotalS2WinRatio                              { get; set; }
        public double  ? matchesTotalS2LossRatio                             { get; set; }
        public int     ? winsTotalS2                                         { get; set; }
        public int     ? lossesTotalS2                                       { get; set; }
        public int     ? matchesLastYearS2                                   { get; set; }
        public double  ? matchesLastYearS2WinRatio                           { get; set; }
        public double  ? matchesLastYearS2LossRatio                          { get; set; }
        public int     ? winsLastYearS2                                      { get; set; }
        public int     ? lossesLastYearS2                                    { get; set; }
        public int     ? matchesLastMonthS2                                  { get; set; }
        public double  ? matchesLastMonthS2WinRatio                          { get; set; }
        public double  ? matchesLastMonthS2LossRatio                         { get; set; }
        public int     ? winsLastMonthS2                                     { get; set; }
        public int     ? lossesLastMonthS2                                   { get; set; }
        public int     ? matchesLastWeekS2                                   { get; set; }
        public double  ? matchesLastWeekS2WinRatio                           { get; set; }
        public double  ? matchesLastWeekS2LossRatio                          { get; set; }
        public int     ? winsLastWeekS2                                      { get; set; }
        public int     ? lossesLastWeekS2                                    { get; set; }
        public int     ? matchesTotalS3                                      { get; set; }
        public double  ? matchesTotalS3WinRatio                              { get; set; }
        public double  ? matchesTotalS3LossRatio                             { get; set; }
        public int     ? winsTotalS3                                         { get; set; }
        public int     ? lossesTotalS3                                       { get; set; }
        public int     ? matchesLastYearS3                                   { get; set; }
        public double  ? matchesLastYearS3WinRatio                           { get; set; }
        public double  ? matchesLastYearS3LossRatio                          { get; set; }
        public int     ? winsLastYearS3                                      { get; set; }
        public int     ? lossesLastYearS3                                    { get; set; }
        public int     ? matchesLastMonthS3                                  { get; set; }
        public double  ? matchesLastMonthS3WinRatio                          { get; set; }
        public double  ? matchesLastMonthS3LossRatio                         { get; set; }
        public int     ? winsLastMonthS3                                     { get; set; }
        public int     ? lossesLastMonthS3                                   { get; set; }
        public int     ? matchesLastWeekS3                                   { get; set; }
        public double  ? matchesLastWeekS3WinRatio                           { get; set; }
        public double  ? matchesLastWeekS3LossRatio                          { get; set; }
        public int     ? winsLastWeekS3                                      { get; set; }
        public int     ? lossesLastWeekS3                                    { get; set; }
        public int     ? matchesTotalS4                                      { get; set; }
        public double  ? matchesTotalS4WinRatio                              { get; set; }
        public double  ? matchesTotalS4LossRatio                             { get; set; }
        public int     ? winsTotalS4                                         { get; set; }
        public int     ? lossesTotalS4                                       { get; set; }
        public int     ? matchesLastYearS4                                   { get; set; }
        public double  ? matchesLastYearS4WinRatio                           { get; set; }
        public double  ? matchesLastYearS4LossRatio                          { get; set; }
        public int     ? winsLastYearS4                                      { get; set; }
        public int     ? lossesLastYearS4                                    { get; set; }
        public int     ? matchesLastMonthS4                                  { get; set; }
        public double  ? matchesLastMonthS4WinRatio                          { get; set; }
        public double  ? matchesLastMonthS4LossRatio                         { get; set; }
        public int     ? winsLastMonthS4                                     { get; set; }
        public int     ? lossesLastMonthS4                                   { get; set; }
        public int     ? matchesLastWeekS4                                   { get; set; }
        public double  ? matchesLastWeekS4WinRatio                           { get; set; }
        public double  ? matchesLastWeekS4LossRatio                          { get; set; }
        public int     ? winsLastWeekS4                                      { get; set; }
        public int     ? lossesLastWeekS4                                    { get; set; }
        public int     ? setsTotal                                           { get; set; }
        public double  ? setsWinRatio                                        { get; set; }
        public double  ? setsLossRatio                                       { get; set; }
        public int     ? winsSetsTotal                                       { get; set; }
        public int     ? lossesSetsTotal                                     { get; set; }
        public int     ? setsLastYear                                        { get; set; }
        public double  ? setsLastYearWinRatio                                { get; set; }
        public double  ? setsLastYearLossRatio                               { get; set; }
        public int     ? winsSetsLastYear                                    { get; set; }
        public int     ? lossesSetsLastYear                                  { get; set; }
        public int     ? setsLastMonth                                       { get; set; }
        public double  ? setsLastMonthWinRatio                               { get; set; }
        public double  ? setsLastMonthLossRatio                              { get; set; }
        public int     ? winsSetsLastMonth                                   { get; set; }
        public int     ? lossesSetsLastMonth                                 { get; set; }
        public int     ? setsLastWeek                                        { get; set; }
        public double  ? setsLastWeekWinRatio                                { get; set; }
        public double  ? setsLastWeekLossRatio                               { get; set; }
        public int     ? winsSetsLastWeek                                    { get; set; }
        public int     ? lossesSetsLastWeek                                  { get; set; }
        public int     ? setsTotalS1                                         { get; set; }
        public double  ? setsTotalS1WinRatio                                 { get; set; }
        public double  ? setsTotalS1LossRatio                                { get; set; }
        public int     ? winsSetsTotalS1                                     { get; set; }
        public int     ? lossesSetsTotalS1                                   { get; set; }
        public int     ? setsLastYearS1                                      { get; set; }
        public double  ? setsLastYearS1WinRatio                              { get; set; }
        public double  ? setsLastYearS1LossRatio                             { get; set; }
        public int     ? winsSetsLastYearS1                                  { get; set; }
        public int     ? lossesSetsLastYearS1                                { get; set; }
        public int     ? setsLastMonthS1                                     { get; set; }
        public double  ? setsLastMonthS1WinRatio                             { get; set; }
        public double  ? setsLastMonthS1LossRatio                            { get; set; }
        public int     ? winsSetsLastMonthS1                                 { get; set; }
        public int     ? lossesSetsLastMonthS1                               { get; set; }
        public int     ? setsLastWeekS1                                      { get; set; }
        public double  ? setsLastWeekS1WinRatio                              { get; set; }
        public double  ? setsLastWeekS1LossRatio                             { get; set; }
        public int     ? winsSetsLastWeekS1                                  { get; set; }
        public int     ? lossesSetsLastWeekS1                                { get; set; }
        public int     ? setsTotalS2                                         { get; set; }
        public double  ? setsTotalS2WinRatio                                 { get; set; }
        public double  ? setsTotalS2LossRatio                                { get; set; }
        public int     ? winsSetsTotalS2                                     { get; set; }
        public int     ? lossesSetsTotalS2                                   { get; set; }
        public int     ? setsLastYearS2                                      { get; set; }
        public double  ? setsLastYearS2WinRatio                              { get; set; }
        public double  ? setsLastYearS2LossRatio                             { get; set; }
        public int     ? winsSetsLastYearS2                                  { get; set; }
        public int     ? lossesSetsLastYearS2                                { get; set; }
        public int     ? setsLastMonthS2                                     { get; set; }
        public double  ? setsLastMonthS2WinRatio                             { get; set; }
        public double  ? setsLastMonthS2LossRatio                            { get; set; }
        public int     ? winsSetsLastMonthS2                                 { get; set; }
        public int     ? lossesSetsLastMonthS2                               { get; set; }
        public int     ? setsLastWeekS2                                      { get; set; }
        public double  ? setsLastWeekS2WinRatio                              { get; set; }
        public double  ? setsLastWeekS2LossRatio                             { get; set; }
        public int     ? winsSetsLastWeekS2                                  { get; set; }
        public int     ? lossesSetsLastWeekS2                                { get; set; }
        public int     ? setsTotalS3                                         { get; set; }
        public double  ? setsTotalS3WinRatio                                 { get; set; }
        public double  ? setsTotalS3LossRatio                                { get; set; }
        public int     ? winsSetsTotalS3                                     { get; set; }
        public int     ? lossesSetsTotalS3                                   { get; set; }
        public int     ? setsLastYearS3                                      { get; set; }
        public double  ? setsLastYearS3WinRatio                              { get; set; }
        public double  ? setsLastYearS3LossRatio                             { get; set; }
        public int     ? winsSetsLastYearS3                                  { get; set; }
        public int     ? lossesSetsLastYearS3                                { get; set; }
        public int     ? setsLastMonthS3                                     { get; set; }
        public double  ? setsLastMonthS3WinRatio                             { get; set; }
        public double  ? setsLastMonthS3LossRatio                            { get; set; }
        public int     ? winsSetsLastMonthS3                                 { get; set; }
        public int     ? lossesSetsLastMonthS3                               { get; set; }
        public int     ? setsLastWeekS3                                      { get; set; }
        public double  ? setsLastWeekS3WinRatio                              { get; set; }
        public double  ? setsLastWeekS3LossRatio                             { get; set; }
        public int     ? winsSetsLastWeekS3                                  { get; set; }
        public int     ? lossesSetsLastWeekS3                                { get; set; }
        public int     ? setsTotalS4                                         { get; set; }
        public double  ? setsTotalS4WinRatio                                 { get; set; }
        public double  ? setsTotalS4LossRatio                                { get; set; }
        public int     ? winsSetsTotalS4                                     { get; set; }
        public int     ? lossesSetsTotalS4                                   { get; set; }
        public int     ? setsLastYearS4                                      { get; set; }
        public double  ? setsLastYearS4WinRatio                              { get; set; }
        public double  ? setsLastYearS4LossRatio                             { get; set; }
        public int     ? winsSetsLastYearS4                                  { get; set; }
        public int     ? lossesSetsLastYearS4                                { get; set; }
        public int     ? setsLastMonthS4                                     { get; set; }
        public double  ? setsLastMonthS4WinRatio                             { get; set; }
        public double  ? setsLastMonthS4LossRatio                            { get; set; }
        public int     ? winsSetsLastMonthS4                                 { get; set; }
        public int     ? lossesSetsLastMonthS4                               { get; set; }
        public int     ? setsLastWeekS4                                      { get; set; }
        public double  ? setsLastWeekS4WinRatio                              { get; set; }
        public double  ? setsLastWeekS4LossRatio                             { get; set; }
        public int     ? winsSetsLastWeekS4                                  { get; set; }
        public int     ? lossesSetsLastWeekS4                                { get; set; }
        public int     ? gamesTotal                                          { get; set; }
        public double  ? gamesWinRatio                                       { get; set; }
        public double  ? gamesLossRatio                                      { get; set; }
        public int     ? winsGamesTotal                                      { get; set; }
        public int     ? lossesGamesTotal                                    { get; set; }
        public int     ? gamesLastYear                                       { get; set; }
        public double  ? gamesLastYearWinRatio                               { get; set; }
        public double  ? gamesLastYearLossRatio                              { get; set; }
        public int     ? winsGamesLastYear                                   { get; set; }
        public int     ? lossesGamesLastYear                                 { get; set; }
        public int     ? gamesLastMonth                                      { get; set; }
        public double  ? gamesLastMonthWinRatio                              { get; set; }
        public double  ? gamesLastMonthLossRatio                             { get; set; }
        public int     ? winsGamesLastMonth                                  { get; set; }
        public int     ? lossesGamesLastMonth                                { get; set; }
        public int     ? gamesLastWeek                                       { get; set; }
        public double  ? gamesLastWeekWinRatio                               { get; set; }
        public double  ? gamesLastWeekLossRatio                              { get; set; }
        public int     ? winsGamesLastWeek                                   { get; set; }
        public int     ? lossesGamesLastWeek                                 { get; set; }
        public int     ? gamesTotalS1                                        { get; set; }
        public double  ? gamesTotalS1WinRatio                                { get; set; }
        public double  ? gamesTotalS1LossRatio                               { get; set; }
        public int     ? winsGamesTotalS1                                    { get; set; }
        public int     ? lossesGamesTotalS1                                  { get; set; }
        public int     ? gamesLastYearS1                                     { get; set; }
        public double  ? gamesLastYearS1WinRatio                             { get; set; }
        public double  ? gamesLastYearS1LossRatio                            { get; set; }
        public int     ? winsGamesLastYearS1                                 { get; set; }
        public int     ? lossesGamesLastYearS1                               { get; set; }
        public int     ? gamesLastMonthS1                                    { get; set; }
        public double  ? gamesLastMonthS1WinRatio                            { get; set; }
        public double  ? gamesLastMonthS1LossRatio                           { get; set; }
        public int     ? winsGamesLastMonthS1                                { get; set; }
        public int     ? lossesGamesLastMonthS1                              { get; set; }
        public int     ? gamesLastWeekS1                                     { get; set; }
        public double  ? gamesLastWeekS1WinRatio                             { get; set; }
        public double  ? gamesLastWeekS1LossRatio                            { get; set; }
        public int     ? winsGamesLastWeekS1                                 { get; set; }
        public int     ? lossesGamesLastWeekS1                               { get; set; }
        public int     ? gamesTotalS2                                        { get; set; }
        public double  ? gamesTotalS2WinRatio                                { get; set; }
        public double  ? gamesTotalS2LossRatio                               { get; set; }
        public int     ? winsGamesTotalS2                                    { get; set; }
        public int     ? lossesGamesTotalS2                                  { get; set; }
        public int     ? gamesLastYearS2                                     { get; set; }
        public double  ? gamesLastYearS2WinRatio                             { get; set; }
        public double  ? gamesLastYearS2LossRatio                            { get; set; }
        public int     ? winsGamesLastYearS2                                 { get; set; }
        public int     ? lossesGamesLastYearS2                               { get; set; }
        public int     ? gamesLastMonthS2                                    { get; set; }
        public double  ? gamesLastMonthS2WinRatio                            { get; set; }
        public double  ? gamesLastMonthS2LossRatio                           { get; set; }
        public int     ? winsGamesLastMonthS2                                { get; set; }
        public int     ? lossesGamesLastMonthS2                              { get; set; }
        public int     ? gamesLastWeekS2                                     { get; set; }
        public double  ? gamesLastWeekS2WinRatio                             { get; set; }
        public double  ? gamesLastWeekS2LossRatio                            { get; set; }
        public int     ? winsGamesLastWeekS2                                 { get; set; }
        public int     ? lossesGamesLastWeekS2                               { get; set; }
        public int     ? gamesTotalS3                                        { get; set; }
        public double  ? gamesTotalS3WinRatio                                { get; set; }
        public double  ? gamesTotalS3LossRatio                               { get; set; }
        public int     ? winsGamesTotalS3                                    { get; set; }
        public int     ? lossesGamesTotalS3                                  { get; set; }
        public int     ? gamesLastYearS3                                     { get; set; }
        public double  ? gamesLastYearS3WinRatio                             { get; set; }
        public double  ? gamesLastYearS3LossRatio                            { get; set; }
        public int     ? winsGamesLastYearS3                                 { get; set; }
        public int     ? lossesGamesLastYearS3                               { get; set; }
        public int     ? gamesLastMonthS3                                    { get; set; }
        public double  ? gamesLastMonthS3WinRatio                            { get; set; }
        public double  ? gamesLastMonthS3LossRatio                           { get; set; }
        public int     ? winsGamesLastMonthS3                                { get; set; }
        public int     ? lossesGamesLastMonthS3                              { get; set; }
        public int     ? gamesLastWeekS3                                     { get; set; }
        public double  ? gamesLastWeekS3WinRatio                             { get; set; }
        public double  ? gamesLastWeekS3LossRatio                            { get; set; }
        public int     ? winsGamesLastWeekS3                                 { get; set; }
        public int     ? lossesGamesLastWeekS3                               { get; set; }
        public int     ? gamesTotalS4                                        { get; set; }
        public double  ? gamesTotalS4WinRatio                                { get; set; }
        public double  ? gamesTotalS4LossRatio                               { get; set; }
        public int     ? winsGamesTotalS4                                    { get; set; }
        public int     ? lossesGamesTotalS4                                  { get; set; }
        public int     ? gamesLastYearS4                                     { get; set; }
        public double  ? gamesLastYearS4WinRatio                             { get; set; }
        public double  ? gamesLastYearS4LossRatio                            { get; set; }
        public int     ? winsGamesLastYearS4                                 { get; set; }
        public int     ? lossesGamesLastYearS4                               { get; set; }
        public int     ? gamesLastMonthS4                                    { get; set; }
        public double  ? gamesLastMonthS4WinRatio                            { get; set; }
        public double  ? gamesLastMonthS4LossRatio                           { get; set; }
        public int     ? winsGamesLastMonthS4                                { get; set; }
        public int     ? lossesGamesLastMonthS4                              { get; set; }
        public int     ? gamesLastWeekS4                                     { get; set; }
        public double  ? gamesLastWeekS4WinRatio                             { get; set; }
        public double  ? gamesLastWeekS4LossRatio                            { get; set; }
        public int     ? winsGamesLastWeekS4                                 { get; set; }
        public int     ? lossesGamesLastWeekS4                               { get; set; }
        public DateTime? dateSinceLastWin                                    { get; set; }
        public DateTime? dateSinceLastWinS1                                  { get; set; }
        public DateTime? dateSinceLastWinS2                                  { get; set; }
        public DateTime? dateSinceLastWinS3                                  { get; set; }
        public DateTime? dateSinceLastWinS4                                  { get; set; }
        public DateTime? dateSinceLastLoss                                   { get; set; }
        public DateTime? dateSinceLastLossS1                                 { get; set; }
        public DateTime? dateSinceLastLossS2                                 { get; set; }
        public DateTime? dateSinceLastLossS3                                 { get; set; }
        public DateTime? dateSinceLastLossS4                                 { get; set; }
        public int     ? totalWinsAsFavourite                                { get; set; }
        public int     ? totalWinsAsUnderdog                                 { get; set; }
        public int     ? totalLossesAsFavourite                              { get; set; }
        public int     ? totalLossesAsUnderdog                               { get; set; }
        public double  ? winsAsFavouriteRatio                                { get; set; }
        public double  ? lossesAsFavouriteRatio                              { get; set; }
        public double  ? winsAsUnderdogRatio                                 { get; set; }
        public double  ? lossesAsUnderdogRatio                               { get; set; }
        public double  ? averageWinningProbabilityAtWonAsFavourite           { get; set; }
        public double  ? averageWinningProbabilityAtWonAsUnderdog            { get; set; }
        public double  ? averageWinningProbabilityAtLossAsFavourite          { get; set; }
        public double  ? averageWinningProbabilityAtLossAsUnderdog           { get; set; }
        public int     ? totalWinsAsFavouriteLastYear                        { get; set; }
        public int     ? totalWinsAsUnderdogLastYear                         { get; set; }
        public int     ? totalLossesAsFavouriteLastYear                      { get; set; }
        public int     ? totalLossesAsUnderdogLastYear                       { get; set; }
        public double  ? winsAsFavouriteLastYearRatio                        { get; set; }
        public double  ? lossesAsFavouriteLastYearRatio                      { get; set; }
        public double  ? winsAsUnderdogLastYearRatio                         { get; set; }
        public double  ? lossesAsUnderdogLastYearRatio                       { get; set; }
        public double  ? averageWinningProbabilityAtWonAsFavouriteLastYear   { get; set; }
        public double  ? averageWinningProbabilityAtWonAsUnderdogLastYear    { get; set; }
        public double  ? averageWinningProbabilityAtLossAsFavouriteLastYear  { get; set; }
        public double  ? averageWinningProbabilityAtLossAsUnderdogLastYear   { get; set; }
        public int     ? totalWinsAsFavouriteLastMonth                       { get; set; }
        public int     ? totalWinsAsUnderdogLastMonth                        { get; set; }
        public int     ? totalLossesAsFavouriteLastMonth                     { get; set; }
        public int     ? totalLossesAsUnderdogLastMonth                      { get; set; }
        public double  ? winsAsFavouriteLastMonthRatio                       { get; set; }
        public double  ? lossesAsFavouriteLastMonthRatio                     { get; set; }
        public double  ? winsAsUnderdogLastMonthRatio                        { get; set; }
        public double  ? lossesAsUnderdogLastMonthRatio                      { get; set; }
        public double  ? averageWinningProbabilityAtWonAsFavouriteLastMonth  { get; set; }
        public double  ? averageWinningProbabilityAtWonAsUnderdogLastMonth   { get; set; }
        public double  ? averageWinningProbabilityAtLossAsFavouriteLastMonth { get; set; }
        public double  ? averageWinningProbabilityAtLossAsUnderdogLastMonth  { get; set; }
        public int     ? totalWinsAsFavouriteLastWeek                        { get; set; }
        public int     ? totalWinsAsUnderdogLastWeek                         { get; set; }
        public int     ? totalLossesAsFavouriteLastWeek                      { get; set; }
        public int     ? totalLossesAsUnderdogLastWeek                       { get; set; }
        public double  ? winsAsFavouriteLastWeekRatio                        { get; set; }
        public double  ? lossesAsFavouriteLastWeekRatio                      { get; set; }
        public double  ? winsAsUnderdogLastWeekRatio                         { get; set; }
        public double  ? lossesAsUnderdogLastWeekRatio                       { get; set; }
        public double  ? averageWinningProbabilityAtWonAsFavouriteLastWeek   { get; set; }
        public double  ? averageWinningProbabilityAtWonAsUnderdogLastWeek    { get; set; }
        public double  ? averageWinningProbabilityAtLossAsFavouriteLastWeek  { get; set; }
        public double  ? averageWinningProbabilityAtLossAsUnderdogLastWeek   { get; set; }
        public int     ? streak                                              { get; set; }
        public int     ? streakS1                                            { get; set; }
        public int     ? streakS2                                            { get; set; }
        public int     ? streakS3                                            { get; set; }
        public int     ? streakS4                                            { get; set; }
        public List<MatchDetailsDTO> ? matchMongoDTOs                          { get; set; }
        }
}