namespace BonzoByte.Core.Models
{
    public class MatchActive
    {
        public int     ? MatchTPId                                                  { get; set; }
        public int     ? TournamentEventTPId                                        { get; set; }
        public DateTime? DateTime                                                   { get; set; }
        public int     ? Player1TPId                                                { get; set; }
        public int     ? Player2TPId                                                { get; set; }
        public string  ? Player1Seed                                                { get; set; }
        public string  ? Player2Seed                                                { get; set; }
        public double  ? Player1Odds                                                { get; set; }
        public double  ? Player2Odds                                                { get; set; }
        public double  ? Player1Percentage                                          { get; set; }
        public double  ? Player2Percentage                                          { get; set; }
        public int     ? SurfaceId                                                  { get; set; }
        public int     ? RoundId                                                    { get; set; }
        public double  ? Player1TrueSkillMeanOldM                                   { get; set; }
        public double  ? Player1TrueSkillStandardDeviationOldM                      { get; set; }
        public double  ? Player2TrueSkillMeanOldM                                   { get; set; }
        public double  ? Player2TrueSkillStandardDeviationOldM                      { get; set; }
        public double  ? WinProbabilityPlayer1M                                     { get; set; }
        public double  ? Player1TrueSkillMeanOldSM                                  { get; set; }
        public double  ? Player1TrueSkillStandardDeviationOldSM                     { get; set; }
        public double  ? Player2TrueSkillMeanOldSM                                  { get; set; }
        public double  ? Player2TrueSkillStandardDeviationOldSM                     { get; set; }
        public double  ? WinProbabilityPlayer1SM                                    { get; set; }
        public double  ? Player1TrueSkillMeanOldGSM                                 { get; set; }
        public double  ? Player1TrueSkillStandardDeviationOldGSM                    { get; set; }
        public double  ? Player2TrueSkillMeanOldGSM                                 { get; set; }
        public double  ? Player2TrueSkillStandardDeviationOldGSM                    { get; set; }
        public double  ? WinProbabilityPlayer1GSM                                   { get; set; }
        public double  ? Player1TrueSkillMeanOldMS1                                 { get; set; }
        public double  ? Player1TrueSkillStandardDeviationOldMS1                    { get; set; }
        public double  ? Player2TrueSkillMeanOldMS1                                 { get; set; }
        public double  ? Player2TrueSkillStandardDeviationOldMS1                    { get; set; }
        public double  ? WinProbabilityPlayer1MS1                                   { get; set; }
        public double  ? Player1TrueSkillMeanOldSMS1                                { get; set; }
        public double  ? Player1TrueSkillStandardDeviationOldSMS1                   { get; set; }
        public double  ? Player2TrueSkillMeanOldSMS1                                { get; set; }
        public double  ? Player2TrueSkillStandardDeviationOldSMS1                   { get; set; }
        public double  ? WinProbabilityPlayer1SMS1                                  { get; set; }
        public double  ? Player1TrueSkillMeanOldGSMS1                               { get; set; }
        public double  ? Player1TrueSkillStandardDeviationOldGSMS1                  { get; set; }
        public double  ? Player2TrueSkillMeanOldGSMS1                               { get; set; }
        public double  ? Player2TrueSkillStandardDeviationOldGSMS1                  { get; set; }
        public double  ? WinProbabilityPlayer1GSMS1                                 { get; set; }
        public double  ? Player1TrueSkillMeanOldMS2                                 { get; set; }
        public double  ? Player1TrueSkillStandardDeviationOldMS2                    { get; set; }
        public double  ? Player2TrueSkillMeanOldMS2                                 { get; set; }
        public double  ? Player2TrueSkillStandardDeviationOldMS2                    { get; set; }
        public double  ? WinProbabilityPlayer1MS2                                   { get; set; }
        public double  ? Player1TrueSkillMeanOldSMS2                                { get; set; }
        public double  ? Player1TrueSkillStandardDeviationOldSMS2                   { get; set; }
        public double  ? Player2TrueSkillMeanOldSMS2                                { get; set; }
        public double  ? Player2TrueSkillStandardDeviationOldSMS2                   { get; set; }
        public double  ? WinProbabilityPlayer1SMS2                                  { get; set; }
        public double  ? Player1TrueSkillMeanOldGSMS2                               { get; set; }
        public double  ? Player1TrueSkillStandardDeviationOldGSMS2                  { get; set; }
        public double  ? Player2TrueSkillMeanOldGSMS2                               { get; set; }
        public double  ? Player2TrueSkillStandardDeviationOldGSMS2                  { get; set; }
        public double  ? WinProbabilityPlayer1GSMS2                                 { get; set; }
        public double  ? Player1TrueSkillMeanOldMS3                                 { get; set; }
        public double  ? Player1TrueSkillStandardDeviationOldMS3                    { get; set; }
        public double  ? Player2TrueSkillMeanOldMS3                                 { get; set; }
        public double  ? Player2TrueSkillStandardDeviationOldMS3                    { get; set; }
        public double  ? WinProbabilityPlayer1MS3                                   { get; set; }
        public double  ? Player1TrueSkillMeanOldSMS3                                { get; set; }
        public double  ? Player1TrueSkillStandardDeviationOldSMS3                   { get; set; }
        public double  ? Player2TrueSkillMeanOldSMS3                                { get; set; }
        public double  ? Player2TrueSkillStandardDeviationOldSMS3                   { get; set; }
        public double  ? WinProbabilityPlayer1SMS3                                  { get; set; }
        public double  ? Player1TrueSkillMeanOldGSMS3                               { get; set; }
        public double  ? Player1TrueSkillStandardDeviationOldGSMS3                  { get; set; }
        public double  ? Player2TrueSkillMeanOldGSMS3                               { get; set; }
        public double  ? Player2TrueSkillStandardDeviationOldGSMS3                  { get; set; }
        public double  ? WinProbabilityPlayer1GSMS3                                 { get; set; }
        public double  ? Player1TrueSkillMeanOldMS4                                 { get; set; }
        public double  ? Player1TrueSkillStandardDeviationOldMS4                    { get; set; }
        public double  ? Player2TrueSkillMeanOldMS4                                 { get; set; }
        public double  ? Player2TrueSkillStandardDeviationOldMS4                    { get; set; }
        public double  ? WinProbabilityPlayer1MS4                                   { get; set; }
        public double  ? Player1TrueSkillMeanOldSMS4                                { get; set; }
        public double  ? Player1TrueSkillStandardDeviationOldSMS4                   { get; set; }
        public double  ? Player2TrueSkillMeanOldSMS4                                { get; set; }
        public double  ? Player2TrueSkillStandardDeviationOldSMS4                   { get; set; }
        public double  ? WinProbabilityPlayer1SMS4                                  { get; set; }
        public double  ? Player1TrueSkillMeanOldGSMS4                               { get; set; }
        public double  ? Player1TrueSkillStandardDeviationOldGSMS4                  { get; set; }
        public double  ? Player2TrueSkillMeanOldGSMS4                               { get; set; }
        public double  ? Player2TrueSkillStandardDeviationOldGSMS4                  { get; set; }
        public double  ? WinProbabilityPlayer1GSMS4                                 { get; set; }
        public int     ? Player1WinsTotal                                           { get; set; }
        public int     ? Player1LossesTotal                                         { get; set; }
        public int     ? Player1WinsLastYear                                        { get; set; }
        public int     ? Player1LossesLastYear                                      { get; set; }
        public int     ? Player1WinsLastMonth                                       { get; set; }
        public int     ? Player1LossesLastMonth                                     { get; set; }
        public int     ? Player1WinsLastWeek                                        { get; set; }
        public int     ? Player1LossesLastWeek                                      { get; set; }
        public int     ? Player2WinsTotal                                           { get; set; }
        public int     ? Player2LossesTotal                                         { get; set; }
        public int     ? Player2WinsLastYear                                        { get; set; }
        public int     ? Player2LossesLastYear                                      { get; set; }
        public int     ? Player2WinsLastMonth                                       { get; set; }
        public int     ? Player2LossesLastMonth                                     { get; set; }
        public int     ? Player2WinsLastWeek                                        { get; set; }
        public int     ? Player2LossesLastWeek                                      { get; set; }
        public int     ? Player1WinsTotalS1                                         { get; set; }
        public int     ? Player1LossesTotalS1                                       { get; set; }
        public int     ? Player1WinsLastYearS1                                      { get; set; }
        public int     ? Player1LossesLastYearS1                                    { get; set; }
        public int     ? Player1WinsLastMonthS1                                     { get; set; }
        public int     ? Player1LossesLastMonthS1                                   { get; set; }
        public int     ? Player1WinsLastWeekS1                                      { get; set; }
        public int     ? Player1LossesLastWeekS1                                    { get; set; }
        public int     ? Player2WinsTotalS1                                         { get; set; }
        public int     ? Player2LossesTotalS1                                       { get; set; }
        public int     ? Player2WinsLastYearS1                                      { get; set; }
        public int     ? Player2LossesLastYearS1                                    { get; set; }
        public int     ? Player2WinsLastMonthS1                                     { get; set; }
        public int     ? Player2LossesLastMonthS1                                   { get; set; }
        public int     ? Player2WinsLastWeekS1                                      { get; set; }
        public int     ? Player2LossesLastWeekS1                                    { get; set; }
        public int     ? Player1WinsTotalS2                                         { get; set; }
        public int     ? Player1LossesTotalS2                                       { get; set; }
        public int     ? Player1WinsLastYearS2                                      { get; set; }
        public int     ? Player1LossesLastYearS2                                    { get; set; }
        public int     ? Player1WinsLastMonthS2                                     { get; set; }
        public int     ? Player1LossesLastMonthS2                                   { get; set; }
        public int     ? Player1WinsLastWeekS2                                      { get; set; }
        public int     ? Player1LossesLastWeekS2                                    { get; set; }
        public int     ? Player2WinsTotalS2                                         { get; set; }
        public int     ? Player2LossesTotalS2                                       { get; set; }
        public int     ? Player2WinsLastYearS2                                      { get; set; }
        public int     ? Player2LossesLastYearS2                                    { get; set; }
        public int     ? Player2WinsLastMonthS2                                     { get; set; }
        public int     ? Player2LossesLastMonthS2                                   { get; set; }
        public int     ? Player2WinsLastWeekS2                                      { get; set; }
        public int     ? Player2LossesLastWeekS2                                    { get; set; }
        public int     ? Player1WinsTotalS3                                         { get; set; }
        public int     ? Player1LossesTotalS3                                       { get; set; }
        public int     ? Player1WinsLastYearS3                                      { get; set; }
        public int     ? Player1LossesLastYearS3                                    { get; set; }
        public int     ? Player1WinsLastMonthS3                                     { get; set; }
        public int     ? Player1LossesLastMonthS3                                   { get; set; }
        public int     ? Player1WinsLastWeekS3                                      { get; set; }
        public int     ? Player1LossesLastWeekS3                                    { get; set; }
        public int     ? Player2WinsTotalS3                                         { get; set; }
        public int     ? Player2LossesTotalS3                                       { get; set; }
        public int     ? Player2WinsLastYearS3                                      { get; set; }
        public int     ? Player2LossesLastYearS3                                    { get; set; }
        public int     ? Player2WinsLastMonthS3                                     { get; set; }
        public int     ? Player2LossesLastMonthS3                                   { get; set; }
        public int     ? Player2WinsLastWeekS3                                      { get; set; }
        public int     ? Player2LossesLastWeekS3                                    { get; set; }
        public int     ? Player1WinsTotalS4                                         { get; set; }
        public int     ? Player1LossesTotalS4                                       { get; set; }
        public int     ? Player1WinsLastYearS4                                      { get; set; }
        public int     ? Player1LossesLastYearS4                                    { get; set; }
        public int     ? Player1WinsLastMonthS4                                     { get; set; }
        public int     ? Player1LossesLastMonthS4                                   { get; set; }
        public int     ? Player1WinsLastWeekS4                                      { get; set; }
        public int     ? Player1LossesLastWeekS4                                    { get; set; }
        public int     ? Player2WinsTotalS4                                         { get; set; }
        public int     ? Player2LossesTotalS4                                       { get; set; }
        public int     ? Player2WinsLastYearS4                                      { get; set; }
        public int     ? Player2LossesLastYearS4                                    { get; set; }
        public int     ? Player2WinsLastMonthS4                                     { get; set; }
        public int     ? Player2LossesLastMonthS4                                   { get; set; }
        public int     ? Player2WinsLastWeekS4                                      { get; set; }
        public int     ? Player2LossesLastWeekS4                                    { get; set; }
        public int     ? Player1WinsSetsTotal                                       { get; set; }
        public int     ? Player1LossesSetsTotal                                     { get; set; }
        public int     ? Player1WinsSetsLastYear                                    { get; set; }
        public int     ? Player1LossesSetsLastYear                                  { get; set; }
        public int     ? Player1WinsSetsLastMonth                                   { get; set; }
        public int     ? Player1LossesSetsLastMonth                                 { get; set; }
        public int     ? Player1WinsSetsLastWeek                                    { get; set; }
        public int     ? Player1LossesSetsLastWeek                                  { get; set; }
        public int     ? Player2WinsSetsTotal                                       { get; set; }
        public int     ? Player2LossesSetsTotal                                     { get; set; }
        public int     ? Player2WinsSetsLastYear                                    { get; set; }
        public int     ? Player2LossesSetsLastYear                                  { get; set; }
        public int     ? Player2WinsSetsLastMonth                                   { get; set; }
        public int     ? Player2LossesSetsLastMonth                                 { get; set; }
        public int     ? Player2WinsSetsLastWeek                                    { get; set; }
        public int     ? Player2LossesSetsLastWeek                                  { get; set; }
        public int     ? Player1WinsSetsTotalS1                                     { get; set; }
        public int     ? Player1LossesSetsTotalS1                                   { get; set; }
        public int     ? Player1WinsSetsLastYearS1                                  { get; set; }
        public int     ? Player1LossesSetsLastYearS1                                { get; set; }
        public int     ? Player1WinsSetsLastMonthS1                                 { get; set; }
        public int     ? Player1LossesSetsLastMonthS1                               { get; set; }
        public int     ? Player1WinsSetsLastWeekS1                                  { get; set; }
        public int     ? Player1LossesSetsLastWeekS1                                { get; set; }
        public int     ? Player2WinsSetsTotalS1                                     { get; set; }
        public int     ? Player2LossesSetsTotalS1                                   { get; set; }
        public int     ? Player2WinsSetsLastYearS1                                  { get; set; }
        public int     ? Player2LossesSetsLastYearS1                                { get; set; }
        public int     ? Player2WinsSetsLastMonthS1                                 { get; set; }
        public int     ? Player2LossesSetsLastMonthS1                               { get; set; }
        public int     ? Player2WinsSetsLastWeekS1                                  { get; set; }
        public int     ? Player2LossesSetsLastWeekS1                                { get; set; }
        public int     ? Player1WinsSetsTotalS2                                     { get; set; }
        public int     ? Player1LossesSetsTotalS2                                   { get; set; }
        public int     ? Player1WinsSetsLastYearS2                                  { get; set; }
        public int     ? Player1LossesSetsLastYearS2                                { get; set; }
        public int     ? Player1WinsSetsLastMonthS2                                 { get; set; }
        public int     ? Player1LossesSetsLastMonthS2                               { get; set; }
        public int     ? Player1WinsSetsLastWeekS2                                  { get; set; }
        public int     ? Player1LossesSetsLastWeekS2                                { get; set; }
        public int     ? Player2WinsSetsTotalS2                                     { get; set; }
        public int     ? Player2LossesSetsTotalS2                                   { get; set; }
        public int     ? Player2WinsSetsLastYearS2                                  { get; set; }
        public int     ? Player2LossesSetsLastYearS2                                { get; set; }
        public int     ? Player2WinsSetsLastMonthS2                                 { get; set; }
        public int     ? Player2LossesSetsLastMonthS2                               { get; set; }
        public int     ? Player2WinsSetsLastWeekS2                                  { get; set; }
        public int     ? Player2LossesSetsLastWeekS2                                { get; set; }
        public int     ? Player1WinsSetsTotalS3                                     { get; set; }
        public int     ? Player1LossesSetsTotalS3                                   { get; set; }
        public int     ? Player1WinsSetsLastYearS3                                  { get; set; }
        public int     ? Player1LossesSetsLastYearS3                                { get; set; }
        public int     ? Player1WinsSetsLastMonthS3                                 { get; set; }
        public int     ? Player1LossesSetsLastMonthS3                               { get; set; }
        public int     ? Player1WinsSetsLastWeekS3                                  { get; set; }
        public int     ? Player1LossesSetsLastWeekS3                                { get; set; }
        public int     ? Player2WinsSetsTotalS3                                     { get; set; }
        public int     ? Player2LossesSetsTotalS3                                   { get; set; }
        public int     ? Player2WinsSetsLastYearS3                                  { get; set; }
        public int     ? Player2LossesSetsLastYearS3                                { get; set; }
        public int     ? Player2WinsSetsLastMonthS3                                 { get; set; }
        public int     ? Player2LossesSetsLastMonthS3                               { get; set; }
        public int     ? Player2WinsSetsLastWeekS3                                  { get; set; }
        public int     ? Player2LossesSetsLastWeekS3                                { get; set; }
        public int     ? Player1WinsSetsTotalS4                                     { get; set; }
        public int     ? Player1LossesSetsTotalS4                                   { get; set; }
        public int     ? Player1WinsSetsLastYearS4                                  { get; set; }
        public int     ? Player1LossesSetsLastYearS4                                { get; set; }
        public int     ? Player1WinsSetsLastMonthS4                                 { get; set; }
        public int     ? Player1LossesSetsLastMonthS4                               { get; set; }
        public int     ? Player1WinsSetsLastWeekS4                                  { get; set; }
        public int     ? Player1LossesSetsLastWeekS4                                { get; set; }
        public int     ? Player2WinsSetsTotalS4                                     { get; set; }
        public int     ? Player2LossesSetsTotalS4                                   { get; set; }
        public int     ? Player2WinsSetsLastYearS4                                  { get; set; }
        public int     ? Player2LossesSetsLastYearS4                                { get; set; }
        public int     ? Player2WinsSetsLastMonthS4                                 { get; set; }
        public int     ? Player2LossesSetsLastMonthS4                               { get; set; }
        public int     ? Player2WinsSetsLastWeekS4                                  { get; set; }
        public int     ? Player2LossesSetsLastWeekS4                                { get; set; }
        public int     ? Player1WinsGamesTotal                                      { get; set; }
        public int     ? Player1LossesGamesTotal                                    { get; set; }
        public int     ? Player1WinsGamesLastYear                                   { get; set; }
        public int     ? Player1LossesGamesLastYear                                 { get; set; }
        public int     ? Player1WinsGamesLastMonth                                  { get; set; }
        public int     ? Player1LossesGamesLastMonth                                { get; set; }
        public int     ? Player1WinsGamesLastWeek                                   { get; set; }
        public int     ? Player1LossesGamesLastWeek                                 { get; set; }
        public int     ? Player2WinsGamesTotal                                      { get; set; }
        public int     ? Player2LossesGamesTotal                                    { get; set; }
        public int     ? Player2WinsGamesLastYear                                   { get; set; }
        public int     ? Player2LossesGamesLastYear                                 { get; set; }
        public int     ? Player2WinsGamesLastMonth                                  { get; set; }
        public int     ? Player2LossesGamesLastMonth                                { get; set; }
        public int     ? Player2WinsGamesLastWeek                                   { get; set; }
        public int     ? Player2LossesGamesLastWeek                                 { get; set; }
        public int     ? Player1WinsGamesTotalS1                                    { get; set; }
        public int     ? Player1LossesGamesTotalS1                                  { get; set; }
        public int     ? Player1WinsGamesLastYearS1                                 { get; set; }
        public int     ? Player1LossesGamesLastYearS1                               { get; set; }
        public int     ? Player1WinsGamesLastMonthS1                                { get; set; }
        public int     ? Player1LossesGamesLastMonthS1                              { get; set; }
        public int     ? Player1WinsGamesLastWeekS1                                 { get; set; }
        public int     ? Player1LossesGamesLastWeekS1                               { get; set; }
        public int     ? Player2WinsGamesTotalS1                                    { get; set; }
        public int     ? Player2LossesGamesTotalS1                                  { get; set; }
        public int     ? Player2WinsGamesLastYearS1                                 { get; set; }
        public int     ? Player2LossesGamesLastYearS1                               { get; set; }
        public int     ? Player2WinsGamesLastMonthS1                                { get; set; }
        public int     ? Player2LossesGamesLastMonthS1                              { get; set; }
        public int     ? Player2WinsGamesLastWeekS1                                 { get; set; }
        public int     ? Player2LossesGamesLastWeekS1                               { get; set; }
        public int     ? Player1WinsGamesTotalS2                                    { get; set; }
        public int     ? Player1LossesGamesTotalS2                                  { get; set; }
        public int     ? Player1WinsGamesLastYearS2                                 { get; set; }
        public int     ? Player1LossesGamesLastYearS2                               { get; set; }
        public int     ? Player1WinsGamesLastMonthS2                                { get; set; }
        public int     ? Player1LossesGamesLastMonthS2                              { get; set; }
        public int     ? Player1WinsGamesLastWeekS2                                 { get; set; }
        public int     ? Player1LossesGamesLastWeekS2                               { get; set; }
        public int     ? Player2WinsGamesTotalS2                                    { get; set; }
        public int     ? Player2LossesGamesTotalS2                                  { get; set; }
        public int     ? Player2WinsGamesLastYearS2                                 { get; set; }
        public int     ? Player2LossesGamesLastYearS2                               { get; set; }
        public int     ? Player2WinsGamesLastMonthS2                                { get; set; }
        public int     ? Player2LossesGamesLastMonthS2                              { get; set; }
        public int     ? Player2WinsGamesLastWeekS2                                 { get; set; }
        public int     ? Player2LossesGamesLastWeekS2                               { get; set; }
        public int     ? Player1WinsGamesTotalS3                                    { get; set; }
        public int     ? Player1LossesGamesTotalS3                                  { get; set; }
        public int     ? Player1WinsGamesLastYearS3                                 { get; set; }
        public int     ? Player1LossesGamesLastYearS3                               { get; set; }
        public int     ? Player1WinsGamesLastMonthS3                                { get; set; }
        public int     ? Player1LossesGamesLastMonthS3                              { get; set; }
        public int     ? Player1WinsGamesLastWeekS3                                 { get; set; }
        public int     ? Player1LossesGamesLastWeekS3                               { get; set; }
        public int     ? Player2WinsGamesTotalS3                                    { get; set; }
        public int     ? Player2LossesGamesTotalS3                                  { get; set; }
        public int     ? Player2WinsGamesLastYearS3                                 { get; set; }
        public int     ? Player2LossesGamesLastYearS3                               { get; set; }
        public int     ? Player2WinsGamesLastMonthS3                                { get; set; }
        public int     ? Player2LossesGamesLastMonthS3                              { get; set; }
        public int     ? Player2WinsGamesLastWeekS3                                 { get; set; }
        public int     ? Player2LossesGamesLastWeekS3                               { get; set; }
        public int     ? Player1WinsGamesTotalS4                                    { get; set; }
        public int     ? Player1LossesGamesTotalS4                                  { get; set; }
        public int     ? Player1WinsGamesLastYearS4                                 { get; set; }
        public int     ? Player1LossesGamesLastYearS4                               { get; set; }
        public int     ? Player1WinsGamesLastMonthS4                                { get; set; }
        public int     ? Player1LossesGamesLastMonthS4                              { get; set; }
        public int     ? Player1WinsGamesLastWeekS4                                 { get; set; }
        public int     ? Player1LossesGamesLastWeekS4                               { get; set; }
        public int     ? Player2WinsGamesTotalS4                                    { get; set; }
        public int     ? Player2LossesGamesTotalS4                                  { get; set; }
        public int     ? Player2WinsGamesLastYearS4                                 { get; set; }
        public int     ? Player2LossesGamesLastYearS4                               { get; set; }
        public int     ? Player2WinsGamesLastMonthS4                                { get; set; }
        public int     ? Player2LossesGamesLastMonthS4                              { get; set; }
        public int     ? Player2WinsGamesLastWeekS4                                 { get; set; }
        public int     ? Player2LossesGamesLastWeekS4                               { get; set; }
        public int     ? Player1DaysSinceLastWin                                    { get; set; }
        public int     ? Player2DaysSinceLastWin                                    { get; set; }
        public int     ? Player1DaysSinceLastWinS1                                  { get; set; }
        public int     ? Player2DaysSinceLastWinS1                                  { get; set; }
        public int     ? Player1DaysSinceLastWinS2                                  { get; set; }
        public int     ? Player2DaysSinceLastWinS2                                  { get; set; }
        public int     ? Player1DaysSinceLastWinS3                                  { get; set; }
        public int     ? Player2DaysSinceLastWinS3                                  { get; set; }
        public int     ? Player1DaysSinceLastWinS4                                  { get; set; }
        public int     ? Player2DaysSinceLastWinS4                                  { get; set; }
        public int     ? Player1DaysSinceLastLoss                                   { get; set; }
        public int     ? Player2DaysSinceLastLoss                                   { get; set; }
        public int     ? Player1DaysSinceLastLossS1                                 { get; set; }
        public int     ? Player2DaysSinceLastLossS1                                 { get; set; }
        public int     ? Player1DaysSinceLastLossS2                                 { get; set; }
        public int     ? Player2DaysSinceLastLossS2                                 { get; set; }
        public int     ? Player1DaysSinceLastLossS3                                 { get; set; }
        public int     ? Player2DaysSinceLastLossS3                                 { get; set; }
        public int     ? Player1DaysSinceLastLossS4                                 { get; set; }
        public int     ? Player2DaysSinceLastLossS4                                 { get; set; }
        public int     ? Player1TotalWinsAsFavourite                                { get; set; }
        public int     ? Player2TotalWinsAsFavourite                                { get; set; }
        public int     ? Player1TotalWinsAsUnderdog                                 { get; set; }
        public int     ? Player2TotalWinsAsUnderdog                                 { get; set; }
        public int     ? Player1TotalLossesAsFavourite                              { get; set; }
        public int     ? Player2TotalLossesAsFavourite                              { get; set; }
        public int     ? Player1TotalLossesAsUnderdog                               { get; set; }
        public int     ? Player2TotalLossesAsUnderdog                               { get; set; }
        public double  ? Player1AverageWinningProbabilityAtWonAsFavourite           { get; set; }
        public double  ? Player2AverageWinningProbabilityAtWonAsFavourite           { get; set; }
        public double  ? Player1AverageWinningProbabilityAtWonAsUnderdog            { get; set; }
        public double  ? Player2AverageWinningProbabilityAtWonAsUnderdog            { get; set; }
        public double  ? Player1AverageWinningProbabilityAtLossAsFavourite          { get; set; }
        public double  ? Player2AverageWinningProbabilityAtLossAsFavourite          { get; set; }
        public double  ? Player1AverageWinningProbabilityAtLossAsUnderdog           { get; set; }
        public double  ? Player2AverageWinningProbabilityAtLossAsUnderdog           { get; set; }
        public int     ? Player1TotalWinsAsFavouriteLastYear                        { get; set; }
        public int     ? Player2TotalWinsAsFavouriteLastYear                        { get; set; }
        public int     ? Player1TotalWinsAsUnderdogLastYear                         { get; set; }
        public int     ? Player2TotalWinsAsUnderdogLastYear                         { get; set; }
        public int     ? Player1TotalLossesAsFavouriteLastYear                      { get; set; }
        public int     ? Player2TotalLossesAsFavouriteLastYear                      { get; set; }
        public int     ? Player1TotalLossesAsUnderdogLastYear                       { get; set; }
        public int     ? Player2TotalLossesAsUnderdogLastYear                       { get; set; }
        public double  ? Player1AverageWinningProbabilityAtWonAsFavouriteLastYear   { get; set; }
        public double  ? Player2AverageWinningProbabilityAtWonAsFavouriteLastYear   { get; set; }
        public double  ? Player1AverageWinningProbabilityAtWonAsUnderdogLastYear    { get; set; }
        public double  ? Player2AverageWinningProbabilityAtWonAsUnderdogLastYear    { get; set; }
        public double  ? Player1AverageWinningProbabilityAtLossAsFavouriteLastYear  { get; set; }
        public double  ? Player2AverageWinningProbabilityAtLossAsFavouriteLastYear  { get; set; }
        public double  ? Player1AverageWinningProbabilityAtLossAsUnderdogLastYear   { get; set; }
        public double  ? Player2AverageWinningProbabilityAtLossAsUnderdogLastYear   { get; set; }
        public int     ? Player1TotalWinsAsFavouriteLastMonth                       { get; set; }
        public int     ? Player2TotalWinsAsFavouriteLastMonth                       { get; set; }
        public int     ? Player1TotalWinsAsUnderdogLastMonth                        { get; set; }
        public int     ? Player2TotalWinsAsUnderdogLastMonth                        { get; set; }
        public int     ? Player1TotalLossesAsFavouriteLastMonth                     { get; set; }
        public int     ? Player2TotalLossesAsFavouriteLastMonth                     { get; set; }
        public int     ? Player1TotalLossesAsUnderdogLastMonth                      { get; set; }
        public int     ? Player2TotalLossesAsUnderdogLastMonth                      { get; set; }
        public double  ? Player1AverageWinningProbabilityAtWonAsFavouriteLastMonth  { get; set; }
        public double  ? Player2AverageWinningProbabilityAtWonAsFavouriteLastMonth  { get; set; }
        public double  ? Player1AverageWinningProbabilityAtWonAsUnderdogLastMonth   { get; set; }
        public double  ? Player2AverageWinningProbabilityAtWonAsUnderdogLastMonth   { get; set; }
        public double  ? Player1AverageWinningProbabilityAtLossAsFavouriteLastMonth { get; set; }
        public double  ? Player2AverageWinningProbabilityAtLossAsFavouriteLastMonth { get; set; }
        public double  ? Player1AverageWinningProbabilityAtLossAsUnderdogLastMonth  { get; set; }
        public double  ? Player2AverageWinningProbabilityAtLossAsUnderdogLastMonth  { get; set; }
        public int     ? Player1TotalWinsAsFavouriteLastWeek                        { get; set; }
        public int     ? Player2TotalWinsAsFavouriteLastWeek                        { get; set; }
        public int     ? Player1TotalWinsAsUnderdogLastWeek                         { get; set; }
        public int     ? Player2TotalWinsAsUnderdogLastWeek                         { get; set; }
        public int     ? Player1TotalLossesAsFavouriteLastWeek                      { get; set; }
        public int     ? Player2TotalLossesAsFavouriteLastWeek                      { get; set; }
        public int     ? Player1TotalLossesAsUnderdogLastWeek                       { get; set; }
        public int     ? Player2TotalLossesAsUnderdogLastWeek                       { get; set; }
        public double  ? Player1AverageWinningProbabilityAtWonAsFavouriteLastWeek   { get; set; }
        public double  ? Player2AverageWinningProbabilityAtWonAsFavouriteLastWeek   { get; set; }
        public double  ? Player1AverageWinningProbabilityAtWonAsUnderdogLastWeek    { get; set; }
        public double  ? Player2AverageWinningProbabilityAtWonAsUnderdogLastWeek    { get; set; }
        public double  ? Player1AverageWinningProbabilityAtLossAsFavouriteLastWeek  { get; set; }
        public double  ? Player2AverageWinningProbabilityAtLossAsFavouriteLastWeek  { get; set; }
        public double  ? Player1AverageWinningProbabilityAtLossAsUnderdogLastWeek   { get; set; }
        public double  ? Player2AverageWinningProbabilityAtLossAsUnderdogLastWeek   { get; set; }
        public int     ? Player1H2HOld                                              { get; set; }
        public int     ? Player2H2HOld                                              { get; set; }
        public double  ? Player1H2HTrueSkillMeanOldM                                { get; set; }
        public double  ? Player1H2HTrueSkillStandardDeviationOldM                   { get; set; }
        public double  ? Player2H2HTrueSkillMeanOldM                                { get; set; }
        public double  ? Player2H2HTrueSkillStandardDeviationOldM                   { get; set; }
        public double  ? WinProbabilityPlayer1H2HM                                  { get; set; }
        public double  ? Player1H2HTrueSkillMeanOldSM                               { get; set; }
        public double  ? Player1H2HTrueSkillStandardDeviationOldSM                  { get; set; }
        public double  ? Player2H2HTrueSkillMeanOldSM                               { get; set; }
        public double  ? Player2H2HTrueSkillStandardDeviationOldSM                  { get; set; }
        public double  ? WinProbabilityPlayer1H2HSM                                 { get; set; }
        public double  ? Player1H2HTrueSkillMeanOldGSM                              { get; set; }
        public double  ? Player1H2HTrueSkillStandardDeviationOldGSM                 { get; set; }
        public double  ? Player2H2HTrueSkillMeanOldGSM                              { get; set; }
        public double  ? Player2H2HTrueSkillStandardDeviationOldGSM                 { get; set; }
        public double  ? WinProbabilityPlayer1H2HGSM                                { get; set; }
        public int     ? Player1H2HOldS1                                            { get; set; }
        public int     ? Player2H2HOldS1                                            { get; set; }
        public double  ? Player1H2HTrueSkillMeanOldMS1                              { get; set; }
        public double  ? Player1H2HTrueSkillStandardDeviationOldMS1                 { get; set; }
        public double  ? Player2H2HTrueSkillMeanOldMS1                              { get; set; }
        public double  ? Player2H2HTrueSkillStandardDeviationOldMS1                 { get; set; }
        public double  ? WinProbabilityPlayer1H2HMS1                                { get; set; }
        public double  ? Player1H2HTrueSkillMeanOldSMS1                             { get; set; }
        public double  ? Player1H2HTrueSkillStandardDeviationOldSMS1                { get; set; }
        public double  ? Player2H2HTrueSkillMeanOldSMS1                             { get; set; }
        public double  ? Player2H2HTrueSkillStandardDeviationOldSMS1                { get; set; }
        public double  ? WinProbabilityPlayer1H2HSMS1                               { get; set; }
        public double  ? Player1H2HTrueSkillMeanOldGSMS1                            { get; set; }
        public double  ? Player1H2HTrueSkillStandardDeviationOldGSMS1               { get; set; }
        public double  ? Player2H2HTrueSkillMeanOldGSMS1                            { get; set; }
        public double  ? Player2H2HTrueSkillStandardDeviationOldGSMS1               { get; set; }
        public double  ? WinProbabilityPlayer1H2HGSMS1                              { get; set; }
        public int     ? Player1H2HOldS2                                            { get; set; }
        public int     ? Player2H2HOldS2                                            { get; set; }
        public double  ? Player1H2HTrueSkillMeanOldMS2                              { get; set; }
        public double  ? Player1H2HTrueSkillStandardDeviationOldMS2                 { get; set; }
        public double  ? Player2H2HTrueSkillMeanOldMS2                              { get; set; }
        public double  ? Player2H2HTrueSkillStandardDeviationOldMS2                 { get; set; }
        public double  ? WinProbabilityPlayer1H2HMS2                                { get; set; }
        public double  ? Player1H2HTrueSkillMeanOldSMS2                             { get; set; }
        public double  ? Player1H2HTrueSkillStandardDeviationOldSMS2                { get; set; }
        public double  ? Player2H2HTrueSkillMeanOldSMS2                             { get; set; }
        public double  ? Player2H2HTrueSkillStandardDeviationOldSMS2                { get; set; }
        public double  ? WinProbabilityPlayer1H2HSMS2                               { get; set; }
        public double  ? Player1H2HTrueSkillMeanOldGSMS2                            { get; set; }
        public double  ? Player1H2HTrueSkillStandardDeviationOldGSMS2               { get; set; }
        public double  ? Player2H2HTrueSkillMeanOldGSMS2                            { get; set; }
        public double  ? Player2H2HTrueSkillStandardDeviationOldGSMS2               { get; set; }
        public double  ? WinProbabilityPlayer1H2HGSMS2                              { get; set; }
        public int     ? Player1H2HOldS3                                            { get; set; }
        public int     ? Player2H2HOldS3                                            { get; set; }
        public double  ? Player1H2HTrueSkillMeanOldMS3                              { get; set; }
        public double  ? Player1H2HTrueSkillStandardDeviationOldMS3                 { get; set; }
        public double  ? Player2H2HTrueSkillMeanOldMS3                              { get; set; }
        public double  ? Player2H2HTrueSkillStandardDeviationOldMS3                 { get; set; }
        public double  ? WinProbabilityPlayer1H2HMS3                                { get; set; }
        public double  ? Player1H2HTrueSkillMeanOldSMS3                             { get; set; }
        public double  ? Player1H2HTrueSkillStandardDeviationOldSMS3                { get; set; }
        public double  ? Player2H2HTrueSkillMeanOldSMS3                             { get; set; }
        public double  ? Player2H2HTrueSkillStandardDeviationOldSMS3                { get; set; }
        public double  ? WinProbabilityPlayer1H2HSMS3                               { get; set; }
        public double  ? Player1H2HTrueSkillMeanOldGSMS3                            { get; set; }
        public double  ? Player1H2HTrueSkillStandardDeviationOldGSMS3               { get; set; }
        public double  ? Player2H2HTrueSkillMeanOldGSMS3                            { get; set; }
        public double  ? Player2H2HTrueSkillStandardDeviationOldGSMS3               { get; set; }
        public double  ? WinProbabilityPlayer1H2HGSMS3                              { get; set; }
        public int     ? Player1H2HOldS4                                            { get; set; }
        public int     ? Player2H2HOldS4                                            { get; set; }
        public double  ? Player1H2HTrueSkillMeanOldMS4                              { get; set; }
        public double  ? Player1H2HTrueSkillStandardDeviationOldMS4                 { get; set; }
        public double  ? Player2H2HTrueSkillMeanOldMS4                              { get; set; }
        public double  ? Player2H2HTrueSkillStandardDeviationOldMS4                 { get; set; }
        public double  ? WinProbabilityPlayer1H2HMS4                                { get; set; }
        public double  ? Player1H2HTrueSkillMeanOldSMS4                             { get; set; }
        public double  ? Player1H2HTrueSkillStandardDeviationOldSMS4                { get; set; }
        public double  ? Player2H2HTrueSkillMeanOldSMS4                             { get; set; }
        public double  ? Player2H2HTrueSkillStandardDeviationOldSMS4                { get; set; }
        public double  ? WinProbabilityPlayer1H2HSMS4                               { get; set; }
        public double  ? Player1H2HTrueSkillMeanOldGSMS4                            { get; set; }
        public double  ? Player1H2HTrueSkillStandardDeviationOldGSMS4               { get; set; }
        public double  ? Player2H2HTrueSkillMeanOldGSMS4                            { get; set; }
        public double  ? Player2H2HTrueSkillStandardDeviationOldGSMS4               { get; set; }
        public double  ? WinProbabilityPlayer1H2HGSMS4                              { get; set; }
        public int     ? Player1Streak                                              { get; set; }
        public int     ? Player2Streak                                              { get; set; }
        public int     ? Player1StreakS1                                            { get; set; }
        public int     ? Player2StreakS1                                            { get; set; }
        public int     ? Player1StreakS2                                            { get; set; }
        public int     ? Player2StreakS2                                            { get; set; }
        public int     ? Player1StreakS3                                            { get; set; }
        public int     ? Player2StreakS3                                            { get; set; }
        public int     ? Player1StreakS4                                            { get; set; }
        public int     ? Player2StreakS4                                            { get; set; }
        public int     ? P1SetsWon                                                  { get; set; }
        public int     ? P2SetsWon                                                  { get; set; }
        public int     ? P1GamesWon                                                 { get; set; }
        public int     ? P2GamesWon                                                 { get; set; }
        public int     ? P1SetsLoss                                                 { get; set; }
        public int     ? P2SetsLoss                                                 { get; set; }
        public int     ? P1GamesLoss                                                { get; set; }
        public int     ? P2GamesLoss                                                { get; set; }
        public double  ? WinProbabilityNN                                           { get; set; }
    }
}