namespace BonzoByte.Core.Models
{
    public class Player
    {
        public int     ? PlayerTPId                                          { get; set; }
        public string  ? PlayerName                                          { get; set; }
        public int     ? CountryTPId                                         { get; set; }
        public DateTime? PlayerBirthDate                                     { get; set; }
        public int     ? PlayerHeight                                        { get; set; }
        public int     ? PlayerWeight                                        { get; set; }
        public int     ? PlayerTurnedPro                                     { get; set; }
        public int     ? PlaysId                                             { get; set; }
        public int     ? TournamentTypeId                                    { get; set; }
        public double  ? TrueSkillMeanM                                      { get; set; }
        public double  ? TrueSkillStandardDeviationM                         { get; set; }
        public double  ? TrueSkillMeanSM                                     { get; set; }
        public double  ? TrueSkillStandardDeviationSM                        { get; set; }
        public double  ? TrueSkillMeanGSM                                    { get; set; }
        public double  ? TrueSkillStandardDeviationGSM                       { get; set; }
        public double  ? TrueSkillMeanMS1                                    { get; set; }
        public double  ? TrueSkillStandardDeviationMS1                       { get; set; }
        public double  ? TrueSkillMeanSMS1                                   { get; set; }
        public double  ? TrueSkillStandardDeviationSMS1                      { get; set; }
        public double  ? TrueSkillMeanGSMS1                                  { get; set; }
        public double  ? TrueSkillStandardDeviationGSMS1                     { get; set; }
        public double  ? TrueSkillMeanMS2                                    { get; set; }
        public double  ? TrueSkillStandardDeviationMS2                       { get; set; }
        public double  ? TrueSkillMeanSMS2                                   { get; set; }
        public double  ? TrueSkillStandardDeviationSMS2                      { get; set; }
        public double  ? TrueSkillMeanGSMS2                                  { get; set; }
        public double  ? TrueSkillStandardDeviationGSMS2                     { get; set; }
        public double  ? TrueSkillMeanMS3                                    { get; set; }
        public double  ? TrueSkillStandardDeviationMS3                       { get; set; }
        public double  ? TrueSkillMeanSMS3                                   { get; set; }
        public double  ? TrueSkillStandardDeviationSMS3                      { get; set; }
        public double  ? TrueSkillMeanGSMS3                                  { get; set; }
        public double  ? TrueSkillStandardDeviationGSMS3                     { get; set; }
        public double  ? TrueSkillMeanMS4                                    { get; set; }
        public double  ? TrueSkillStandardDeviationMS4                       { get; set; }
        public double  ? TrueSkillMeanSMS4                                   { get; set; }
        public double  ? TrueSkillStandardDeviationSMS4                      { get; set; }
        public double  ? TrueSkillMeanGSMS4                                  { get; set; }
        public double  ? TrueSkillStandardDeviationGSMS4                     { get; set; }
        public int     ? WinsTotal                                           { get; set; }
        public int     ? LossesTotal                                         { get; set; }
        public int     ? WinsLastYear                                        { get; set; }
        public int     ? LossesLastYear                                      { get; set; }
        public int     ? WinsLastMonth                                       { get; set; }
        public int     ? LossesLastMonth                                     { get; set; }
        public int     ? WinsLastWeek                                        { get; set; }
        public int     ? LossesLastWeek                                      { get; set; }
        public int     ? WinsTotalS1                                         { get; set; }
        public int     ? LossesTotalS1                                       { get; set; }
        public int     ? WinsLastYearS1                                      { get; set; }
        public int     ? LossesLastYearS1                                    { get; set; }
        public int     ? WinsLastMonthS1                                     { get; set; }
        public int     ? LossesLastMonthS1                                   { get; set; }
        public int     ? WinsLastWeekS1                                      { get; set; }
        public int     ? LossesLastWeekS1                                    { get; set; }
        public int     ? WinsTotalS2                                         { get; set; }
        public int     ? LossesTotalS2                                       { get; set; }
        public int     ? WinsLastYearS2                                      { get; set; }
        public int     ? LossesLastYearS2                                    { get; set; }
        public int     ? WinsLastMonthS2                                     { get; set; }
        public int     ? LossesLastMonthS2                                   { get; set; }
        public int     ? WinsLastWeekS2                                      { get; set; }
        public int     ? LossesLastWeekS2                                    { get; set; }
        public int     ? WinsTotalS3                                         { get; set; }
        public int     ? LossesTotalS3                                       { get; set; }
        public int     ? WinsLastYearS3                                      { get; set; }
        public int     ? LossesLastYearS3                                    { get; set; }
        public int     ? WinsLastMonthS3                                     { get; set; }
        public int     ? LossesLastMonthS3                                   { get; set; }
        public int     ? WinsLastWeekS3                                      { get; set; }
        public int     ? LossesLastWeekS3                                    { get; set; }
        public int     ? WinsTotalS4                                         { get; set; }
        public int     ? LossesTotalS4                                       { get; set; }
        public int     ? WinsLastYearS4                                      { get; set; }
        public int     ? LossesLastYearS4                                    { get; set; }
        public int     ? WinsLastMonthS4                                     { get; set; }
        public int     ? LossesLastMonthS4                                   { get; set; }
        public int     ? WinsLastWeekS4                                      { get; set; }
        public int     ? LossesLastWeekS4                                    { get; set; }
        public int     ? WinsSetsTotal                                       { get; set; }
        public int     ? LossesSetsTotal                                     { get; set; }
        public int     ? WinsSetsLastYear                                    { get; set; }
        public int     ? LossesSetsLastYear                                  { get; set; }
        public int     ? WinsSetsLastMonth                                   { get; set; }
        public int     ? LossesSetsLastMonth                                 { get; set; }
        public int     ? WinsSetsLastWeek                                    { get; set; }
        public int     ? LossesSetsLastWeek                                  { get; set; }
        public int     ? WinsSetsTotalS1                                     { get; set; }
        public int     ? LossesSetsTotalS1                                   { get; set; }
        public int     ? WinsSetsLastYearS1                                  { get; set; }
        public int     ? LossesSetsLastYearS1                                { get; set; }
        public int     ? WinsSetsLastMonthS1                                 { get; set; }
        public int     ? LossesSetsLastMonthS1                               { get; set; }
        public int     ? WinsSetsLastWeekS1                                  { get; set; }
        public int     ? LossesSetsLastWeekS1                                { get; set; }
        public int     ? WinsSetsTotalS2                                     { get; set; }
        public int     ? LossesSetsTotalS2                                   { get; set; }
        public int     ? WinsSetsLastYearS2                                  { get; set; }
        public int     ? LossesSetsLastYearS2                                { get; set; }
        public int     ? WinsSetsLastMonthS2                                 { get; set; }
        public int     ? LossesSetsLastMonthS2                               { get; set; }
        public int     ? WinsSetsLastWeekS2                                  { get; set; }
        public int     ? LossesSetsLastWeekS2                                { get; set; }
        public int     ? WinsSetsTotalS3                                     { get; set; }
        public int     ? LossesSetsTotalS3                                   { get; set; }
        public int     ? WinsSetsLastYearS3                                  { get; set; }
        public int     ? LossesSetsLastYearS3                                { get; set; }
        public int     ? WinsSetsLastMonthS3                                 { get; set; }
        public int     ? LossesSetsLastMonthS3                               { get; set; }
        public int     ? WinsSetsLastWeekS3                                  { get; set; }
        public int     ? LossesSetsLastWeekS3                                { get; set; }
        public int     ? WinsSetsTotalS4                                     { get; set; }
        public int     ? LossesSetsTotalS4                                   { get; set; }
        public int     ? WinsSetsLastYearS4                                  { get; set; }
        public int     ? LossesSetsLastYearS4                                { get; set; }
        public int     ? WinsSetsLastMonthS4                                 { get; set; }
        public int     ? LossesSetsLastMonthS4                               { get; set; }
        public int     ? WinsSetsLastWeekS4                                  { get; set; }
        public int     ? LossesSetsLastWeekS4                                { get; set; }
        public int     ? WinsGamesTotal                                      { get; set; }
        public int     ? LossesGamesTotal                                    { get; set; }
        public int     ? WinsGamesLastYear                                   { get; set; }
        public int     ? LossesGamesLastYear                                 { get; set; }
        public int     ? WinsGamesLastMonth                                  { get; set; }
        public int     ? LossesGamesLastMonth                                { get; set; }
        public int     ? WinsGamesLastWeek                                   { get; set; }
        public int     ? LossesGamesLastWeek                                 { get; set; }
        public int     ? WinsGamesTotalS1                                    { get; set; }
        public int     ? LossesGamesTotalS1                                  { get; set; }
        public int     ? WinsGamesLastYearS1                                 { get; set; }
        public int     ? LossesGamesLastYearS1                               { get; set; }
        public int     ? WinsGamesLastMonthS1                                { get; set; }
        public int     ? LossesGamesLastMonthS1                              { get; set; }
        public int     ? WinsGamesLastWeekS1                                 { get; set; }
        public int     ? LossesGamesLastWeekS1                               { get; set; }
        public int     ? WinsGamesTotalS2                                    { get; set; }
        public int     ? LossesGamesTotalS2                                  { get; set; }
        public int     ? WinsGamesLastYearS2                                 { get; set; }
        public int     ? LossesGamesLastYearS2                               { get; set; }
        public int     ? WinsGamesLastMonthS2                                { get; set; }
        public int     ? LossesGamesLastMonthS2                              { get; set; }
        public int     ? WinsGamesLastWeekS2                                 { get; set; }
        public int     ? LossesGamesLastWeekS2                               { get; set; }
        public int     ? WinsGamesTotalS3                                    { get; set; }
        public int     ? LossesGamesTotalS3                                  { get; set; }
        public int     ? WinsGamesLastYearS3                                 { get; set; }
        public int     ? LossesGamesLastYearS3                               { get; set; }
        public int     ? WinsGamesLastMonthS3                                { get; set; }
        public int     ? LossesGamesLastMonthS3                              { get; set; }
        public int     ? WinsGamesLastWeekS3                                 { get; set; }
        public int     ? LossesGamesLastWeekS3                               { get; set; }
        public int     ? WinsGamesTotalS4                                    { get; set; }
        public int     ? LossesGamesTotalS4                                  { get; set; }
        public int     ? WinsGamesLastYearS4                                 { get; set; }
        public int     ? LossesGamesLastYearS4                               { get; set; }
        public int     ? WinsGamesLastMonthS4                                { get; set; }
        public int     ? LossesGamesLastMonthS4                              { get; set; }
        public int     ? WinsGamesLastWeekS4                                 { get; set; }
        public int     ? LossesGamesLastWeekS4                               { get; set; }
        public DateTime? DateSinceLastWin                                    { get; set; }
        public DateTime? DateSinceLastWinS1                                  { get; set; }
        public DateTime? DateSinceLastWinS2                                  { get; set; }
        public DateTime? DateSinceLastWinS3                                  { get; set; }
        public DateTime? DateSinceLastWinS4                                  { get; set; }
        public DateTime? DateSinceLastLoss                                   { get; set; }
        public DateTime? DateSinceLastLossS1                                 { get; set; }
        public DateTime? DateSinceLastLossS2                                 { get; set; }
        public DateTime? DateSinceLastLossS3                                 { get; set; }
        public DateTime? DateSinceLastLossS4                                 { get; set; }
        public int     ? TotalWinsAsFavourite                                { get; set; }
        public int     ? TotalWinsAsUnderdog                                 { get; set; }
        public int     ? TotalLossesAsFavourite                              { get; set; }
        public int     ? TotalLossesAsUnderdog                               { get; set; }
        public double  ? WinsAsFavouriteRatio                                { get; set; }
        public double  ? LossesAsFavouriteRatio                              { get; set; }
        public double  ? WinsAsUnderdogRatio                                 { get; set; }
        public double  ? LossesAsUnderdogRatio                               { get; set; }
        public double  ? AverageWinningProbabilityAtWonAsFavourite           { get; set; }
        public double  ? AverageWinningProbabilityAtWonAsUnderdog            { get; set; }
        public double  ? AverageWinningProbabilityAtLossAsFavourite          { get; set; }
        public double  ? AverageWinningProbabilityAtLossAsUnderdog           { get; set; }
        public int     ? TotalWinsAsFavouriteLastYear                        { get; set; }
        public int     ? TotalWinsAsUnderdogLastYear                         { get; set; }
        public int     ? TotalLossesAsFavouriteLastYear                      { get; set; }
        public int     ? TotalLossesAsUnderdogLastYear                       { get; set; }
        public double  ? WinsAsFavouriteLastYearRatio                        { get; set; }
        public double  ? LossesAsFavouriteLastYearRatio                      { get; set; }
        public double  ? WinsAsUnderdogLastYearRatio                         { get; set; }
        public double  ? LossesAsUnderdogLastYearRatio                       { get; set; }
        public double  ? AverageWinningProbabilityAtWonAsFavouriteLastYear   { get; set; }
        public double  ? AverageWinningProbabilityAtWonAsUnderdogLastYear    { get; set; }
        public double  ? AverageWinningProbabilityAtLossAsFavouriteLastYear  { get; set; }
        public double  ? AverageWinningProbabilityAtLossAsUnderdogLastYear   { get; set; }
        public int     ? TotalWinsAsFavouriteLastMonth                       { get; set; }
        public int     ? TotalWinsAsUnderdogLastMonth                        { get; set; }
        public int     ? TotalLossesAsFavouriteLastMonth                     { get; set; }
        public int     ? TotalLossesAsUnderdogLastMonth                      { get; set; }
        public double  ? WinsAsFavouriteLastMonthRatio                       { get; set; }
        public double  ? LossesAsFavouriteLastMonthRatio                     { get; set; }
        public double  ? WinsAsUnderdogLastMonthRatio                        { get; set; }
        public double  ? LossesAsUnderdogLastMonthRatio                      { get; set; }
        public double  ? AverageWinningProbabilityAtWonAsFavouriteLastMonth  { get; set; }
        public double  ? AverageWinningProbabilityAtWonAsUnderdogLastMonth   { get; set; }
        public double  ? AverageWinningProbabilityAtLossAsFavouriteLastMonth { get; set; }
        public double  ? AverageWinningProbabilityAtLossAsUnderdogLastMonth  { get; set; }
        public int     ? TotalWinsAsFavouriteLastWeek                        { get; set; }
        public int     ? TotalWinsAsUnderdogLastWeek                         { get; set; }
        public int     ? TotalLossesAsFavouriteLastWeek                      { get; set; }
        public int     ? TotalLossesAsUnderdogLastWeek                       { get; set; }
        public double  ? WinsAsFavouriteLastWeekRatio                        { get; set; }
        public double  ? LossesAsFavouriteLastWeekRatio                      { get; set; }
        public double  ? WinsAsUnderdogLastWeekRatio                         { get; set; }
        public double  ? LossesAsUnderdogLastWeekRatio                       { get; set; }
        public double  ? AverageWinningProbabilityAtWonAsFavouriteLastWeek   { get; set; }
        public double  ? AverageWinningProbabilityAtWonAsUnderdogLastWeek    { get; set; }
        public double  ? AverageWinningProbabilityAtLossAsFavouriteLastWeek  { get; set; }
        public double  ? AverageWinningProbabilityAtLossAsUnderdogLastWeek   { get; set; }
        public int     ? Streak                                              { get; set; }
        public int     ? StreakS1                                            { get; set; }
        public int     ? StreakS2                                            { get; set; }
        public int     ? StreakS3                                            { get; set; }
        public int     ? StreakS4                                            { get; set; }
    }
}