using BonzoByte.Core.DAL.Repositories;
using BonzoByte.Core.Models;
using Moserware.Skills;

namespace BonzoByte.Core.Helpers;

public static class WinLossHelper
{
    public static void UpdateWinLossByTimeFrame(List<Models.Match> lastWeekMatchesToRemove, List<Models.Match> lastMonthMatchesToRemove, List<Models.Match> lastYearMatchesToRemove, List<Models.Player>? players)
    {
        foreach (var m in lastWeekMatchesToRemove)
        {
            var p1 = players!.Find(p => p.PlayerTPId == m.Player1TPId);
            var p2 = players!.Find(p => p.PlayerTPId == m.Player2TPId);

            p1!.WinsLastWeek--;
            p2!.LossesLastWeek--;
            p1!.WinsSetsLastWeek -= m.P1SetsWon;
            p2!.WinsSetsLastWeek -= m.P2SetsWon;
            p1!.LossesSetsLastWeek -= m.P1SetsLoss;
            p2!.LossesSetsLastWeek -= m.P2SetsLoss;
            p1!.WinsGamesLastWeek -= m.P1GamesWon;
            p2!.WinsGamesLastWeek -= m.P2GamesWon;
            p1!.LossesGamesLastWeek -= m.P1GamesLoss;
            p2!.LossesGamesLastWeek -= m.P2GamesLoss;

            switch (m.SurfaceId)
            {
                case 1:
                    p1!.WinsLastWeekS1--;
                    p2!.LossesLastWeekS1--;
                    p1!.WinsSetsLastWeekS1 -= m.P1SetsWon;
                    p2!.WinsSetsLastWeekS1 -= m.P2SetsWon;
                    p1!.LossesSetsLastWeekS1 -= m.P1SetsLoss;
                    p2!.LossesSetsLastWeekS1 -= m.P2SetsLoss;
                    p1!.WinsGamesLastWeekS1 -= m.P1GamesWon;
                    p2!.WinsGamesLastWeekS1 -= m.P2GamesWon;
                    p1!.LossesGamesLastWeekS1 -= m.P1GamesLoss;
                    p2!.LossesGamesLastWeekS1 -= m.P2GamesLoss;
                    break;
                case 2:
                    p1!.WinsLastWeekS2--;
                    p2!.LossesLastWeekS2--;
                    p1!.WinsSetsLastWeekS2 -= m.P1SetsWon;
                    p2!.WinsSetsLastWeekS2 -= m.P2SetsWon;
                    p1!.LossesSetsLastWeekS2 -= m.P1SetsLoss;
                    p2!.LossesSetsLastWeekS2 -= m.P2SetsLoss;
                    p1!.WinsGamesLastWeekS2 -= m.P1GamesWon;
                    p2!.WinsGamesLastWeekS2 -= m.P2GamesWon;
                    p1!.LossesGamesLastWeekS2 -= m.P1GamesLoss;
                    p2!.LossesGamesLastWeekS2 -= m.P2GamesLoss;
                    break;
                case 3:
                    p1!.WinsLastWeekS3--;
                    p2!.LossesLastWeekS3--;
                    p1!.WinsSetsLastWeekS3 -= m.P1SetsWon;
                    p2!.WinsSetsLastWeekS3 -= m.P2SetsWon;
                    p1!.LossesSetsLastWeekS3 -= m.P1SetsLoss;
                    p2!.LossesSetsLastWeekS3 -= m.P2SetsLoss;
                    p1!.WinsGamesLastWeekS3 -= m.P1GamesWon;
                    p2!.WinsGamesLastWeekS3 -= m.P2GamesWon;
                    p1!.LossesGamesLastWeekS3 -= m.P1GamesLoss;
                    p2!.LossesGamesLastWeekS3 -= m.P2GamesLoss;
                    break;
                case 4:
                    p1!.WinsLastWeekS4--;
                    p2!.LossesLastWeekS4--;
                    p1!.WinsSetsLastWeekS4 -= m.P1SetsWon;
                    p2!.WinsSetsLastWeekS4 -= m.P2SetsWon;
                    p1!.LossesSetsLastWeekS4 -= m.P1SetsLoss;
                    p2!.LossesSetsLastWeekS4 -= m.P2SetsLoss;
                    p1!.WinsGamesLastWeekS4 -= m.P1GamesWon;
                    p2!.WinsGamesLastWeekS4 -= m.P2GamesWon;
                    p1!.LossesGamesLastWeekS4 -= m.P1GamesLoss;
                    p2!.LossesGamesLastWeekS4 -= m.P2GamesLoss;
                    break;
                default:
                    break;
            }
        }

        foreach (var m in lastMonthMatchesToRemove)
        {
            var p1 = players!.Find(p => p.PlayerTPId == m.Player1TPId);
            var p2 = players!.Find(p => p.PlayerTPId == m.Player2TPId);

            p1!.WinsLastMonth--;
            p2!.LossesLastMonth--;
            p1!.WinsSetsLastMonth -= m.P1SetsWon;
            p2!.WinsSetsLastMonth -= m.P2SetsWon;
            p1!.LossesSetsLastMonth -= m.P1SetsLoss;
            p2!.LossesSetsLastMonth -= m.P2SetsLoss;
            p1!.WinsGamesLastMonth -= m.P1GamesWon;
            p2!.WinsGamesLastMonth -= m.P2GamesWon;
            p1!.LossesGamesLastMonth -= m.P1GamesLoss;
            p2!.LossesGamesLastMonth -= m.P2GamesLoss;

            switch (m.SurfaceId)
            {
                case 1:
                    p1!.WinsLastMonthS1--;
                    p2!.LossesLastMonthS1--;
                    p1!.WinsSetsLastMonthS1 -= m.P1SetsWon;
                    p2!.WinsSetsLastMonthS1 -= m.P2SetsWon;
                    p1!.LossesSetsLastMonthS1 -= m.P1SetsLoss;
                    p2!.LossesSetsLastMonthS1 -= m.P2SetsLoss;
                    p1!.WinsGamesLastMonthS1 -= m.P1GamesWon;
                    p2!.WinsGamesLastMonthS1 -= m.P2GamesWon;
                    p1!.LossesGamesLastMonthS1 -= m.P1GamesLoss;
                    p2!.LossesGamesLastMonthS1 -= m.P2GamesLoss;
                    break;
                case 2:
                    p1!.WinsLastMonthS2--;
                    p2!.LossesLastMonthS2--;
                    p1!.WinsSetsLastMonthS2 -= m.P1SetsWon;
                    p2!.WinsSetsLastMonthS2 -= m.P2SetsWon;
                    p1!.LossesSetsLastMonthS2 -= m.P1SetsLoss;
                    p2!.LossesSetsLastMonthS2 -= m.P2SetsLoss;
                    p1!.WinsGamesLastMonthS2 -= m.P1GamesWon;
                    p2!.WinsGamesLastMonthS2 -= m.P2GamesWon;
                    p1!.LossesGamesLastMonthS2 -= m.P1GamesLoss;
                    p2!.LossesGamesLastMonthS2 -= m.P2GamesLoss;
                    break;
                case 3:
                    p1!.WinsLastMonthS3--;
                    p2!.LossesLastMonthS3--;
                    p1!.WinsSetsLastMonthS3 -= m.P1SetsWon;
                    p2!.WinsSetsLastMonthS3 -= m.P2SetsWon;
                    p1!.LossesSetsLastMonthS3 -= m.P1SetsLoss;
                    p2!.LossesSetsLastMonthS3 -= m.P2SetsLoss;
                    p1!.WinsGamesLastMonthS3 -= m.P1GamesWon;
                    p2!.WinsGamesLastMonthS3 -= m.P2GamesWon;
                    p1!.LossesGamesLastMonthS3 -= m.P1GamesLoss;
                    p2!.LossesGamesLastMonthS3 -= m.P2GamesLoss;
                    break;
                case 4:
                    p1!.WinsLastMonthS4--;
                    p2!.LossesLastMonthS4--;
                    p1!.WinsSetsLastMonthS4 -= m.P1SetsWon;
                    p2!.WinsSetsLastMonthS4 -= m.P2SetsWon;
                    p1!.LossesSetsLastMonthS4 -= m.P1SetsLoss;
                    p2!.LossesSetsLastMonthS4 -= m.P2SetsLoss;
                    p1!.WinsGamesLastMonthS4 -= m.P1GamesWon;
                    p2!.WinsGamesLastMonthS4 -= m.P2GamesWon;
                    p1!.LossesGamesLastMonthS4 -= m.P1GamesLoss;
                    p2!.LossesGamesLastMonthS4 -= m.P2GamesLoss;
                    break;
                default:
                    break;
            }
        }

        foreach (var m in lastYearMatchesToRemove)
        {
            var p1 = players!.Find(p => p.PlayerTPId == m.Player1TPId);
            var p2 = players!.Find(p => p.PlayerTPId == m.Player2TPId);

            p1!.WinsLastYear--;
            p2!.LossesLastYear--;
            p1!.WinsSetsLastYear -= m.P1SetsWon;
            p2!.WinsSetsLastYear -= m.P2SetsWon;
            p1!.LossesSetsLastYear -= m.P1SetsLoss;
            p2!.LossesSetsLastYear -= m.P2SetsLoss;
            p1!.WinsGamesLastYear -= m.P1GamesWon;
            p2!.WinsGamesLastYear -= m.P2GamesWon;
            p1!.LossesGamesLastYear -= m.P1GamesLoss;
            p2!.LossesGamesLastYear -= m.P2GamesLoss;

            switch (m.SurfaceId)
            {
                case 1:
                    p1!.WinsLastYearS1--;
                    p2!.LossesLastYearS1--;
                    p1!.WinsSetsLastYearS1 -= m.P1SetsWon;
                    p2!.WinsSetsLastYearS1 -= m.P2SetsWon;
                    p1!.LossesSetsLastYearS1 -= m.P1SetsLoss;
                    p2!.LossesSetsLastYearS1 -= m.P2SetsLoss;
                    p1!.WinsGamesLastYearS1 -= m.P1GamesWon;
                    p2!.WinsGamesLastYearS1 -= m.P2GamesWon;
                    p1!.LossesGamesLastYearS1 -= m.P1GamesLoss;
                    p2!.LossesGamesLastYearS1 -= m.P2GamesLoss;
                    break;
                case 2:
                    p1!.WinsLastYearS2--;
                    p2!.LossesLastYearS2--;
                    p1!.WinsSetsLastYearS2 -= m.P1SetsWon;
                    p2!.WinsSetsLastYearS2 -= m.P2SetsWon;
                    p1!.LossesSetsLastYearS2 -= m.P1SetsLoss;
                    p2!.LossesSetsLastYearS2 -= m.P2SetsLoss;
                    p1!.WinsGamesLastYearS2 -= m.P1GamesWon;
                    p2!.WinsGamesLastYearS2 -= m.P2GamesWon;
                    p1!.LossesGamesLastYearS2 -= m.P1GamesLoss;
                    p2!.LossesGamesLastYearS2 -= m.P2GamesLoss;
                    break;
                case 3:
                    p1!.WinsLastYearS3--;
                    p2!.LossesLastYearS3--;
                    p1!.WinsSetsLastYearS3 -= m.P1SetsWon;
                    p2!.WinsSetsLastYearS3 -= m.P2SetsWon;
                    p1!.LossesSetsLastYearS3 -= m.P1SetsLoss;
                    p2!.LossesSetsLastYearS3 -= m.P2SetsLoss;
                    p1!.WinsGamesLastYearS3 -= m.P1GamesWon;
                    p2!.WinsGamesLastYearS3 -= m.P2GamesWon;
                    p1!.LossesGamesLastYearS3 -= m.P1GamesLoss;
                    p2!.LossesGamesLastYearS3 -= m.P2GamesLoss;
                    break;
                case 4:
                    p1!.WinsLastYearS4--;
                    p2!.LossesLastYearS4--;
                    p1!.WinsSetsLastYearS4 -= m.P1SetsWon;
                    p2!.WinsSetsLastYearS4 -= m.P2SetsWon;
                    p1!.LossesSetsLastYearS4 -= m.P1SetsLoss;
                    p2!.LossesSetsLastYearS4 -= m.P2SetsLoss;
                    p1!.WinsGamesLastYearS4 -= m.P1GamesWon;
                    p2!.WinsGamesLastYearS4 -= m.P2GamesWon;
                    p1!.LossesGamesLastYearS4 -= m.P1GamesLoss;
                    p2!.LossesGamesLastYearS4 -= m.P2GamesLoss;
                    break;
                default:
                    break;
            }
        }
    }

    public static void UpdateMatchWinLoss(Models.Match match, Models.Player p1, Models.Player p2)
    {
        match.Player1WinsTotal              = p1.WinsTotal;
        match.Player1LossesTotal            = p1.LossesTotal;
        match.Player1WinsLastYear           = p1.WinsLastYear;
        match.Player1LossesLastYear         = p1.LossesLastYear;
        match.Player1WinsLastMonth          = p1.WinsLastMonth;
        match.Player1LossesLastMonth        = p1.LossesLastMonth;
        match.Player1WinsLastWeek           = p1.WinsLastWeek;
        match.Player1LossesLastWeek         = p1.LossesLastWeek;
        match.Player2WinsTotal              = p2.WinsTotal;
        match.Player2LossesTotal            = p2.LossesTotal;
        match.Player2WinsLastYear           = p2.WinsLastYear;
        match.Player2LossesLastYear         = p2.LossesLastYear;
        match.Player2WinsLastMonth          = p2.WinsLastMonth;
        match.Player2LossesLastMonth        = p2.LossesLastMonth;
        match.Player2WinsLastWeek           = p2.WinsLastWeek;
        match.Player2LossesLastWeek         = p2.LossesLastWeek;
        match.Player1WinsTotalS1            = p1.WinsTotalS1;
        match.Player1LossesTotalS1          = p1.LossesTotalS1;
        match.Player1WinsLastYearS1         = p1.WinsLastYearS1;
        match.Player1LossesLastYearS1       = p1.LossesLastYearS1;
        match.Player1WinsLastMonthS1        = p1.WinsLastMonthS1;
        match.Player1LossesLastMonthS1      = p1.LossesLastMonthS1;
        match.Player1WinsLastWeekS1         = p1.WinsLastWeekS1;
        match.Player1LossesLastWeekS1       = p1.LossesLastWeekS1;
        match.Player2WinsTotalS1            = p2.WinsTotalS1;
        match.Player2LossesTotalS1          = p2.LossesTotalS1;
        match.Player2WinsLastYearS1         = p2.WinsLastYearS1;
        match.Player2LossesLastYearS1       = p2.LossesLastYearS1;
        match.Player2WinsLastMonthS1        = p2.WinsLastMonthS1;
        match.Player2LossesLastMonthS1      = p2.LossesLastMonthS1;
        match.Player2WinsLastWeekS1         = p2.WinsLastWeekS1;
        match.Player2LossesLastWeekS1       = p2.LossesLastWeekS1;
        match.Player1WinsTotalS2            = p1.WinsTotalS2;
        match.Player1LossesTotalS2          = p1.LossesTotalS2;
        match.Player1WinsLastYearS2         = p1.WinsLastYearS2;
        match.Player1LossesLastYearS2       = p1.LossesLastYearS2;
        match.Player1WinsLastMonthS2        = p1.WinsLastMonthS2;
        match.Player1LossesLastMonthS2      = p1.LossesLastMonthS2;
        match.Player1WinsLastWeekS2         = p1.WinsLastWeekS2;
        match.Player1LossesLastWeekS2       = p1.LossesLastWeekS2;
        match.Player2WinsTotalS2            = p2.WinsTotalS2;
        match.Player2LossesTotalS2          = p2.LossesTotalS2;
        match.Player2WinsLastYearS2         = p2.WinsLastYearS2;
        match.Player2LossesLastYearS2       = p2.LossesLastYearS2;
        match.Player2WinsLastMonthS2        = p2.WinsLastMonthS2;
        match.Player2LossesLastMonthS2      = p2.LossesLastMonthS2;
        match.Player2WinsLastWeekS2         = p2.WinsLastWeekS2;
        match.Player2LossesLastWeekS2       = p2.LossesLastWeekS2;
        match.Player1WinsTotalS3            = p1.WinsTotalS3;
        match.Player1LossesTotalS3          = p1.LossesTotalS3;
        match.Player1WinsLastYearS3         = p1.WinsLastYearS3;
        match.Player1LossesLastYearS3       = p1.LossesLastYearS3;
        match.Player1WinsLastMonthS3        = p1.WinsLastMonthS3;
        match.Player1LossesLastMonthS3      = p1.LossesLastMonthS3;
        match.Player1WinsLastWeekS3         = p1.WinsLastWeekS3;
        match.Player1LossesLastWeekS3       = p1.LossesLastWeekS3;
        match.Player2WinsTotalS3            = p2.WinsTotalS3;
        match.Player2LossesTotalS3          = p2.LossesTotalS3;
        match.Player2WinsLastYearS3         = p2.WinsLastYearS3;
        match.Player2LossesLastYearS3       = p2.LossesLastYearS3;
        match.Player2WinsLastMonthS3        = p2.WinsLastMonthS3;
        match.Player2LossesLastMonthS3      = p2.LossesLastMonthS3;
        match.Player2WinsLastWeekS3         = p2.WinsLastWeekS3;
        match.Player2LossesLastWeekS3       = p2.LossesLastWeekS3;
        match.Player1WinsTotalS4            = p1.WinsTotalS4;
        match.Player1LossesTotalS4          = p1.LossesTotalS4;
        match.Player1WinsLastYearS4         = p1.WinsLastYearS4;
        match.Player1LossesLastYearS4       = p1.LossesLastYearS4;
        match.Player1WinsLastMonthS4        = p1.WinsLastMonthS4;
        match.Player1LossesLastMonthS4      = p1.LossesLastMonthS4;
        match.Player1WinsLastWeekS4         = p1.WinsLastWeekS4;
        match.Player1LossesLastWeekS4       = p1.LossesLastWeekS4;
        match.Player2WinsTotalS4            = p2.WinsTotalS4;
        match.Player2LossesTotalS4          = p2.LossesTotalS4;
        match.Player2WinsLastYearS4         = p2.WinsLastYearS4;
        match.Player2LossesLastYearS4       = p2.LossesLastYearS4;
        match.Player2WinsLastMonthS4        = p2.WinsLastMonthS4;
        match.Player2LossesLastMonthS4      = p2.LossesLastMonthS4;
        match.Player2WinsLastWeekS4         = p2.WinsLastWeekS4;
        match.Player2LossesLastWeekS4       = p2.LossesLastWeekS4;
        match.Player1WinsSetsTotal          = p1.WinsSetsTotal;
        match.Player1LossesSetsTotal        = p1.LossesSetsTotal;
        match.Player1WinsSetsLastYear       = p1.WinsSetsLastYear;
        match.Player1LossesSetsLastYear     = p1.LossesSetsLastYear;
        match.Player1WinsSetsLastMonth      = p1.WinsSetsLastMonth;
        match.Player1LossesSetsLastMonth    = p1.LossesSetsLastMonth;
        match.Player1WinsSetsLastWeek       = p1.WinsSetsLastWeek;
        match.Player1LossesSetsLastWeek     = p1.LossesSetsLastWeek;
        match.Player2WinsSetsTotal          = p2.WinsSetsTotal;
        match.Player2LossesSetsTotal        = p2.LossesSetsTotal;
        match.Player2WinsSetsLastYear       = p2.WinsSetsLastYear;
        match.Player2LossesSetsLastYear     = p2.LossesSetsLastYear;
        match.Player2WinsSetsLastMonth      = p2.WinsSetsLastMonth;
        match.Player2LossesSetsLastMonth    = p2.LossesSetsLastMonth;
        match.Player2WinsSetsLastWeek       = p2.WinsSetsLastWeek;
        match.Player2LossesSetsLastWeek     = p2.LossesSetsLastWeek;
        match.Player1WinsSetsTotalS1        = p1.WinsSetsTotalS1;
        match.Player1LossesSetsTotalS1      = p1.LossesSetsTotalS1;
        match.Player1WinsSetsLastYearS1     = p1.WinsSetsLastYearS1;
        match.Player1LossesSetsLastYearS1   = p1.LossesSetsLastYearS1;
        match.Player1WinsSetsLastMonthS1    = p1.WinsSetsLastMonthS1;
        match.Player1LossesSetsLastMonthS1  = p1.LossesSetsLastMonthS1;
        match.Player1WinsSetsLastWeekS1     = p1.WinsSetsLastWeekS1;
        match.Player1LossesSetsLastWeekS1   = p1.LossesSetsLastWeekS1;
        match.Player2WinsSetsTotalS1        = p2.WinsSetsTotalS1;
        match.Player2LossesSetsTotalS1      = p2.LossesSetsTotalS1;
        match.Player2WinsSetsLastYearS1     = p2.WinsSetsLastYearS1;
        match.Player2LossesSetsLastYearS1   = p2.LossesSetsLastYearS1;
        match.Player2WinsSetsLastMonthS1    = p2.WinsSetsLastMonthS1;
        match.Player2LossesSetsLastMonthS1  = p2.LossesSetsLastMonthS1;
        match.Player2WinsSetsLastWeekS1     = p2.WinsSetsLastWeekS1;
        match.Player2LossesSetsLastWeekS1   = p2.LossesSetsLastWeekS1;
        match.Player1WinsSetsTotalS2        = p1.WinsSetsTotalS2;
        match.Player1LossesSetsTotalS2      = p1.LossesSetsTotalS2;
        match.Player1WinsSetsLastYearS2     = p1.WinsSetsLastYearS2;
        match.Player1LossesSetsLastYearS2   = p1.LossesSetsLastYearS2;
        match.Player1WinsSetsLastMonthS2    = p1.WinsSetsLastMonthS2;
        match.Player1LossesSetsLastMonthS2  = p1.LossesSetsLastMonthS2;
        match.Player1WinsSetsLastWeekS2     = p1.WinsSetsLastWeekS2;
        match.Player1LossesSetsLastWeekS2   = p1.LossesSetsLastWeekS2;
        match.Player2WinsSetsTotalS2        = p2.WinsSetsTotalS2;
        match.Player2LossesSetsTotalS2      = p2.LossesSetsTotalS2;
        match.Player2WinsSetsLastYearS2     = p2.WinsSetsLastYearS2;
        match.Player2LossesSetsLastYearS2   = p2.LossesSetsLastYearS2;
        match.Player2WinsSetsLastMonthS2    = p2.WinsSetsLastMonthS2;
        match.Player2LossesSetsLastMonthS2  = p2.LossesSetsLastMonthS2;
        match.Player2WinsSetsLastWeekS2     = p2.WinsSetsLastWeekS2;
        match.Player2LossesSetsLastWeekS2   = p2.LossesSetsLastWeekS2;
        match.Player1WinsSetsTotalS3        = p1.WinsSetsTotalS3;
        match.Player1LossesSetsTotalS3      = p1.LossesSetsTotalS3;
        match.Player1WinsSetsLastYearS3     = p1.WinsSetsLastYearS3;
        match.Player1LossesSetsLastYearS3   = p1.LossesSetsLastYearS3;
        match.Player1WinsSetsLastMonthS3    = p1.WinsSetsLastMonthS3;
        match.Player1LossesSetsLastMonthS3  = p1.LossesSetsLastMonthS3;
        match.Player1WinsSetsLastWeekS3     = p1.WinsSetsLastWeekS3;
        match.Player1LossesSetsLastWeekS3   = p1.LossesSetsLastWeekS3;
        match.Player2WinsSetsTotalS3        = p2.WinsSetsTotalS3;
        match.Player2LossesSetsTotalS3      = p2.LossesSetsTotalS3;
        match.Player2WinsSetsLastYearS3     = p2.WinsSetsLastYearS3;
        match.Player2LossesSetsLastYearS3   = p2.LossesSetsLastYearS3;
        match.Player2WinsSetsLastMonthS3    = p2.WinsSetsLastMonthS3;
        match.Player2LossesSetsLastMonthS3  = p2.LossesSetsLastMonthS3;
        match.Player2WinsSetsLastWeekS3     = p2.WinsSetsLastWeekS3;
        match.Player2LossesSetsLastWeekS3   = p2.LossesSetsLastWeekS3;
        match.Player1WinsSetsTotalS4        = p1.WinsSetsTotalS4;
        match.Player1LossesSetsTotalS4      = p1.LossesSetsTotalS4;
        match.Player1WinsSetsLastYearS4     = p1.WinsSetsLastYearS4;
        match.Player1LossesSetsLastYearS4   = p1.LossesSetsLastYearS4;
        match.Player1WinsSetsLastMonthS4    = p1.WinsSetsLastMonthS4;
        match.Player1LossesSetsLastMonthS4  = p1.LossesSetsLastMonthS4;
        match.Player1WinsSetsLastWeekS4     = p1.WinsSetsLastWeekS4;
        match.Player1LossesSetsLastWeekS4   = p1.LossesSetsLastWeekS4;
        match.Player2WinsSetsTotalS4        = p2.WinsSetsTotalS4;
        match.Player2LossesSetsTotalS4      = p2.LossesSetsTotalS4;
        match.Player2WinsSetsLastYearS4     = p2.WinsSetsLastYearS4;
        match.Player2LossesSetsLastYearS4   = p2.LossesSetsLastYearS4;
        match.Player2WinsSetsLastMonthS4    = p2.WinsSetsLastMonthS4;
        match.Player2LossesSetsLastMonthS4  = p2.LossesSetsLastMonthS4;
        match.Player2WinsSetsLastWeekS4     = p2.WinsSetsLastWeekS4;
        match.Player2LossesSetsLastWeekS4   = p2.LossesSetsLastWeekS4;
        match.Player1WinsGamesTotal         = p1.WinsGamesTotal;
        match.Player1LossesGamesTotal       = p1.LossesGamesTotal;
        match.Player1WinsGamesLastYear      = p1.WinsGamesLastYear;
        match.Player1LossesGamesLastYear    = p1.LossesGamesLastYear;
        match.Player1WinsGamesLastMonth     = p1.WinsGamesLastMonth;
        match.Player1LossesGamesLastMonth   = p1.LossesGamesLastMonth;
        match.Player1WinsGamesLastWeek      = p1.WinsGamesLastWeek;
        match.Player1LossesGamesLastWeek    = p1.LossesGamesLastWeek;
        match.Player2WinsGamesTotal         = p2.WinsGamesTotal;
        match.Player2LossesGamesTotal       = p2.LossesGamesTotal;
        match.Player2WinsGamesLastYear      = p2.WinsGamesLastYear;
        match.Player2LossesGamesLastYear    = p2.LossesGamesLastYear;
        match.Player2WinsGamesLastMonth     = p2.WinsGamesLastMonth;
        match.Player2LossesGamesLastMonth   = p2.LossesGamesLastMonth;
        match.Player2WinsGamesLastWeek      = p2.WinsGamesLastWeek;
        match.Player2LossesGamesLastWeek    = p2.LossesGamesLastWeek;
        match.Player1WinsGamesTotalS1       = p1.WinsGamesTotalS1;
        match.Player1LossesGamesTotalS1     = p1.LossesGamesTotalS1;
        match.Player1WinsGamesLastYearS1    = p1.WinsGamesLastYearS1;
        match.Player1LossesGamesLastYearS1  = p1.LossesGamesLastYearS1;
        match.Player1WinsGamesLastMonthS1   = p1.WinsGamesLastMonthS1;
        match.Player1LossesGamesLastMonthS1 = p1.LossesGamesLastMonthS1;
        match.Player1WinsGamesLastWeekS1    = p1.WinsGamesLastWeekS1;
        match.Player1LossesGamesLastWeekS1  = p1.LossesGamesLastWeekS1;
        match.Player2WinsGamesTotalS1       = p2.WinsGamesTotalS1;
        match.Player2LossesGamesTotalS1     = p2.LossesGamesTotalS1;
        match.Player2WinsGamesLastYearS1    = p2.WinsGamesLastYearS1;
        match.Player2LossesGamesLastYearS1  = p2.LossesGamesLastYearS1;
        match.Player2WinsGamesLastMonthS1   = p2.WinsGamesLastMonthS1;
        match.Player2LossesGamesLastMonthS1 = p2.LossesGamesLastMonthS1;
        match.Player2WinsGamesLastWeekS1    = p2.WinsGamesLastWeekS1;
        match.Player2LossesGamesLastWeekS1  = p2.LossesGamesLastWeekS1;
        match.Player1WinsGamesTotalS2       = p1.WinsGamesTotalS2;
        match.Player1LossesGamesTotalS2     = p1.LossesGamesTotalS2;
        match.Player1WinsGamesLastYearS2    = p1.WinsGamesLastYearS2;
        match.Player1LossesGamesLastYearS2  = p1.LossesGamesLastYearS2;
        match.Player1WinsGamesLastMonthS2   = p1.WinsGamesLastMonthS2;
        match.Player1LossesGamesLastMonthS2 = p1.LossesGamesLastMonthS2;
        match.Player1WinsGamesLastWeekS2    = p1.WinsGamesLastWeekS2;
        match.Player1LossesGamesLastWeekS2  = p1.LossesGamesLastWeekS2;
        match.Player2WinsGamesTotalS2       = p2.WinsGamesTotalS2;
        match.Player2LossesGamesTotalS2     = p2.LossesGamesTotalS2;
        match.Player2WinsGamesLastYearS2    = p2.WinsGamesLastYearS2;
        match.Player2LossesGamesLastYearS2  = p2.LossesGamesLastYearS2;
        match.Player2WinsGamesLastMonthS2   = p2.WinsGamesLastMonthS2;
        match.Player2LossesGamesLastMonthS2 = p2.LossesGamesLastMonthS2;
        match.Player2WinsGamesLastWeekS2    = p2.WinsGamesLastWeekS2;
        match.Player2LossesGamesLastWeekS2  = p2.LossesGamesLastWeekS2;
        match.Player1WinsGamesTotalS3       = p1.WinsGamesTotalS3;
        match.Player1LossesGamesTotalS3     = p1.LossesGamesTotalS3;
        match.Player1WinsGamesLastYearS3    = p1.WinsGamesLastYearS3;
        match.Player1LossesGamesLastYearS3  = p1.LossesGamesLastYearS3;
        match.Player1WinsGamesLastMonthS3   = p1.WinsGamesLastMonthS3;
        match.Player1LossesGamesLastMonthS3 = p1.LossesGamesLastMonthS3;
        match.Player1WinsGamesLastWeekS3    = p1.WinsGamesLastWeekS3;
        match.Player1LossesGamesLastWeekS3  = p1.LossesGamesLastWeekS3;
        match.Player2WinsGamesTotalS3       = p2.WinsGamesTotalS3;
        match.Player2LossesGamesTotalS3     = p2.LossesGamesTotalS3;
        match.Player2WinsGamesLastYearS3    = p2.WinsGamesLastYearS3;
        match.Player2LossesGamesLastYearS3  = p2.LossesGamesLastYearS3;
        match.Player2WinsGamesLastMonthS3   = p2.WinsGamesLastMonthS3;
        match.Player2LossesGamesLastMonthS3 = p2.LossesGamesLastMonthS3;
        match.Player2WinsGamesLastWeekS3    = p2.WinsGamesLastWeekS3;
        match.Player2LossesGamesLastWeekS3  = p2.LossesGamesLastWeekS3;
        match.Player1WinsGamesTotalS4       = p1.WinsGamesTotalS4;
        match.Player1LossesGamesTotalS4     = p1.LossesGamesTotalS4;
        match.Player1WinsGamesLastYearS4    = p1.WinsGamesLastYearS4;
        match.Player1LossesGamesLastYearS4  = p1.LossesGamesLastYearS4;
        match.Player1WinsGamesLastMonthS4   = p1.WinsGamesLastMonthS4;
        match.Player1LossesGamesLastMonthS4 = p1.LossesGamesLastMonthS4;
        match.Player1WinsGamesLastWeekS4    = p1.WinsGamesLastWeekS4;
        match.Player1LossesGamesLastWeekS4  = p1.LossesGamesLastWeekS4;
        match.Player2WinsGamesTotalS4       = p2.WinsGamesTotalS4;
        match.Player2LossesGamesTotalS4     = p2.LossesGamesTotalS4;
        match.Player2WinsGamesLastYearS4    = p2.WinsGamesLastYearS4;
        match.Player2LossesGamesLastYearS4  = p2.LossesGamesLastYearS4;
        match.Player2WinsGamesLastMonthS4   = p2.WinsGamesLastMonthS4;
        match.Player2LossesGamesLastMonthS4 = p2.LossesGamesLastMonthS4;
        match.Player2WinsGamesLastWeekS4    = p2.WinsGamesLastWeekS4;
        match.Player2LossesGamesLastWeekS4  = p2.LossesGamesLastWeekS4;
    }

    public static void UpdatePlayerWinLoss(Models.Match match, Models.Player p1, Models.Player p2)
    {
        p1.WinsTotal            ++;
        p1.WinsLastYear         ++;
        p1.WinsLastMonth        ++;
        p1.WinsLastWeek         ++;
        p2.LossesTotal          ++;
        p2.LossesLastYear       ++;
        p2.LossesLastMonth      ++;
        p2.LossesLastWeek       ++;
        p1.WinsSetsTotal        += match.P1SetsWon;
        p1.WinsSetsLastYear     += match.P1SetsWon;
        p1.WinsSetsLastMonth    += match.P1SetsWon;
        p1.WinsSetsLastWeek     += match.P1SetsWon;
        p1.LossesSetsTotal      += match.P1SetsLoss;
        p1.LossesSetsLastYear   += match.P1SetsLoss;
        p1.LossesSetsLastMonth  += match.P1SetsLoss;
        p1.LossesSetsLastWeek   += match.P1SetsLoss;
        p2.WinsSetsTotal        += match.P2SetsWon;
        p2.WinsSetsLastYear     += match.P2SetsWon;
        p2.WinsSetsLastMonth    += match.P2SetsWon;
        p2.WinsSetsLastWeek     += match.P2SetsWon;
        p2.LossesSetsTotal      += match.P2SetsLoss;
        p2.LossesSetsLastYear   += match.P2SetsLoss;
        p2.LossesSetsLastMonth  += match.P2SetsLoss;
        p2.LossesSetsLastWeek   += match.P2SetsLoss;
        p1.WinsGamesTotal       += match.P1GamesWon;
        p1.WinsGamesLastYear    += match.P1GamesWon;
        p1.WinsGamesLastMonth   += match.P1GamesWon;
        p1.WinsGamesLastWeek    += match.P1GamesWon;
        p1.LossesGamesTotal     += match.P1GamesLoss;
        p1.LossesGamesLastYear  += match.P1GamesLoss;
        p1.LossesGamesLastMonth += match.P1GamesLoss;
        p1.LossesGamesLastWeek  += match.P1GamesLoss;
        p2.WinsGamesTotal       += match.P2GamesWon;
        p2.WinsGamesLastYear    += match.P2GamesWon;
        p2.WinsGamesLastMonth   += match.P2GamesWon;
        p2.WinsGamesLastWeek    += match.P2GamesWon;
        p2.LossesGamesTotal     += match.P2GamesLoss;
        p2.LossesGamesLastYear  += match.P2GamesLoss;
        p2.LossesGamesLastMonth += match.P2GamesLoss;
        p2.LossesGamesLastWeek  += match.P2GamesLoss;

        switch (match.SurfaceId)
        {
            case 1:
                p1.WinsTotalS1            ++;
                p1.WinsLastYearS1         ++;
                p1.WinsLastMonthS1        ++;
                p1.WinsLastWeekS1         ++;
                p2.LossesTotalS1          ++;
                p2.LossesLastYearS1       ++;
                p2.LossesLastMonthS1      ++;
                p2.LossesLastWeekS1       ++;
                p1.WinsSetsTotalS1        += match.P1SetsWon;
                p1.WinsSetsLastYearS1     += match.P1SetsWon;
                p1.WinsSetsLastMonthS1    += match.P1SetsWon;
                p1.WinsSetsLastWeekS1     += match.P1SetsWon;
                p1.LossesSetsTotalS1      += match.P1SetsLoss;
                p1.LossesSetsLastYearS1   += match.P1SetsLoss;
                p1.LossesSetsLastMonthS1  += match.P1SetsLoss;
                p1.LossesSetsLastWeekS1   += match.P1SetsLoss;
                p2.WinsSetsTotalS1        += match.P2SetsWon;
                p2.WinsSetsLastYearS1     += match.P2SetsWon;
                p2.WinsSetsLastMonthS1    += match.P2SetsWon;
                p2.WinsSetsLastWeekS1     += match.P2SetsWon;
                p2.LossesSetsTotalS1      += match.P2SetsLoss;
                p2.LossesSetsLastYearS1   += match.P2SetsLoss;
                p2.LossesSetsLastMonthS1  += match.P2SetsLoss;
                p2.LossesSetsLastWeekS1   += match.P2SetsLoss;
                p1.WinsGamesTotalS1       += match.P1GamesWon;
                p1.WinsGamesLastYearS1    += match.P1GamesWon;
                p1.WinsGamesLastMonthS1   += match.P1GamesWon;
                p1.WinsGamesLastWeekS1    += match.P1GamesWon;
                p1.LossesGamesTotalS1     += match.P1GamesLoss;
                p1.LossesGamesLastYearS1  += match.P1GamesLoss;
                p1.LossesGamesLastMonthS1 += match.P1GamesLoss;
                p1.LossesGamesLastWeekS1  += match.P1GamesLoss;
                p2.WinsGamesTotalS1       += match.P2GamesWon;
                p2.WinsGamesLastYearS1    += match.P2GamesWon;
                p2.WinsGamesLastMonthS1   += match.P2GamesWon;
                p2.WinsGamesLastWeekS1    += match.P2GamesWon;
                p2.LossesGamesTotalS1     += match.P2GamesLoss;
                p2.LossesGamesLastYearS1  += match.P2GamesLoss;
                p2.LossesGamesLastMonthS1 += match.P2GamesLoss;
                p2.LossesGamesLastWeekS1  += match.P2GamesLoss;
                break;
            case 2:
                p1.WinsTotalS2            ++;
                p1.WinsLastYearS2         ++;
                p1.WinsLastMonthS2        ++;
                p1.WinsLastWeekS2         ++;
                p2.LossesTotalS2          ++;
                p2.LossesLastYearS2       ++;
                p2.LossesLastMonthS2      ++;
                p2.LossesLastWeekS2       ++;
                p1.WinsSetsTotalS2        += match.P1SetsWon;
                p1.WinsSetsLastYearS2     += match.P1SetsWon;
                p1.WinsSetsLastMonthS2    += match.P1SetsWon;
                p1.WinsSetsLastWeekS2     += match.P1SetsWon;
                p1.LossesSetsTotalS2      += match.P1SetsLoss;
                p1.LossesSetsLastYearS2   += match.P1SetsLoss;
                p1.LossesSetsLastMonthS2  += match.P1SetsLoss;
                p1.LossesSetsLastWeekS2   += match.P1SetsLoss;
                p2.WinsSetsTotalS2        += match.P2SetsWon;
                p2.WinsSetsLastYearS2     += match.P2SetsWon;
                p2.WinsSetsLastMonthS2    += match.P2SetsWon;
                p2.WinsSetsLastWeekS2     += match.P2SetsWon;
                p2.LossesSetsTotalS2      += match.P2SetsLoss;
                p2.LossesSetsLastYearS2   += match.P2SetsLoss;
                p2.LossesSetsLastMonthS2  += match.P2SetsLoss;
                p2.LossesSetsLastWeekS2   += match.P2SetsLoss;
                p1.WinsGamesTotalS2       += match.P1GamesWon;
                p1.WinsGamesLastYearS2    += match.P1GamesWon;
                p1.WinsGamesLastMonthS2   += match.P1GamesWon;
                p1.WinsGamesLastWeekS2    += match.P1GamesWon;
                p1.LossesGamesTotalS2     += match.P1GamesLoss;
                p1.LossesGamesLastYearS2  += match.P1GamesLoss;
                p1.LossesGamesLastMonthS2 += match.P1GamesLoss;
                p1.LossesGamesLastWeekS2  += match.P1GamesLoss;
                p2.WinsGamesTotalS2       += match.P2GamesWon;
                p2.WinsGamesLastYearS2    += match.P2GamesWon;
                p2.WinsGamesLastMonthS2   += match.P2GamesWon;
                p2.WinsGamesLastWeekS2    += match.P2GamesWon;
                p2.LossesGamesTotalS2     += match.P2GamesLoss;
                p2.LossesGamesLastYearS2  += match.P2GamesLoss;
                p2.LossesGamesLastMonthS2 += match.P2GamesLoss;
                p2.LossesGamesLastWeekS2  += match.P2GamesLoss;
                break;
            case 3:
                p1.WinsTotalS3            ++;
                p1.WinsLastYearS3         ++;
                p1.WinsLastMonthS3        ++;
                p1.WinsLastWeekS3         ++;
                p2.LossesTotalS3          ++;
                p2.LossesLastYearS3       ++;
                p2.LossesLastMonthS3      ++;
                p2.LossesLastWeekS3       ++;
                p1.WinsSetsTotalS3        += match.P1SetsWon;
                p1.WinsSetsLastYearS3     += match.P1SetsWon;
                p1.WinsSetsLastMonthS3    += match.P1SetsWon;
                p1.WinsSetsLastWeekS3     += match.P1SetsWon;
                p1.LossesSetsTotalS3      += match.P1SetsLoss;
                p1.LossesSetsLastYearS3   += match.P1SetsLoss;
                p1.LossesSetsLastMonthS3  += match.P1SetsLoss;
                p1.LossesSetsLastWeekS3   += match.P1SetsLoss;
                p2.WinsSetsTotalS3        += match.P2SetsWon;
                p2.WinsSetsLastYearS3     += match.P2SetsWon;
                p2.WinsSetsLastMonthS3    += match.P2SetsWon;
                p2.WinsSetsLastWeekS3     += match.P2SetsWon;
                p2.LossesSetsTotalS3      += match.P2SetsLoss;
                p2.LossesSetsLastYearS3   += match.P2SetsLoss;
                p2.LossesSetsLastMonthS3  += match.P2SetsLoss;
                p2.LossesSetsLastWeekS3   += match.P2SetsLoss;
                p1.WinsGamesTotalS3       += match.P1GamesWon;
                p1.WinsGamesLastYearS3    += match.P1GamesWon;
                p1.WinsGamesLastMonthS3   += match.P1GamesWon;
                p1.WinsGamesLastWeekS3    += match.P1GamesWon;
                p1.LossesGamesTotalS3     += match.P1GamesLoss;
                p1.LossesGamesLastYearS3  += match.P1GamesLoss;
                p1.LossesGamesLastMonthS3 += match.P1GamesLoss;
                p1.LossesGamesLastWeekS3  += match.P1GamesLoss;
                p2.WinsGamesTotalS3       += match.P2GamesWon;
                p2.WinsGamesLastYearS3    += match.P2GamesWon;
                p2.WinsGamesLastMonthS3   += match.P2GamesWon;
                p2.WinsGamesLastWeekS3    += match.P2GamesWon;
                p2.LossesGamesTotalS3     += match.P2GamesLoss;
                p2.LossesGamesLastYearS3  += match.P2GamesLoss;
                p2.LossesGamesLastMonthS3 += match.P2GamesLoss;
                p2.LossesGamesLastWeekS3  += match.P2GamesLoss;
                break;
            case 4:
                p1.WinsTotalS4            ++;
                p1.WinsLastYearS4         ++;
                p1.WinsLastMonthS4        ++;
                p1.WinsLastWeekS4         ++;
                p2.LossesTotalS4          ++;
                p2.LossesLastYearS4       ++;
                p2.LossesLastMonthS4      ++;
                p2.LossesLastWeekS4       ++;
                p1.WinsSetsTotalS4        += match.P1SetsWon;
                p1.WinsSetsLastYearS4     += match.P1SetsWon;
                p1.WinsSetsLastMonthS4    += match.P1SetsWon;
                p1.WinsSetsLastWeekS4     += match.P1SetsWon;
                p1.LossesSetsTotalS4      += match.P1SetsLoss;
                p1.LossesSetsLastYearS4   += match.P1SetsLoss;
                p1.LossesSetsLastMonthS4  += match.P1SetsLoss;
                p1.LossesSetsLastWeekS4   += match.P1SetsLoss;
                p2.WinsSetsTotalS4        += match.P2SetsWon;
                p2.WinsSetsLastYearS4     += match.P2SetsWon;
                p2.WinsSetsLastMonthS4    += match.P2SetsWon;
                p2.WinsSetsLastWeekS4     += match.P2SetsWon;
                p2.LossesSetsTotalS4      += match.P2SetsLoss;
                p2.LossesSetsLastYearS4   += match.P2SetsLoss;
                p2.LossesSetsLastMonthS4  += match.P2SetsLoss;
                p2.LossesSetsLastWeekS4   += match.P2SetsLoss;
                p1.WinsGamesTotalS4       += match.P1GamesWon;
                p1.WinsGamesLastYearS4    += match.P1GamesWon;
                p1.WinsGamesLastMonthS4   += match.P1GamesWon;
                p1.WinsGamesLastWeekS4    += match.P1GamesWon;
                p1.LossesGamesTotalS4     += match.P1GamesLoss;
                p1.LossesGamesLastYearS4  += match.P1GamesLoss;
                p1.LossesGamesLastMonthS4 += match.P1GamesLoss;
                p1.LossesGamesLastWeekS4  += match.P1GamesLoss;
                p2.WinsGamesTotalS4       += match.P2GamesWon;
                p2.WinsGamesLastYearS4    += match.P2GamesWon;
                p2.WinsGamesLastMonthS4   += match.P2GamesWon;
                p2.WinsGamesLastWeekS4    += match.P2GamesWon;
                p2.LossesGamesTotalS4     += match.P2GamesLoss;
                p2.LossesGamesLastYearS4  += match.P2GamesLoss;
                p2.LossesGamesLastMonthS4 += match.P2GamesLoss;
                p2.LossesGamesLastWeekS4  += match.P2GamesLoss;
                break;
            default:
                break;
        }
    }
}