name: Deploy Angular to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'BonzoByte.Frontend/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: List repo (debug)
        run: |
          pwd
          ls -la
          echo "---- BonzoByte.Frontend ----"
          ls -la BonzoByte.Frontend || true

      - name: Install deps
        working-directory: BonzoByte.Frontend
        run: npm ci

      # Ako build traži ime projekta, zamijeni naredbu ispod sa:
      # npx ng build BonzoByte.Frontend --configuration production --base-href "/BonzoByte/" --deploy-url "/BonzoByte/" --output-path dist/site
      - name: Build Angular
        working-directory: BonzoByte.Frontend
        run: npx ng build --configuration production --base-href "/BonzoByte/" --deploy-url "/BonzoByte/" --output-path dist/site

      - name: SPA 404 fallback
        working-directory: BonzoByte.Frontend
        run: cp dist/site/index.html dist/site/404.html

      - name: List output (debug)
        working-directory: BonzoByte.Frontend
        run: ls -la dist/site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: BonzoByte.Frontend/dist/site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
